export const CERTIFICATE_CLIENT_CONFIG = {
  apiPath: "/api/v1/certificates",
  listTimeoutMs: 15_000,
  downloadTimeoutMs: 35_000,
  staleTimeMs: 30_000,
  releaseObjectUrlMs: 1000,
  settingsPath: "/settings",
  collectionPath: "/certificates",
  issuancePollIntervalMs: 3_000,
  issuancePollLimit: 6,
} as const;

export const CERTIFICATE_LABELS = {
  statuses: { issued: "Issued", pending_name: "Name required", revoked: "Revoked" },
  types: { course_completion: "Course completion", role_readiness: "Role readiness" },
  eyebrow: "Your learning, recognised",
  heading: "My Certificates",
  introduction: "A record of what you have achieved. Download it. Share it.",
  filter: "Certificate type",
  allTypes: "All certificates",
  loading: "Loading certificates",
  loadingOne: "Loading certificate",
  loadError: "Could not load certificates.",
  levelLoadError: "Could not load your certificate.",
  retry: "Try again",
  emptyHeading: "Your next achievement starts here",
  emptyDescription: "Complete a course or learning path to earn a certificate.",
  levelEmpty: "No certificate is available for this level yet.",
  checking: "Checking for your certificate…",
  issuanceHelp:
    "Your certificate appears here once all course requirements and any required reviews are complete. You can check again or return from My Certificates.",
  completionHeading: "Your course certificate",
  completionIntroduction: "A milestone worth keeping. Your achievement, ready to take with you.",
  ready: "Your certificate is ready",
  allCertificates: "View all certificates",
  backToCourses: "Back to my courses",
  view: "View certificate",
  preview: "Certificate preview",
  issuer: "Rareminds LTE",
  certificateOfCompletion: "Certificate of completion",
  recipient: "Awarded to",
  achievement: "For successfully completing",
  credential: "Credential ID",
  verify: "Verify certificate",
  saved: "Saved in My Certificates. Download a PDF or share your verification link.",
  unavailableDownload: "PDF download is temporarily unavailable. Please check again.",
  invalidLevel: "This certificate link is invalid. Open your certificate from My Certificates.",
  completed: "Completed",
  nameRequired: "Add your name in Settings to receive your certificate",
  revoked: "This certificate has been revoked.",
  download: "Download certificate",
  preparing: "Preparing PDF…",
  downloaded: "Certificate downloaded",
  downloadError: "Could not download your certificate. Please try again.",
  copy: "Copy verification link",
  copied: "Verification link copied",
  copyError: "Could not copy the link. Please try again.",
  retryAfter: (seconds: number) => `Please retry in ${seconds} seconds.`,
} as const;
