/** Compile the PDF's utility classes from LTE's one global stylesheet.
 * Build-time only: backend runtime never imports frontend code or CSS. */
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import process from 'node:process';
import { compile } from 'tailwindcss';

const require = createRequire(import.meta.url);
const project = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const stylesPath = resolve(project, 'src/app/styles/index.css');
const templatePath = resolve(project, 'functions/lib/certificates/template.ts');
const outputPath = resolve(project, 'functions/lib/certificates/templateStyles.ts');
const template = readFileSync(templatePath, 'utf8');
const candidates = [...new Set([...template.matchAll(/class="([^"]+)"/g)].flatMap(match => match[1].split(/\s+/)))];
const compiler = await compile(readFileSync(stylesPath, 'utf8'), {
  base: dirname(stylesPath),
  loadStylesheet: async (id, base) => {
    const path = id === 'tailwindcss' ? require.resolve('tailwindcss/index.css') : resolve(base, id);
    return { path, base: dirname(path), content: readFileSync(path, 'utf8') };
  },
});
const css = compiler.build(candidates).replace(/<\/style/gi, '<\\/style');
const source = `// Generated by scripts/certificates/templateStyles.mjs from the global Tailwind theme.\n// Do not hand-edit. No frontend runtime dependency.\nexport const CERTIFICATE_STYLES = ${JSON.stringify(css)};\n`;
// Keep generated output canonical under the same formatter enforced by commit hooks.
const output = execFileSync(process.execPath, [
  require.resolve('@biomejs/biome/bin/biome'), 'format', '--stdin-file-path', outputPath,
], { input: source, encoding: 'utf8', timeout: 10_000 });
if (process.argv.includes('--check')) {
  if (readFileSync(outputPath, 'utf8') !== output) throw new Error('Certificate styles are stale; run npm run certificates:styles');
} else writeFileSync(outputPath, output);
