-- Generated from LTE_LEARNING_CATALOG_TEMPLATE.xlsx: public.artifact_questions.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.artifact_questions
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('b5fc4ee1-dbc6-5ea9-9d6d-b265ed9fb601'::uuid, 'fc3b022f-135b-569e-a5e4-63f3e91a18c8'::uuid, 1, 'Complete the Course Readiness Sheet', 'Capture Guest & Visitor Reception work evidence by identifying evidence sources and L1-safe boundaries.', '{"required_fields": "Required fields include the course and learner role, case anchor, course mission, evidence types, visible facts, unknown information, risk, L1 allowed actions, L1 prohibited actions, evidence-before-action statement, behaviour commitment, promise-safe response, open validation question, and Module 1 handoff.", "pass_criteria": "The learner correctly names at least three evidence types, one L1 boundary, one risk, and one validation question.", "critical_fail": "The learner claims authority to approve check-in or release access."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('f34a240b-1e45-54d2-936a-ec448785afa2'::uuid, 'bda47fb5-c7a2-5379-ade0-3213b38a4bf8'::uuid, 1, 'Complete the Case Intake Note', 'Capture guest arrival work evidence in a structured Case Intake Note.', '{"required_fields": "Required fields include the course and module context, Module 0 input, case summary, reservation facts, ID evidence, guest claim, PMS note, room-status signal, assumptions, missing information, L1 allowed actions, L1 prohibited actions, clarification questions, supervisor-review trigger, and Module 2 handoff.", "pass_criteria": "Facts and assumptions are separated, the ID variation, payment hold, and inspection status are not ignored, and the L1 boundary is clear.", "critical_fail": "The learner promises key or access, confirms check-in readiness, or ignores the ID, payment, or room-status signal."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('e2400924-4696-54f2-ba32-a44f2fc07e5b'::uuid, '7336d607-35ea-5036-8b55-580767dda89b'::uuid, 1, 'Complete the Evidence Validation Checklist', 'Confirm guest/visitor reception eligibility and readiness evidence.', '{"required_fields": "Required fields include the evidence item, source, observed value, expected value, validation status, blocker type, reason, impact, owner or review need, risk flag, revision note, safe next step, and Module 3 handoff.", "pass_criteria": "The learner correctly classifies the ID variation, room-inspection status, payment hold, and missing or confirmed evidence.", "critical_fail": "The learner marks the case as ready or recommends access despite an unresolved ID, payment, or room-readiness blocker."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('fefc9afa-3aa8-544d-8873-cd9a89e5e26a'::uuid, 'bf5260af-952f-5bc6-9805-40e00b785fab'::uuid, 1, 'Complete the Action or Handoff Note', 'Prepare a role-safe guest arrival handoff note using validated identity, booking, payment/readiness, room-status, and service handoff evidence.', '{"required_fields": "Required fields include the case summary, validated evidence, blocker, risk, owner or review route, recommended next step, prohibited L1 action, guest communication, internal handoff wording, revision note, and Module 4 input.", "pass_criteria": "The handoff is clear, evidence-backed, owner-specific, and avoids approval or access-release language.", "critical_fail": "The learner releases key or access, approves check-in, or removes a blocker from the handoff."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('563bcbdb-e3ce-54c1-8191-829913c8cf09'::uuid, '2d47e5d6-eace-5acd-a80b-b362351309bd'::uuid, 1, 'Complete the Risk and Escalation Note', 'Recognize blocker and route service handoff or escalation using evidence.', '{"required_fields": "Required fields include the blocker type, evidence source and status, consequence, owner or escalation route, urgency, safe next step, guest communication, internal escalation wording, follow-up, revision note, and Module 5 handoff.", "pass_criteria": "The escalation identifies the correct blocker, evidence, owner, consequence, and safe next step without bypassing authority.", "critical_fail": "The learner bypasses escalation, hides a blocker, or proceeds despite an unresolved ID, payment, or room-status issue."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('39cb826a-d903-5bc9-a09d-a0c5209964de'::uuid, 'de69b051-e2ab-56b2-a17a-87bd54042672'::uuid, 1, 'Complete the Quality and Closure Report', 'Communicate closure status and quality-check guest arrival readiness evidence.', '{"required_fields": "Required fields include completed L1 checks, unresolved blockers, owner action pending, communication sent, no-access statement, remaining risk, closure status or recommendation, evidence trail, revision note, and Module 6 handoff.", "pass_criteria": "The report clearly states the completed checks, unresolved risks, pending owner actions, and absence of unauthorised final approval.", "critical_fail": "The learner falsely closes an unresolved payment, readiness, or access issue or states that check-in has been approved."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('1e0dd5fd-2fde-587d-a2fe-02d38ebed6c5'::uuid, 'f90d981e-929e-5359-8e0c-92989e7ca89f'::uuid, 1, 'Complete the Final Portfolio Pack', 'Defend and transfer guest/visitor arrival-readiness evidence handling across a new simple case.', '{"required_fields": "Required fields include the artifact-chain index, evidence and decision proof, role-boundary proof, improvement proof, strongest capability evidence, guest-case decision defence, visitor evidence, visitor missing evidence or risk, visitor owner and safe step, visitor communication, role-boundary defence, and transfer explanation or reflection.", "pass_criteria": "The portfolio includes all artifacts, revised evidence, decision defence, a visitor-transfer response, safe escalation, and role-boundary proof.", "critical_fail": "The learner independently approves visitor or guest access or submits the portfolio without an evidence chain or transfer proof."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;

COMMIT;
