-- Generated from LTE_LEARNING_CATALOG_CIE_CAP_003_LINKS_COMPLETE.xlsx: public.artifact_questions.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.artifact_questions
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('62071a82-268b-51ed-96e0-ce087f6156d4'::uuid, 'b0e7d927-c690-5059-a585-628694be9551'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M0_Course_Readiness_Sheet_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L1 M00: CIE-CAP-003_M0_Course_Readiness_Sheet_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M0_Course_Readiness_Sheet_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('ae94b129-816f-5ef7-bc10-a637f9f21e1a'::uuid, 'd91a4253-9f65-5513-8a30-989114c72ec4'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M0_Course_Readiness_Sheet_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L1 M00: CIE-CAP-003_M0_Course_Readiness_Sheet_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M0_Course_Readiness_Sheet_Practice_Artifact.xlsx without replacing its required structure. Required fields: Case ID, Learner Role, Allowed L1 Actions, Excluded Authority, Evidence Pack Received, Final Portfolio Proof. Required evidence: E-M0-01, E-M0-02, E-M0-03.", "pass_criteria": "Learner must complete Case ID, Learner Role, Allowed L1 Actions, Excluded Authority, Evidence Pack Received, Final Portfolio Proof, cite E-M0-01, E-M0-02, E-M0-03, extract HN-24A, A-314, 2026-07-08 review, L1 cannot approve baseline/EOT/claims, choose safe role action, and avoid approval language.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('b9e0b724-e72c-534e-bf5e-adc180b06a70'::uuid, '26a805ff-eff3-5c01-a6cd-6418ec5ec4bf'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M1_Case_Intake_Note_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L1 M01: CIE-CAP-003_M1_Case_Intake_Note_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M1_Case_Intake_Note_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('a4e74589-46a8-5e05-a0fe-fb8096ad6773'::uuid, 'b04775d0-7f83-5e2e-933b-4b05ec5b3466'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M1_Case_Intake_Note_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L1 M01: CIE-CAP-003_M1_Case_Intake_Note_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M1_Case_Intake_Note_Practice_Artifact.xlsx without replacing its required structure. Required fields: Case ID, Work Object, Reporting Trigger, Confirmed Facts, Missing Information, Role Boundary, Intake Status. Required evidence: E-M1-01, E-M1-02, E-M1-03.", "pass_criteria": "Learner must complete Case ID, Work Object, Reporting Trigger, Confirmed Facts, Missing Information, Role Boundary, Intake Status, cite E-M1-01, E-M1-02, E-M1-03, extract A-314, WBS 03.04, planned finish 2026-07-12, baseline planned 70 percent, actual progress not yet validated, planning owner blank, W27 deadline, choose safe role action, and avoid approval language.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('2438ccd0-4d26-5188-885d-47d0a550fd27'::uuid, '65916881-1269-5903-8e4d-ec8c26f90870'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M2_Evidence_Validation_Checklist_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L1 M02: CIE-CAP-003_M2_Evidence_Validation_Checklist_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M2_Evidence_Validation_Checklist_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('0bb507ed-afc5-58dd-9009-cfb0db0d68b8'::uuid, '1f3982d7-b9f7-5be6-b272-82af9e4eb6ac'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M2_Evidence_Validation_Checklist_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L1 M02: CIE-CAP-003_M2_Evidence_Validation_Checklist_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M2_Evidence_Validation_Checklist_Practice_Artifact.xlsx without replacing its required structure. Required fields: Evidence ID, Evidence Status, Conflict Noted, Missing Evidence, Impact on Next Step, Reviewer Question. Required evidence: E-M2-01, E-M2-02, E-M2-03.", "pass_criteria": "Learner must complete Evidence ID, Evidence Status, Conflict Noted, Missing Evidence, Impact on Next Step, Reviewer Question, cite E-M2-01, E-M2-02, E-M2-03, extract overall dashboard 62 percent, A-314 dashboard 65 percent, baseline planned 70 percent, daily progress actual 48 percent, float -2 days, source link blank, choose safe role action, and avoid approval language.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('78e53bfa-241e-5cd3-9290-a567d04d7d94'::uuid, '7dcebfb1-51ef-5af4-b29e-a1534ce01e50'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M3_Action_or_Handoff_Note_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L1 M03: CIE-CAP-003_M3_Action_or_Handoff_Note_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M3_Action_or_Handoff_Note_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('28ec7f87-d59f-5ca1-ac7a-7a549548b748'::uuid, 'd9861fc9-c8d4-5a8f-99ba-ce2eefe701ec'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M3_Action_or_Handoff_Note_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L1 M03: CIE-CAP-003_M3_Action_or_Handoff_Note_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M3_Action_or_Handoff_Note_Practice_Artifact.xlsx without replacing its required structure. Required fields: Variance Summary, Evidence Basis, Proposed Next Action, Owner Needed, Handoff Condition, Boundary Statement. Required evidence: E-M3-01, E-M3-02, E-M3-03.", "pass_criteria": "Learner must complete Variance Summary, Evidence Basis, Proposed Next Action, Owner Needed, Handoff Condition, Boundary Statement, cite E-M3-01, E-M3-02, E-M3-03, extract access delay 1.5 days, PO-RB-447 received 2026-07-06, float from +3 to -2, RA-17 owner blank, choose safe role action, and avoid approval language.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('dff86faa-ea91-5148-bafe-090c371141ee'::uuid, '3948a9fa-337b-59af-8320-bd80bfbe94c0'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M4_Risk_and_Escalation_Note_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L1 M04: CIE-CAP-003_M4_Risk_and_Escalation_Note_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M4_Risk_and_Escalation_Note_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('e72cdfcb-f7c1-567f-b880-46258eec9b25'::uuid, '47a085cf-de9a-577f-bf20-6aa1a01a3319'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M4_Risk_and_Escalation_Note_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L1 M04: CIE-CAP-003_M4_Risk_and_Escalation_Note_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M4_Risk_and_Escalation_Note_Practice_Artifact.xlsx without replacing its required structure. Required fields: Blocker Type, Risk Signal, Escalation Owner, Due Date, Evidence Attached, Consequence, Status. Required evidence: E-M4-01, E-M4-02, E-M4-03.", "pass_criteria": "Learner must complete Blocker Type, Risk Signal, Escalation Owner, Due Date, Evidence Attached, Consequence, Status, cite E-M4-01, E-M4-02, E-M4-03, extract GRN pending, work permit reopened 2026-07-06 14:00, QA walkthrough pending, do-not-mark-recovered note, choose safe role action, and avoid approval language.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('0caa8218-5eac-5cdb-8515-f92bacaa35d0'::uuid, '598883b4-1b3e-575b-85e9-13a99eceb590'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M5_Quality_and_Closure_Report_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L1 M05: CIE-CAP-003_M5_Quality_and_Closure_Report_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M5_Quality_and_Closure_Report_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('7e2dc799-730a-5553-82fb-69ab6550fff7'::uuid, '51da17b8-0e73-5544-80bc-91c67610b0a2'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M5_Quality_and_Closure_Report_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L1 M05: CIE-CAP-003_M5_Quality_and_Closure_Report_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M5_Quality_and_Closure_Report_Practice_Artifact.xlsx without replacing its required structure. Required fields: Evidence Trail Complete, Open Risks, Communication Draft, Closure Status, Retry Log, Next Owner. Required evidence: E-M5-01, E-M5-02, E-M5-03.", "pass_criteria": "Learner must complete Evidence Trail Complete, Open Risks, Communication Draft, Closure Status, Retry Log, Next Owner, cite E-M5-01, E-M5-02, E-M5-03, extract E-M2-02 missing from draft, RA-17 owner blank, ''client-ready'' wording rejected, Pending Planning Engineer Review, choose safe role action, and avoid approval language.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('34009ca3-64cf-5b3b-8d23-006d68ecba13'::uuid, '69ff45b2-84e8-593e-ad5a-a0225352bbb0'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M6_Final_Portfolio_Pack_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L1 M06: CIE-CAP-003_M6_Final_Portfolio_Pack_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M6_Final_Portfolio_Pack_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('aeafe552-dd6c-50a8-9df4-361993ac5e35'::uuid, '9fd30a91-aed0-528c-8d9e-75f1e70bbb39'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M6_Final_Portfolio_Pack_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L1 M06: CIE-CAP-003_M6_Final_Portfolio_Pack_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M6_Final_Portfolio_Pack_Practice_Artifact.xlsx without replacing its required structure. Required fields: Artifact Chain, Evidence Index, Retry Corrections, Transfer Explanation, Boundary Defense, Reviewer Questions. Required evidence: E-M6-01, E-M6-02, E-M6-03.", "pass_criteria": "Learner must complete Artifact Chain, Evidence Index, Retry Corrections, Transfer Explanation, Boundary Defense, Reviewer Questions, cite E-M6-01, E-M6-02, E-M6-03, extract seven artifacts required, M5 retry screenshot missing, B-209 planned 55 actual 54, baseline approval request outside L1, choose safe role action, and avoid approval language.", "critical_fail": "approval of baseline change, EOT/claim, client-ready release, invented owner, ignored negative float, or AI-generated artifact submission."}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('b5217b05-be0a-5ccf-bac2-faf0de834157'::uuid, 'adf0e3d4-483a-5253-934e-86339285c758'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M0_Course_Readiness_Sheet_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L2 M00: CIE-CAP-003_M0_Course_Readiness_Sheet_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M0_Course_Readiness_Sheet_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('f40e8865-016b-578c-a91c-f9b36acd7ed2'::uuid, '986771b8-b82b-59e8-b850-276d0a901ab3'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M0_Course_Readiness_Sheet_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L2 M00: CIE-CAP-003_M0_Course_Readiness_Sheet_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M0_Course_Readiness_Sheet_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_M0_Course_Readiness_Sheet_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('eedf6678-b6c0-5814-bb9a-6a4042c20ef2'::uuid, 'c804a0b2-684d-5a9f-b6c9-633e4cef9b68'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M1_Case_Intake_Note_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L2 M01: CIE-CAP-003_M1_Case_Intake_Note_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M1_Case_Intake_Note_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('ef0f9c7a-259e-5e2c-80c1-50754b3ca6e1'::uuid, 'd863a120-58d0-5af2-900f-30cc2c576b40'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M1_Case_Intake_Note_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L2 M01: CIE-CAP-003_M1_Case_Intake_Note_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M1_Case_Intake_Note_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_M1_Case_Intake_Note_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('f6e642c7-b285-552f-a266-6a436cdd3fd0'::uuid, '65a0f9f8-5ebb-57e7-9f5d-5f1ebd16d3a7'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M2_Evidence_Validation_Checklist_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L2 M02: CIE-CAP-003_M2_Evidence_Validation_Checklist_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M2_Evidence_Validation_Checklist_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('4e245ebe-d6b6-5699-90ff-5e110f3d2902'::uuid, '49b6f2d3-0858-5185-bd2a-b13a0eaaad52'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M2_Evidence_Validation_Checklist_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L2 M02: CIE-CAP-003_M2_Evidence_Validation_Checklist_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M2_Evidence_Validation_Checklist_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_M2_Evidence_Validation_Checklist_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('86951460-d6d6-56fe-97d9-9abe7ae6249c'::uuid, '1585a2c4-d7eb-5956-99dd-605ae1a6fddd'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M3_Updated_Progress_Tracker_and_Handoff_Note_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L2 M03: CIE-CAP-003_M3_Updated_Progress_Tracker_and_Handoff_Note_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M3_Updated_Progress_Tracker_and_Handoff_Note_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('92d575a4-fe5d-59b7-af45-bc536e88165c'::uuid, '0079f25b-ed1b-5401-96ac-e8813aca4bfd'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M3_Updated_Progress_Tracker_and_Handoff_Note_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L2 M03: CIE-CAP-003_M3_Updated_Progress_Tracker_and_Handoff_Note_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M3_Updated_Progress_Tracker_and_Handoff_Note_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_M3_Updated_Progress_Tracker_and_Handoff_Note_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('7e7a0a5c-fdf7-5b79-babe-e5279dfb38f1'::uuid, '1bf8d637-41df-5ecd-8efe-bf8208c6d317'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M4_Risk_and_Escalation_Note_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L2 M04: CIE-CAP-003_M4_Risk_and_Escalation_Note_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M4_Risk_and_Escalation_Note_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('54144956-146c-570c-bae9-72502fa3951b'::uuid, '652b2a6b-79f5-502f-947b-a59e6cecb3a2'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M4_Risk_and_Escalation_Note_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L2 M04: CIE-CAP-003_M4_Risk_and_Escalation_Note_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M4_Risk_and_Escalation_Note_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_M4_Risk_and_Escalation_Note_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('a6ffe922-cb11-51f0-92e7-3933d5a3089e'::uuid, '84fa6953-675b-572e-91a0-ecb4c70a382b'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M5_Quality_Review_and_Closure_Pack_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L2 M05: CIE-CAP-003_M5_Quality_Review_and_Closure_Pack_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M5_Quality_Review_and_Closure_Pack_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('82c2ccdb-9198-5301-be04-b98557a753b0'::uuid, 'b9ada84f-efa3-5632-975b-b038d5fdd33e'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M5_Quality_Review_and_Closure_Pack_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L2 M05: CIE-CAP-003_M5_Quality_Review_and_Closure_Pack_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M5_Quality_Review_and_Closure_Pack_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_M5_Quality_Review_and_Closure_Pack_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('d1d8ee33-d047-5016-88c2-2e5f77d6f0a7'::uuid, '649c8f42-53da-56be-bc63-c1787a1e634f'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_M6_L2_Progress_Control_Portfolio_Pack_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L2 M06: CIE-CAP-003_M6_L2_Progress_Control_Portfolio_Pack_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_M6_L2_Progress_Control_Portfolio_Pack_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('7a1a456d-3dd5-55d1-8359-b57acfeeb453'::uuid, 'b42ecda3-0a00-5cfb-839d-7fcea0352974'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_M6_L2_Progress_Control_Portfolio_Pack_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L2 M06: CIE-CAP-003_M6_L2_Progress_Control_Portfolio_Pack_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_M6_L2_Progress_Control_Portfolio_Pack_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_M6_L2_Progress_Control_Portfolio_Pack_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported update, omits handoff, wrong workflow route, depends on step-by-step answer"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('ee1348d4-9987-592d-abe2-a7af6d3783f7'::uuid, '846ceeec-d994-589d-8ad7-4e1411b9fdc3'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L3_M0_Orientation_Diagnostic_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L3 M00: CIE-CAP-003_L3_M0_Orientation_Diagnostic_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L3_M0_Orientation_Diagnostic_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('976f61ff-9fa2-540a-aa6a-f308e969c0dc'::uuid, 'c441413a-02ec-5cc7-8665-ebd413bf414d'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L3_M0_Orientation_Diagnostic_Guided_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L3 M00: CIE-CAP-003_L3_M0_Orientation_Diagnostic_Guided_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L3_M0_Orientation_Diagnostic_Guided_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L3_M0_Orientation_Diagnostic_Guided_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('fde4b76e-e40c-5d6a-aadd-2193932c0639'::uuid, 'f2fa55a7-123f-59c4-a239-7f90bd8cefca'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L3_M1_Case_Intake_and_Role_Boundary_Note_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L3 M01: CIE-CAP-003_L3_M1_Case_Intake_and_Role_Boundary_Note_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L3_M1_Case_Intake_and_Role_Boundary_Note_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('237adb87-6cad-5c4b-b8b1-0f5d32557c92'::uuid, '730c1a6c-fec9-596c-94ae-ff3beb1638bf'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L3_M1_Case_Intake_and_Role_Boundary_Note_Guided_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L3 M01: CIE-CAP-003_L3_M1_Case_Intake_and_Role_Boundary_Note_Guided_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L3_M1_Case_Intake_and_Role_Boundary_Note_Guided_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L3_M1_Case_Intake_and_Role_Boundary_Note_Guided_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('383a8790-7185-5be5-a001-ee545d8ab8a6'::uuid, '86734bb2-5bc2-543f-bc93-dae488ce6437'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L3_M2_Evidence_Validation_Findings_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L3 M02: CIE-CAP-003_L3_M2_Evidence_Validation_Findings_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L3_M2_Evidence_Validation_Findings_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('6e1c2547-f665-5e54-8220-24a4367df6b0'::uuid, 'f272b79a-664d-5620-bc5c-09c4d98568ba'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L3_M2_Evidence_Validation_Findings_Guided_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L3 M02: CIE-CAP-003_L3_M2_Evidence_Validation_Findings_Guided_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L3_M2_Evidence_Validation_Findings_Guided_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L3_M2_Evidence_Validation_Findings_Guided_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('e06322d9-babc-5519-bd1a-e87b676c1023'::uuid, 'a8929c51-dfba-5639-a3a6-9bc887d8de4d'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L3_M3_Draft_Progress_Variance_and_Recovery_Support_Recommendation_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L3 M03: CIE-CAP-003_L3_M3_Draft_Progress_Variance_and_Recovery_Support_Recommendation_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L3_M3_Draft_Progress_Variance_and_Recovery_Support_Recommendation_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('4b48ccb5-ed42-52d2-a22a-0418971246a3'::uuid, '20652321-763a-5795-bdc0-d6455aa8edea'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L3_M3_Draft_Progress_Variance_and_Recovery_Support_Recommendation_Guided_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L3 M03: CIE-CAP-003_L3_M3_Draft_Progress_Variance_and_Recovery_Support_Recommendation_Guided_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L3_M3_Draft_Progress_Variance_and_Recovery_Support_Recommendation_Guided_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L3_M3_Draft_Progress_Variance_and_Recovery_Support_Recommendation_Guided_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('c6ab9394-ccb9-548f-b10e-433aeec0bd9b'::uuid, 'd53daf74-4ef3-5baf-94ed-b7c46ee81128'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L3_M4_Exception_and_Escalation_Rationale_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L3 M04: CIE-CAP-003_L3_M4_Exception_and_Escalation_Rationale_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L3_M4_Exception_and_Escalation_Rationale_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('e4ec7be7-a336-52e2-93c1-c1ea9380f86d'::uuid, '1d405550-1688-5fc1-971c-0860fe70d962'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L3_M4_Exception_and_Escalation_Rationale_Guided_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L3 M04: CIE-CAP-003_L3_M4_Exception_and_Escalation_Rationale_Guided_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L3_M4_Exception_and_Escalation_Rationale_Guided_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L3_M4_Exception_and_Escalation_Rationale_Guided_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('85e05e18-cce7-5400-baf0-938deb3f0345'::uuid, '50e37365-15cf-5a6e-8dc0-b00e8038db17'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L3_M5_Quality-Checked_Progress_Variance_and_Recovery_Support_Pack_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L3 M05: CIE-CAP-003_L3_M5_Quality-Checked_Progress_Variance_and_Recovery_Support_Pack_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L3_M5_Quality-Checked_Progress_Variance_and_Recovery_Support_Pack_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('d490751b-2d17-5f51-a8c0-af6075b699a1'::uuid, '3542ea3d-4927-58ef-a2a9-6915df569bf4'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L3_M5_Quality-Checked_Progress_Variance_and_Recovery_Support_Pack_Guided_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L3 M05: CIE-CAP-003_L3_M5_Quality-Checked_Progress_Variance_and_Recovery_Support_Pack_Guided_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L3_M5_Quality-Checked_Progress_Variance_and_Recovery_Support_Pack_Guided_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L3_M5_Quality-Checked_Progress_Variance_and_Recovery_Support_Pack_Guided_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('6d97d322-7375-56a7-a7e0-925bec59b34a'::uuid, '28f4833f-3bd2-5c69-803d-c075e4756988'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L3_M6_Portfolio-Ready_Progress_Variance_and_Recovery_Support_Pack_Evolve_Stage_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L3 M06: CIE-CAP-003_L3_M6_Portfolio-Ready_Progress_Variance_and_Recovery_Support_Pack_Evolve_Stage_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L3_M6_Portfolio-Ready_Progress_Variance_and_Recovery_Support_Pack_Evolve_Stage_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('c1fc16e4-2dee-50d4-9f3e-57c9417d2133'::uuid, '8e493839-18f6-56b0-9051-d9e2bd05290c'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L3_M6_Portfolio-Ready_Progress_Variance_and_Recovery_Support_Pack_Guided_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L3 M06: CIE-CAP-003_L3_M6_Portfolio-Ready_Progress_Variance_and_Recovery_Support_Pack_Guided_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L3_M6_Portfolio-Ready_Progress_Variance_and_Recovery_Support_Pack_Guided_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L3_M6_Portfolio-Ready_Progress_Variance_and_Recovery_Support_Pack_Guided_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Unsupported causal judgement, recommendation not traceable, uncertainty/consequence omitted"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('612317f2-6959-5c6b-9685-8d75493a0058'::uuid, 'fbe1cf99-3818-524b-8c62-ab29dbe5ac43'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L4_M0_Integrated_Recovery_Readiness_Map_Evolve_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L4 M00: CIE-CAP-003_L4_M0_Integrated_Recovery_Readiness_Map_Evolve_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L4_M0_Integrated_Recovery_Readiness_Map_Evolve_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('3ab86e86-80df-58a2-90bf-fbcd6a079cc3'::uuid, '42bf2a76-fbe7-5c83-9222-f68bc8e11432'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L4_M0_Integrated_Recovery_Readiness_Map_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L4 M00: CIE-CAP-003_L4_M0_Integrated_Recovery_Readiness_Map_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L4_M0_Integrated_Recovery_Readiness_Map_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L4_M0_Integrated_Recovery_Readiness_Map_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('cbcba1b4-0aa1-584c-8ec1-f7187125a18e'::uuid, '1936e8b5-56ef-5e7e-be9f-7676f33ebc60'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L4_M1_Case_Intake_and_Boundary_Note_v2_Evolve_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L4 M01: CIE-CAP-003_L4_M1_Case_Intake_and_Boundary_Note_v2_Evolve_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L4_M1_Case_Intake_and_Boundary_Note_v2_Evolve_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('7e41662b-5ff0-59bf-9b3b-b2c5f19b987c'::uuid, '4b75527b-ef39-53e2-8f80-9307dfadee3a'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L4_M1_Case_Intake_and_Boundary_Note_v2_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L4 M01: CIE-CAP-003_L4_M1_Case_Intake_and_Boundary_Note_v2_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L4_M1_Case_Intake_and_Boundary_Note_v2_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L4_M1_Case_Intake_and_Boundary_Note_v2_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('1366dbc5-4160-5de5-aada-0de04f801013'::uuid, 'ff0f937b-a41d-5b71-8985-c1ff99a7f039'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L4_M2_Integrated_Evidence_Validation_Matrix_v2_Evolve_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L4 M02: CIE-CAP-003_L4_M2_Integrated_Evidence_Validation_Matrix_v2_Evolve_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L4_M2_Integrated_Evidence_Validation_Matrix_v2_Evolve_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('9dbca31b-b86d-5652-99df-5ba7de7476f6'::uuid, 'bf44ee44-2b06-5783-9a75-8d3f5cc1c454'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L4_M2_Integrated_Evidence_Validation_Matrix_v2_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L4 M02: CIE-CAP-003_L4_M2_Integrated_Evidence_Validation_Matrix_v2_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L4_M2_Integrated_Evidence_Validation_Matrix_v2_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L4_M2_Integrated_Evidence_Validation_Matrix_v2_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('3cc960e8-c8ae-5bb8-8676-e3a3cb52f5d6'::uuid, '281f8c88-068a-5a27-8c07-2a1053130906'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L4_M3_Integrated_Recovery_Action_Handoff_Pack_v2_Evolve_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L4 M03: CIE-CAP-003_L4_M3_Integrated_Recovery_Action_Handoff_Pack_v2_Evolve_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L4_M3_Integrated_Recovery_Action_Handoff_Pack_v2_Evolve_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('e9ca0b87-6172-56df-bf44-de46de566a3d'::uuid, '4b759561-72e9-5a00-8403-8467666fc69b'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L4_M3_Integrated_Recovery_Action_Handoff_Pack_v2_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L4 M03: CIE-CAP-003_L4_M3_Integrated_Recovery_Action_Handoff_Pack_v2_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L4_M3_Integrated_Recovery_Action_Handoff_Pack_v2_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L4_M3_Integrated_Recovery_Action_Handoff_Pack_v2_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('3d56b9cf-bb83-5e96-8a32-c589666be17f'::uuid, '32354df5-882e-5ba2-a829-995b4dfe4535'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L4_M4_Exception_Control_Note_v2_Evolve_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L4 M04: CIE-CAP-003_L4_M4_Exception_Control_Note_v2_Evolve_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L4_M4_Exception_Control_Note_v2_Evolve_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('c056a79f-01c1-5990-a325-5315a818072d'::uuid, '82d4990f-71a0-5e43-9d5f-36ee86d16d1e'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L4_M4_Exception_Control_Note_v2_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L4 M04: CIE-CAP-003_L4_M4_Exception_Control_Note_v2_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L4_M4_Exception_Control_Note_v2_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L4_M4_Exception_Control_Note_v2_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('bfdf989d-2fb3-56a0-a936-206d060b952d'::uuid, '552bade1-8d08-518c-bb7e-96e30b473de4'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L4_M5_Integrated_Quality_Review_and_Closure_Pack_v2_Evolve_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L4 M05: CIE-CAP-003_L4_M5_Integrated_Quality_Review_and_Closure_Pack_v2_Evolve_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L4_M5_Integrated_Quality_Review_and_Closure_Pack_v2_Evolve_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('cf3bd531-30be-5b4c-a9ff-bc6d0c710f7c'::uuid, '1aa524d6-33e9-5656-b98f-2e9d24d32d6d'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L4_M5_Integrated_Quality_Review_and_Closure_Pack_v2_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L4 M05: CIE-CAP-003_L4_M5_Integrated_Quality_Review_and_Closure_Pack_v2_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L4_M5_Integrated_Quality_Review_and_Closure_Pack_v2_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L4_M5_Integrated_Quality_Review_and_Closure_Pack_v2_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('9ac9bf55-6d70-504d-bd6d-98375ed33fc6'::uuid, 'c76edb32-661a-598a-b299-d606a6e70d73'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L4_M6_Integrated_Progress_Variance_and_Recovery_Support_Portfolio_Evolve_Artifact.xlsx', 'Complete the exact Express final artifact workbook supplied for L4 M06: CIE-CAP-003_L4_M6_Integrated_Progress_Variance_and_Recovery_Support_Portfolio_Evolve_Artifact.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L4_M6_Integrated_Progress_Variance_and_Recovery_Support_Portfolio_Evolve_Artifact.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('7df1da98-2665-531a-9b5f-25f0a5346de7'::uuid, 'aa09df23-344c-5014-92f0-8f07e3eb2abb'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L4_M6_Integrated_Progress_Variance_and_Recovery_Support_Portfolio_Practice_Artifact.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L4 M06: CIE-CAP-003_L4_M6_Integrated_Progress_Variance_and_Recovery_Support_Portfolio_Practice_Artifact.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L4_M6_Integrated_Progress_Variance_and_Recovery_Support_Portfolio_Practice_Artifact.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L4_M6_Integrated_Progress_Variance_and_Recovery_Support_Portfolio_Practice_Artifact.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Optimises one function only, unresolved trade-off, no integrated ownership/review path"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('1ec4284e-9388-5cc9-91f4-17b0cb839f5e'::uuid, '036b5dd9-a9ff-5773-b196-0ce7eac5e495'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L5_M0_Enterprise_Progress_Governance_Problem_and_Mandate_Charter_Try_It_Yourself.xlsx', 'Complete the exact Express final artifact workbook supplied for L5 M00: CIE-CAP-003_L5_M0_Enterprise_Progress_Governance_Problem_and_Mandate_Charter_Try_It_Yourself.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L5_M0_Enterprise_Progress_Governance_Problem_and_Mandate_Charter_Try_It_Yourself.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('1426e2a6-5f55-5575-a8b2-20c770773cfc'::uuid, '95d34529-5967-5e8c-bfe4-b82872c2752d'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L5_M0_Enterprise_Progress_Governance_Problem_and_Mandate_Charter_Guided_Practice.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L5 M00: CIE-CAP-003_L5_M0_Enterprise_Progress_Governance_Problem_and_Mandate_Charter_Guided_Practice.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L5_M0_Enterprise_Progress_Governance_Problem_and_Mandate_Charter_Guided_Practice.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L5_M0_Enterprise_Progress_Governance_Problem_and_Mandate_Charter_Guided_Practice.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('6fe5d9d3-6c61-5a4a-8c15-949f8e9687aa'::uuid, '91f71277-5522-51ff-9f0b-6cd5b128fb0c'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L5_M1_Enterprise_Governance_Intake_and_Decision_Rights_Record_Try_It_Yourself.xlsx', 'Complete the exact Express final artifact workbook supplied for L5 M01: CIE-CAP-003_L5_M1_Enterprise_Governance_Intake_and_Decision_Rights_Record_Try_It_Yourself.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L5_M1_Enterprise_Governance_Intake_and_Decision_Rights_Record_Try_It_Yourself.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('eec47a04-aaad-5b81-9a17-9029c8fe6ff3'::uuid, '0caa9f54-e8a0-56ef-acad-be2f35c0fa79'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L5_M1_Enterprise_Governance_Intake_and_Decision_Rights_Record_Guided_Practice.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L5 M01: CIE-CAP-003_L5_M1_Enterprise_Governance_Intake_and_Decision_Rights_Record_Guided_Practice.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L5_M1_Enterprise_Governance_Intake_and_Decision_Rights_Record_Guided_Practice.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L5_M1_Enterprise_Governance_Intake_and_Decision_Rights_Record_Guided_Practice.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('64106978-a1b3-507a-a074-d013296f610d'::uuid, '1d8aba50-df33-52f1-bae6-4fcba4ef73c2'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L5_M2_Enterprise_Progress_Evidence_Standard_and_Assurance_Matrix_Try_It_Yourself.xlsx', 'Complete the exact Express final artifact workbook supplied for L5 M02: CIE-CAP-003_L5_M2_Enterprise_Progress_Evidence_Standard_and_Assurance_Matrix_Try_It_Yourself.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L5_M2_Enterprise_Progress_Evidence_Standard_and_Assurance_Matrix_Try_It_Yourself.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('03ba3e6b-d830-5b2c-888e-b63b2d5c6079'::uuid, 'e1158b91-9bb0-545a-8edb-c1970067c735'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L5_M2_Enterprise_Progress_Evidence_Standard_and_Assurance_Matrix_Guided_Practice.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L5 M02: CIE-CAP-003_L5_M2_Enterprise_Progress_Evidence_Standard_and_Assurance_Matrix_Guided_Practice.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L5_M2_Enterprise_Progress_Evidence_Standard_and_Assurance_Matrix_Guided_Practice.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L5_M2_Enterprise_Progress_Evidence_Standard_and_Assurance_Matrix_Guided_Practice.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('81ea6250-2e85-5110-8f3b-d2bf83467cb7'::uuid, 'bfbe5856-12ed-5d20-b5c7-0c69551c67e2'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L5_M3_Governance_Direction_and_Transformation_Options_Paper_Try_It_Yourself.xlsx', 'Complete the exact Express final artifact workbook supplied for L5 M03: CIE-CAP-003_L5_M3_Governance_Direction_and_Transformation_Options_Paper_Try_It_Yourself.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L5_M3_Governance_Direction_and_Transformation_Options_Paper_Try_It_Yourself.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('4a17934b-437f-5970-bc6e-b167e4182efe'::uuid, '6bcc4e21-9e99-58ba-8407-a0f413045a41'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L5_M3_Governance_Direction_and_Transformation_Options_Paper_Guided_Practice.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L5 M03: CIE-CAP-003_L5_M3_Governance_Direction_and_Transformation_Options_Paper_Guided_Practice.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L5_M3_Governance_Direction_and_Transformation_Options_Paper_Guided_Practice.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L5_M3_Governance_Direction_and_Transformation_Options_Paper_Guided_Practice.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('cfcc4f60-e100-5cf4-ab34-e802968bc2ae'::uuid, 'c1b90f66-87ad-5171-8e88-ee1a4b2302d5'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L5_M4_Enterprise_Risk_Appetite_Exception_and_Escalation_Framework_Try_It_Yourself.xlsx', 'Complete the exact Express final artifact workbook supplied for L5 M04: CIE-CAP-003_L5_M4_Enterprise_Risk_Appetite_Exception_and_Escalation_Framework_Try_It_Yourself.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L5_M4_Enterprise_Risk_Appetite_Exception_and_Escalation_Framework_Try_It_Yourself.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('d176952c-2070-5b28-bd2f-ef8fcd956d0e'::uuid, '419e3a24-1763-5afd-99bb-961023b75376'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L5_M4_Enterprise_Risk_Appetite_Exception_and_Escalation_Framework_Guided_Practice.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L5 M04: CIE-CAP-003_L5_M4_Enterprise_Risk_Appetite_Exception_and_Escalation_Framework_Guided_Practice.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L5_M4_Enterprise_Risk_Appetite_Exception_and_Escalation_Framework_Guided_Practice.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L5_M4_Enterprise_Risk_Appetite_Exception_and_Escalation_Framework_Guided_Practice.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('f8a390b0-9cc2-586f-94e1-08ff298fe4d9'::uuid, 'bf1f5e79-140a-59a0-bb76-2bd3e6c727cb'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L5_M5_Enterprise_Assurance_Disclosure_and_Closure_Protocol_Try_It_Yourself.xlsx', 'Complete the exact Express final artifact workbook supplied for L5 M05: CIE-CAP-003_L5_M5_Enterprise_Assurance_Disclosure_and_Closure_Protocol_Try_It_Yourself.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L5_M5_Enterprise_Assurance_Disclosure_and_Closure_Protocol_Try_It_Yourself.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('407dfa03-bebe-5ea4-8a5a-7af16dd1518c'::uuid, '5fee6056-8f47-5e01-808d-b934030bda8a'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L5_M5_Enterprise_Assurance_Disclosure_and_Closure_Protocol_Guided_Practice.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L5 M05: CIE-CAP-003_L5_M5_Enterprise_Assurance_Disclosure_and_Closure_Protocol_Guided_Practice.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L5_M5_Enterprise_Assurance_Disclosure_and_Closure_Protocol_Guided_Practice.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L5_M5_Enterprise_Assurance_Disclosure_and_Closure_Protocol_Guided_Practice.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('99aaa742-e557-5197-8841-a6921660e8dc'::uuid, '49adf02b-6b57-5a0c-9bb1-1869b346b790'::uuid, 1, 'Complete the final artifact: CIE-CAP-003_L5_M6_Enterprise_Progress_Governance_Transformation_Framework_Try_It_Yourself.xlsx', 'Complete the exact Express final artifact workbook supplied for L5 M06: CIE-CAP-003_L5_M6_Enterprise_Progress_Governance_Transformation_Framework_Try_It_Yourself.xlsx.', '{"required_fields": "Complete the exact Express final workbook CIE-CAP-003_L5_M6_Enterprise_Progress_Governance_Transformation_Framework_Try_It_Yourself.xlsx without replacing its required structure. Apply the module method independently and submit the final artifact.", "pass_criteria": "Complete the supplied Evolve workbook accurately, keep evidence traceable, preserve unresolved items, demonstrate independent transfer, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('d6ee8dce-7920-5fa9-9771-30de1555ebc6'::uuid, '4338cced-fd9e-562f-8b21-7c7564a720ac'::uuid, 1, 'Complete the practice artifact: CIE-CAP-003_L5_M6_Enterprise_Progress_Governance_Transformation_Framework_Guided_Practice.xlsx', 'Complete the exact Evolve practice artifact workbook supplied for L5 M06: CIE-CAP-003_L5_M6_Enterprise_Progress_Governance_Transformation_Framework_Guided_Practice.xlsx.', '{"required_fields": "Complete the exact Evolve practice workbook CIE-CAP-003_L5_M6_Enterprise_Progress_Governance_Transformation_Framework_Guided_Practice.xlsx without replacing its required structure. Complete the exact Express or guided-practice workbook CIE-CAP-003_L5_M6_Enterprise_Progress_Governance_Transformation_Framework_Guided_Practice.xlsx without replacing its required structure.", "pass_criteria": "Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated level authority boundary.", "critical_fail": "Direction without assurance, ignores strategic/reputational risk, ungoverned standard or transformation"}'::jsonb, 'file', ARRAY['xlsx']::text[], 10, TRUE, TRUE)
ON CONFLICT DO NOTHING;

COMMIT;
