-- Generated from LTE_LEARNING_CATALOG_CIE_CAP_003_LINKS_COMPLETE.xlsx: public.levels.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.levels
INSERT INTO public."levels" ("id", "level_code", "capability_id", "level_id", "title", "description", "observable_behavior", "example_outputs", "problem_statement", "duration_minutes", "difficulty_level", "status", "version_no", "is_active", "total_xp")
VALUES ('029f3de1-70b8-5b3f-9203-6f5cee8be5f5'::uuid, 'CIE_CAP003_L1', (SELECT "id" FROM public."capabilities" WHERE "code" = 'CIE-CAP-003'), (SELECT "id" FROM public."level_scale" WHERE "level_no" = 1), 'Project Progress, Schedule and Recovery Control - L1 Assisted recognition', 'Build guided capability to recognise project-controls evidence, identify progress and schedule inconsistencies, preserve role boundaries, and prepare an evidence-backed handoff for planning-engineer review.', '["With guidance, identifies planned/actual progress, schedule, delay, recovery and ownership evidence", "identifies inconsistencies and missing evidence", "prepares a safe handoff without approving baseline changes, EOT, claims or final release."]'::jsonb, '["Course Readiness Sheet", "Case Intake Note", "Evidence Validation Checklist", "Action or Handoff Note", "Risk and Escalation Note", "Quality and Closure Report", "Final Portfolio Pack"]'::jsonb, '{"title": "Project Progress, Schedule and Recovery Control — L1", "description": "HN-24A contains conflicting baseline, dashboard and daily-progress evidence, late procurement, blocked access, negative float and a missing recovery owner, the learner must recognise what is supported, what is not ready, and what must be handed off without crossing L1 authority."}'::jsonb, 420, 'beginner'::public.difficulty_level, 'published'::public.status, 1, TRUE, DEFAULT)
ON CONFLICT DO NOTHING;
INSERT INTO public."levels" ("id", "level_code", "capability_id", "level_id", "title", "description", "observable_behavior", "example_outputs", "problem_statement", "duration_minutes", "difficulty_level", "status", "version_no", "is_active", "total_xp")
VALUES ('8bfef3e8-d301-5436-8857-7cc9c36456ef'::uuid, 'CIE_CAP003_L2', (SELECT "id" FROM public."capabilities" WHERE "code" = 'CIE-CAP-003'), (SELECT "id" FROM public."level_scale" WHERE "level_no" = 2), 'Project Progress, Schedule and Recovery Control — L2', 'Build independent operational capability to validate routine project-progress evidence, update controlled progress fields, route routine exceptions and complete a traceable handoff using established criteria.', '["Independently validates routine progress-control evidence", "updates controlled fields using established criteria", "routes routine exceptions", "completes a traceable operational handoff."]'::jsonb, '["Course Readiness Sheet", "Case Intake Note", "Evidence Validation Checklist", "Updated Progress Tracker and Handoff Note", "Risk and Escalation Note", "Quality Review and Closure Pack", "L2 Progress Control Portfolio Pack"]'::jsonb, '{"title": "Project Progress, Schedule and Recovery Control — L2", "description": "A junior engineer independently completes a routine single-activity progress-control workflow using schedule, DPR, photo, measurement/inspection and tracker evidence."}'::jsonb, 450, 'foundation'::public.difficulty_level, 'published'::public.status, 1, TRUE, DEFAULT)
ON CONFLICT DO NOTHING;
INSERT INTO public."levels" ("id", "level_code", "capability_id", "level_id", "title", "description", "observable_behavior", "example_outputs", "problem_statement", "duration_minutes", "difficulty_level", "status", "version_no", "is_active", "total_xp")
VALUES ('97137f7e-f69e-5403-9103-de6dbbabf803'::uuid, 'CIE_CAP003_L3', (SELECT "id" FROM public."capabilities" WHERE "code" = 'CIE-CAP-003'), (SELECT "id" FROM public."level_scale" WHERE "level_no" = 3), 'Project Progress, Schedule and Recovery Control — L3', 'Build capability to analyse incomplete or conflicting linked evidence, evaluate consequences and produce a traceable progress-variance and recovery-support recommendation for authorised decision.', '["Analyses incomplete or conflicting linked evidence", "evaluates project and stakeholder consequences", "judges alternatives", "produces and defends an evidence-backed recommendation."]'::jsonb, '["Orientation Diagnostic", "Case Intake and Role Boundary Note", "Evidence Validation Findings", "Draft Progress Variance and Recovery Support Recommendation", "Exception and Escalation Rationale", "Quality-Checked Progress Variance and Recovery Support Pack", "Portfolio-Ready Progress Variance and Recovery Support Pack"]'::jsonb, '{"title": "Project Progress, Schedule and Recovery Control — L3", "description": "A project-controls analyst reconciles incomplete or conflicting linked evidence and produces a justified recommendation for authorised decision."}'::jsonb, 510, 'intermediate'::public.difficulty_level, 'published'::public.status, 1, TRUE, DEFAULT)
ON CONFLICT DO NOTHING;
INSERT INTO public."levels" ("id", "level_code", "capability_id", "level_id", "title", "description", "observable_behavior", "example_outputs", "problem_statement", "duration_minutes", "difficulty_level", "status", "version_no", "is_active", "total_xp")
VALUES ('d40290f1-2a2c-5fe1-822f-cfe353d9f3d4'::uuid, 'CIE_CAP003_L4', (SELECT "id" FROM public."capabilities" WHERE "code" = 'CIE-CAP-003'), (SELECT "id" FROM public."level_scale" WHERE "level_no" = 4), 'Project Progress, Schedule and Recovery Control — L4', 'Build capability to integrate planning, site, QA, resources, commercial and client-review evidence, evaluate competing recovery trade-offs and lead an integrated recovery-control path.', '["Integrates planning, site, QA, resource, commercial and client evidence", "evaluates competing recovery trade-offs", "coordinates ownership and interfaces", "leads an integrated recovery-control outcome."]'::jsonb, '["Integrated Recovery Readiness Map", "Case Intake and Boundary Note v2", "Integrated Evidence Validation Matrix v2", "Integrated Recovery Action Handoff Pack v2", "Exception Control Note v2", "Integrated Quality Review and Closure Pack v2", "Integrated Progress Variance and Recovery Support Portfolio"]'::jsonb, '{"title": "Project Progress, Schedule and Recovery Control — L4", "description": "An integrated project-controls lead reconciles competing cross-functional signals and optimises an integrated recovery-control path."}'::jsonb, 585, 'advanced'::public.difficulty_level, 'published'::public.status, 1, TRUE, DEFAULT)
ON CONFLICT DO NOTHING;
INSERT INTO public."levels" ("id", "level_code", "capability_id", "level_id", "title", "description", "observable_behavior", "example_outputs", "problem_statement", "duration_minutes", "difficulty_level", "status", "version_no", "is_active", "total_xp")
VALUES ('0c615ad6-2d07-5f7d-9766-928144f8f194'::uuid, 'CIE_CAP003_L5', (SELECT "id" FROM public."capabilities" WHERE "code" = 'CIE-CAP-003'), (SELECT "id" FROM public."level_scale" WHERE "level_no" = 5), 'Project Progress, Schedule and Recovery Control — L5', 'Build capability to define enterprise progress-governance principles, decision rights, evidence standards, assurance, risk appetite, exception mechanisms and transformation direction across projects.', '["Defines enterprise evidence standards and decision rights", "sets risk appetite, exception and assurance mechanisms", "establishes governance forums and disclosure rules", "directs progress-control transformation across projects."]'::jsonb, '["Enterprise Progress Governance Problem and Mandate Charter", "Enterprise Governance Intake and Decision Rights Record", "Enterprise Progress Evidence Standard and Assurance Matrix", "Governance Direction and Transformation Options Paper", "Enterprise Risk Appetite, Exception and Escalation Framework", "Enterprise Assurance, Disclosure and Closure Protocol", "Enterprise Progress Governance Transformation Framework"]'::jsonb, '{"title": "Project Progress, Schedule and Recovery Control — L5", "description": "An enterprise governance lead addresses portfolio-wide inconsistency in progress evidence, decision rights, exception handling and assurance by defining standards and transformation direction."}'::jsonb, 630, 'expert'::public.difficulty_level, 'published'::public.status, 1, TRUE, DEFAULT)
ON CONFLICT DO NOTHING;

COMMIT;
