-- Generated from LTE_LEARNING_CATALOG_TEMPLATE.xlsx: public.modules.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.modules
INSERT INTO public."modules" ("id", "course_id", "module_no", "title", "description", "pressure_points", "user_confusion", "industry_challenge", "prerequisites", "what_youll_learn", "when_to_apply", "learning_content", "support", "knowledge", "module_problem_statement", "tools", "is_published", "is_active")
VALUES ('2e018b03-2663-5f67-8e6f-d1327b2894e2'::uuid, '0a010796-10c0-5287-b89a-6ab56bd71399'::uuid, 0, 'Industry, Role & Course Readiness', 'Learner connects front-office arrival readiness to guest trust, room flow, payment/readiness safety, team workload, and L1 role boundaries before working the case.', NULL, NULL, NULL, NULL, NULL, NULL, '["Learn why arrival-readiness checks protect service quality and access safety.", "Compare safe vs unsafe beginner assumptions in a front-office moment.", "Fill Course Readiness Sheet using evidence labels and role-boundary prompts.", "Submit readiness sheet with risk, evidence source, boundary, and validation question."]'::jsonb, '["List the five arrival-readiness evidence sources and mark one open validation question before entering Module 1.", "Write one evidence-before-action sentence for the Course Readiness Sheet.", "Classify three actions as allowed / not allowed / escalation required.", "Ask boundary-check questions, simplify SOP language, and help the learner compare safe vs unsafe first moves after the learner writes one human observation and one open validation question.", "Mission card + front-office readiness signal map", "Evidence-first decision ladder visual", "Allowed vs not-allowed action board", "Behaviour cue card + pressure reflection prompt", "Safe wording bank for first guest response", "Guest trust and operations impact mini-map"]'::jsonb, '["Front-Office Arrival Readiness", "Evidence-Before-Action Principle", "L1 Role Boundary in Guest/Visitor Readiness", "Professional Readiness Mindset", "Pause Before Promise", "Service Value Awareness"]'::jsonb, 'At 3:30 PM, a tired guest is waiting near the front desk while the queue grows. The learner sees a reservation for Rohan Mehta, an early-arrival note, payment/readiness uncertainty, and a room that is not yet fully inspection-cleared. Before touching any check-in or access step, the learner must identify the course mission, L1 role boundary, tools, risks, and one open validation question.', 'null'::jsonb, FALSE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules" ("id", "course_id", "module_no", "title", "description", "pressure_points", "user_confusion", "industry_challenge", "prerequisites", "what_youll_learn", "when_to_apply", "learning_content", "support", "knowledge", "module_problem_statement", "tools", "is_published", "is_active")
VALUES ('df2d80be-e296-5bda-901e-0869b8f2491e'::uuid, '0a010796-10c0-5287-b89a-6ab56bd71399'::uuid, 1, 'Case Intake & Role Boundary', 'Learner opens the arrival case, separates facts from assumptions, identifies available/missing records, and protects L1 authority while preparing intake.', NULL, NULL, NULL, NULL, NULL, NULL, '["Learn intake discipline and role-boundary language.", "Sort evidence cards into fact, assumption, missing, and question categories.", "Draft Case Intake Note for the Rohan Mehta case.", "Submit intake note with evidence references and safe clarification questions."]'::jsonb, '["Mark each item as confirmed, claim, missing, or risk in the Case Intake Note.", "Arrange the intake fields in evidence-first order.", "Extract five required fields from the mock PMS/front-office screen.", "Compare fact/assumption examples, suggest clearer wording after learner drafts the note, and challenge unsupported statements.", "Field-highlighted case file UI + intake grid", "Sequenced intake checklist", "Mock PMS screen with field highlights", "Listening cue card + claim vs confirmed tag", "Fact vs assumption sorting cards", "Safe greeting role-play prompt"]'::jsonb, '["Arrival Evidence Mapping", "Case Intake Sequencing", "PMS / Front-Office Field Recognition", "Active Listening for Arrival Evidence", "Assumption Control", "Calm Guest Greeting Under Pressure"]'::jsonb, 'The learner receives the first case file. Reservation card shows guest name Rohan Mehta, OTA source, today arrival, early arrival requested. Masked ID evidence shows Rohan M. The guest says payment is complete. PMS note says payment hold pending. Room board says Room 412 clean - not inspected. Learner must separate facts, assumptions, missing information, and role boundary.', 'null'::jsonb, FALSE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules" ("id", "course_id", "module_no", "title", "description", "pressure_points", "user_confusion", "industry_challenge", "prerequisites", "what_youll_learn", "when_to_apply", "learning_content", "support", "knowledge", "module_problem_statement", "tools", "is_published", "is_active")
VALUES ('6549115e-08da-53bb-a2d8-4c1f40cda084'::uuid, '0a010796-10c0-5287-b89a-6ab56bd71399'::uuid, 2, 'Evidence / Requirement Validation', 'Learner validates whether reservation, identity, room-status, and payment/readiness evidence is complete, matching, missing, blocked, or requires supervisor review.', NULL, NULL, NULL, NULL, NULL, NULL, '["Learn evidence status categories and readiness blockers.", "Compare examples of match, minor variation, mismatch, missing, and hold.", "Complete checklist using Rohan case evidence.", "Submit checklist with evidence reasons and supervisor-review trigger."]'::jsonb, '["Label the reservation record as usable, incomplete, blocked, or needs review with reason.", "Classify the ID variation and write the safe next step.", "Rewrite one ID note in privacy-safe form.", "Review learner classification logic, ask for evidence source, and flag unsupported \"ready\" decisions after first checklist attempt.", "Reservation card with validation labels", "Match/minor variation/mismatch ladder", "Privacy-safe ID mockup", "Room-status board + payment-hold card", "Polite clarification wording bank", "Pause-vs-proceed decision card"]'::jsonb, '["Reservation Status Validation", "ID Matching and Mismatch Classification", "Privacy-Safe Guest Record Handling", "Room-Status and Payment Hold Validation", "Polite Clarification", "Confidence to Pause"]'::jsonb, 'The learner must validate whether the case evidence is complete and usable. Reservation name Rohan Mehta and ID name Rohan M. may be a minor variation, but payment hold pending and Room 412 clean-not-inspected are blockers. Learner must mark each signal as match, minor variation, mismatch, missing, or hold/blocker.', 'null'::jsonb, FALSE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules" ("id", "course_id", "module_no", "title", "description", "pressure_points", "user_confusion", "industry_challenge", "prerequisites", "what_youll_learn", "when_to_apply", "learning_content", "support", "knowledge", "module_problem_statement", "tools", "is_published", "is_active")
VALUES ('b6606c1e-a0fd-505f-ba6c-d96e07150bba'::uuid, '0a010796-10c0-5287-b89a-6ab56bd71399'::uuid, 3, 'Guided Work Action or Handoff', 'Learner turns validated evidence into a role-safe recommendation or handoff without approving check-in or releasing access.', NULL, NULL, NULL, NULL, NULL, NULL, '["Learn role-safe handoff structure.", "Compare weak and strong handoff examples.", "Draft handoff note using validated evidence.", "Submit note with owner, blocker, evidence, recommendation, and boundary."]'::jsonb, '["Draft a handoff note with five required fields.", "Rewrite one unsafe approval phrase into L1-safe recommendation language.", "Select the likely owner path and note “SME validation required” where SOP owner is unknown.", "Ask whether note includes guest, evidence, blocker, owner, action not allowed, and safe next step; suggest clarity improvements only after draft.", "Weak vs strong handoff comparison", "Approval vs recommendation language board", "Owner-routing mini-map", "Controlled-access warning card", "Traceable handoff record template", "Accountability cue card"]'::jsonb, '["Role-Safe Handoff Note Design", "Recommendation vs Approval Language", "Owner Routing for Arrival Handoff", "Key/Access Handoff Boundary", "Traceable Service Handoff Record", "Accountability in Documentation"]'::jsonb, 'The learner has a completed validation checklist and must prepare a role-safe handoff note. The note must recommend supervisor review, show evidence, identify blockers, name owner, and state action not allowed for L1. Learner must not approve check-in or release key/access.', 'null'::jsonb, FALSE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules" ("id", "course_id", "module_no", "title", "description", "pressure_points", "user_confusion", "industry_challenge", "prerequisites", "what_youll_learn", "when_to_apply", "learning_content", "support", "knowledge", "module_problem_statement", "tools", "is_published", "is_active")
VALUES ('75003941-b763-5c96-9fff-c47c6e00a5b5'::uuid, '0a010796-10c0-5287-b89a-6ab56bd71399'::uuid, 4, 'Exceptions, Blockers, Risks & Escalations', 'Learner identifies exceptions, blockers, dependency risks, wrong-owner routes, and pressure traps, then escalates with evidence and safe next step.', NULL, NULL, NULL, NULL, NULL, NULL, '["Learn escalation structure and owner mapping.", "Compare weak vs strong escalation under pressure.", "Write risk and escalation note for unresolved blockers.", "Submit escalation note with evidence, owner, consequence, and safe next step."]'::jsonb, '["Classify two blockers and link each to evidence.", "Map each blocker to owner/status: known owner or SME validation required.", "Draft a five-part supervisor note.", "Challenge the learner to name owner, risk, consequence, and safe next step; help rewrite unclear escalation after draft.", "Exception classification board", "Escalation matrix mockup", "Weak vs strong escalation note", "Conflict role-play activity", "Empathy-with-boundary wording card", "Pressure-to-safety decision simulation"]'::jsonb, '["Exception Classification", "Escalation Matrix Reading", "Supervisor Note Writing", "Composure During Conflict", "Empathy Without Overpromising", "Urgency Without Unsafe Release"]'::jsonb, 'The guest is still waiting, the queue has grown, housekeeping has not updated inspection status, and the payment hold is still visible. Learner must escalate the right blocker to the right owner with evidence and urgency, without letting pressure cause unsafe access or false reassurance.', 'null'::jsonb, FALSE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules" ("id", "course_id", "module_no", "title", "description", "pressure_points", "user_confusion", "industry_challenge", "prerequisites", "what_youll_learn", "when_to_apply", "learning_content", "support", "knowledge", "module_problem_statement", "tools", "is_published", "is_active")
VALUES ('3d7514ef-3b3f-551d-b87d-72717114909d'::uuid, '0a010796-10c0-5287-b89a-6ab56bd71399'::uuid, 5, 'Quality, Communication & Closure', 'Learner checks whether L1 work is clear, complete, safe, and ready for review/closure while distinguishing completed work from unresolved risks.', NULL, NULL, NULL, NULL, NULL, NULL, '["Learn closure quality and communication clarity.", "Compare false vs responsible closure examples.", "Write closure report using previous artifacts.", "Submit closure report with pending risk, owner action, and portfolio proof."]'::jsonb, '["Classify closure status as L1 complete / owner pending / unresolved risk.", "Run a five-point quality check on the closure report.", "Write one remaining-risk statement for the closure report.", "Compare false vs responsible closure wording, flag missing remaining risk, and ask whether L1 has authority to close access decision.", "Closure status decision card", "Quality checklist overlay", "Remaining-risk communication card", "False vs responsible closure samples", "Self-review checklist + revision note", "Completion field checklist"]'::jsonb, '["Responsible Closure vs Resolution", "Quality Check for Arrival Readiness", "Remaining Risk Communication", "False Closure Detection", "Structured Self-Review", "Documentation Completeness"]'::jsonb, 'The learner must prepare closure status without pretending the case is solved. Supervisor review has been requested, but payment hold and room inspection may still be pending. Learner must separate completed L1 work from unresolved owner action and write truthful closure for handoff/review.', 'null'::jsonb, FALSE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules" ("id", "course_id", "module_no", "title", "description", "pressure_points", "user_confusion", "industry_challenge", "prerequisites", "what_youll_learn", "when_to_apply", "learning_content", "support", "knowledge", "module_problem_statement", "tools", "is_published", "is_active")
VALUES ('635864f6-1f2c-5e4c-ae2e-06ffef18a321'::uuid, '0a010796-10c0-5287-b89a-6ab56bd71399'::uuid, 6, 'Portfolio, Transfer & Final Validation', 'Learner assembles evidence chain, defends decisions, applies same logic to a new visitor readiness case, and proves guided L1 capability.', NULL, NULL, NULL, NULL, NULL, NULL, '["Learn portfolio proof and transfer expectation.", "Compare guest and visitor readiness signals.", "Apply evidence-readiness method to visitor case.", "Submit final portfolio with artifact chain, transfer response, defense, and reflection."]'::jsonb, '["Create a portfolio index row for every artifact.", "Write two decision-trace lines linking evidence to action.", "Run a QA checklist and mark export-ready / needs revision.", "Prompt learner to identify transfer pattern, missing host confirmation, role boundary, and improvement evidence after learner submits first defense draft.", "Portfolio index template", "Decision traceability map", "Portfolio QA checklist + export preview", "Visitor case card + transfer challenge", "Interview story builder", "Feedback-to-revision tracker"]'::jsonb, '["Evidence Indexing", "Decision Traceability", "Portfolio QA and PDF Export", "Visitor Transfer Case Logic", "Interview Storytelling from Evidence", "Learning from Feedback"]'::jsonb, 'The learner assembles portfolio proof and then applies the same readiness method to a new visitor case: corporate visitor Anika Rao arrives for a meeting with guest/company contact, but host confirmation is missing and ID has a minor spelling variation. Learner must defend evidence logic and transfer role-safe escalation without treating visitor access like guest check-in approval.', 'null'::jsonb, FALSE, TRUE)
ON CONFLICT DO NOTHING;

COMMIT;
