// Centralized application copy and interaction configuration.
export const UI_TEXT = {
  notifications: "Notifications",
  closeNotifications: "Close notifications",
  loadingNotifications: "Loading notifications",
  notificationsUnavailable: "Notifications are temporarily unavailable.",
  retry: "Try again",
  noNotifications: "No notifications yet",
  notificationDescription: "Your learning and review updates will appear here.",
  upcoming: "Upcoming",
  recentFeedback: "Recent feedback",
  sectionRetryDescription: "Please try this section again. Other sections remain available.",
  lteAccessRequired: "LTE Access Required",
  accessDescription:
    "Your SkillPassport account does not currently have active LTE product access enabled.",
  manageSubscriptionOnSkillpassport: "Manage Subscription on SkillPassport",
  skipToMainContent: "Skip to main content",
  navigationMenu: "Navigation menu",
  closeNavigationDrawer: "Close navigation drawer",
  allRoles: "All Roles",
  failedToLoadCourses: "Failed to load courses",
  retryLoadingCourses: "Retry Loading Courses",
  noLearningPathYet: "No learning path yet",
  assessmentDescription:
    "Take a quick assessment to get your personalized learning track and unlock your courses.",
  noCourses: "No courses found. Please check back later.",
  myLearning: "My Learning",
  coursesHeading: "Courses",
  coursesDescription: "Track your enrolled courses and continue where you left off.",
  enrolled: "Enrolled",
  completed: "Completed",
  inProgress: "In Progress",
  resultsFor: "results for",
  clearSearch: "Clear search",
  filterByRole: "Filter by role",
  filter: "Filter",
  courses: "courses",
  displayType: "Display type",
  gridView: "Grid view",
  listView: "List view",
  noSearchResults: "No courses match your search. Try another topic or clear your search.",
  noCoursesOnPage: "No courses found on this page.",
  unableToLoadDashboard: "Unable to load Dashboard",
  dashboardErrorDescription: "There was an error loading your dashboard metrics. Please try again.",
  loadingDashboard: "Loading dashboard…",
  retryLoadingDashboard: "Retry Loading Dashboard",
  loadingDashboardLabel: "Loading dashboard...",
  closeDialog: "Close dialog",
  toggleNavigationMenu: "Toggle navigation menu",
  searchLearningContent: "Search learning content",
  searchCoursesSkillsTopics: "Search courses, skills, topics",
  searchPlaceholder: "Search courses, skills, topics...",
  account: "Account",
  yourProfile: "Your Profile",
  logout: "Logout",
  dashboard: "Dashboard",
  certificates: "Certificates",
  rewardsMilestones: "Rewards & Milestones",
  careerExplorer: "Career Explorer",
  learningProgress: "Learning Progress",
  mentorFeedback: "Mentor Feedback",
  achievements: "Achievements",
  settings: "Settings",
  expandSidebar: "Expand sidebar",
  collapseSidebar: "Collapse sidebar",
  mainNavigation: "Main navigation",
  askAiMentorComingSoon: "Ask AI Mentor — Coming soon",
  mentorPrompt: "Need help choosing what to do next?",
  mentorDescription: "Get guidance from your AI Mentor",
  askAiMentor: "Ask AI Mentor",
  viewAll: "View all",
  viewAllAchievements: "View all achievements",
  nextMilestoneProgress: "Next milestone progress",
  achievementDetails: "Achievement details",
  achievementEmptyDescription: "Your achievements will appear here as you learn.",
  capabilityGapMap: "Capability Gap Map",
  capabilityMapTooltip:
    "Compare your current capability levels with the levels required for your career target.",
  viewFullMap: "View full map",
  seeHowLevelsWork: "See how levels work",
  capabilityLevels: "Capability levels",
  capability: "Capability",
  currentLevel: "Current Level",
  targetLevel: "Target Level",
  capabilityEmptyDescription:
    "Capability levels will appear as you progress through your learning path.",
  howCapabilityLevelsWork: "How capability levels work",
  capabilityComparisonDescription: "Your current levels alongside your career target requirements.",
  current: "Current:",
  target: "· Target:",
  noCapabilityLevelsAvailableYet: "No capability levels available yet.",
  recommendedCareerPaths: "Recommended Career Paths",
  aiMatchedBasedOnYourSkillsInterestsTrajectory:
    "AI-matched based on your skills, interests & trajectory",
  exploreAll: "Explore all",
  basedOnYourActivityIn: "Based on your activity in",
  trackExplorer: "Track Explorer",
  careerTrackEmptyDescription: "Your career tracks will appear after your assessment.",
  viewPath: "View Path",
  whyItFits: "WHY IT FITS",
  showLess: "Show less",
  showMore: "... show more",
  overallProgress: "OVERALL PROGRESS",
  careerPathProgress: "Career path progress",
  roles: "ROLES",
  completion: "COMPLETION",
  marketStatus: "MARKET STATUS",
  curriculumAnalysis: "Curriculum Analysis",
  exploreCareerPaths: "Explore career paths",
  careerTracksDescription:
    "Choose from your assessment recommendations. Switching updates your active learning path.",
  noCareerTracksAvailableYet: "No career tracks available yet.",
  careerTarget: "Career Target",
  filterTargetRoles: "Filter target roles",
  chooseYourCareerTrack: "Choose your career track",
  roleReadiness: "Role readiness",
  roleReadinessHeading: "Role Readiness",
  strengths: "Strengths",
  capabilityGaps: "Capability Gaps",
  viewReadinessReport: "View Readiness Report",
  domain: "Domain",
  industry: "Industry",
  level: "Level",
  xp: "XP",
  thisWeek: "this week",
  streak: "Streak",
  days: "Days",
  keepItUp: "Keep it up!",
  badges: "Badges",
  continueYourJourney: "CONTINUE YOUR JOURNEY",
  journeyCompletedTitle: "Level Complete — Outstanding Work!",
  yourJourneyStartsHere: "Your Journey Starts Here",
  journeyCompletedDescription:
    "You finished every level in this track. Pick your next capability to keep the momentum going.",
  journeyEmptyDescription:
    "Choose a career path and capability to unlock your first learning level.",
  chooseNextCapability: "Choose Next Capability",
  exploreCareerPathsAction: "Explore Career Paths",
  output: "Output",
  whyItMatters: "Why it matters",
  journeyProgress: "Journey Progress",
  journeyProgressLabel: "Journey progress",
  remaining: "Remaining",
  continueChallenge: "Continue Challenge",
  viewDetails: "View Details",
  todaySPriorities: "Today's Priorities",
  dailyXpGoal: "Daily XP Goal",
  viewAllTasks: "View all tasks",
  prioritiesEmptyDescription: "You're all caught up. Explore your courses to keep learning.",
  upcomingFeedback: "Upcoming & Feedback",
  reviewTooltip: "Track pending staff reviews and open recent feedback on your submitted work.",
  upcomingHeading: "UPCOMING",
  recentFeedbackHeading: "RECENT FEEDBACK",
  careerTargetSummary: "Career Target Summary",
  journeyAndPriorities: "Journey and Priorities",
  capabilitiesAndUpcomingEvents: "Capabilities and Upcoming Events",
  careerPathsAndAchievements: "Career Paths and Achievements",
  learner: "Learner",
  comingSoon: (label: string) => `${label} is coming soon`,
  aiMentorComingSoon: "AI Mentor is coming soon",
  comingSoonIcon: "⏳",
  active: "Active",
  explore: "Explore",
  trackA: "Track A",
  trackB: "Track B",
  trackC: "Track C",
  trackSwitchFailed: "Failed to switch learning track",
  careerPathDescription: "Explore your courses to learn more about your recommended path.",
  retrying: "Retrying…",
  searchTooLong: "Please keep your search under 200 characters.",
  about: (title: string) => `About ${title}`,
  accountMenu: (name: string) => `${name}, account menu`,
  viewAchievement: (title: string) => `View ${title} achievement`,
  achievementCounts: (unlocked: number, shown: number) => `${unlocked} unlocked • ${shown} shown`,
  availableAchievementDetails: (unlocked: number, available: number) =>
    `${unlocked} unlocked · Details for ${available} available badges`,
  capabilityComparison: (current: string, target: string) =>
    `Current: ${current} · Target: ${target}`,
  switchingTrack: (title: string) => `Switching to ${title}…`,
  switchedTrack: (title: string) => `Switched active track to ${title}`,
  switchTrack: (title: string) => `Switch to ${title}`,
  activeTrack: (title: string) => `${title}, active career track`,
  match: (percentage: number) => `${percentage}% Match`,
  sectionUnavailable: (label: string) => `${label} is temporarily unavailable`,
  cardContent: (title: string) => `${title} content`,
  searchResults: (count: number) => `${count} results for`,
  quotedSearch: (query: string) => `“${query}”`,
} as const;

export const UI_INTERACTION_CLASSES =
  "[&_:is(a,button,input,[tabindex]):focus-visible]:outline-2 [&_:is(a,button,input,[tabindex]):focus-visible]:outline-brand-600 [&_:is(a,button,input,[tabindex]):focus-visible]:outline-offset-3 pointer-coarse:[&_button]:min-h-11 pointer-coarse:[&_a]:min-h-11 pointer-coarse:[&_button[aria-label]]:min-w-11 pointer-coarse:[&_a[aria-label]]:min-w-11 motion-reduce:[&_*]:animate-none! motion-reduce:[&_*]:transition-none! motion-reduce:[&_*]:scroll-auto!";
export const DESKTOP_NAVIGATION_MEDIA = "(min-width: 1024px)";
export const DASHBOARD_SCROLL_CONTAINER_ID = "dashboard-scroll-container";
export const FOCUSABLE_CONTROL_SELECTOR =
  'button:not([disabled]), a[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"]):not([disabled])';

export const SEARCH_QUERY_MAX_LENGTH = 200;
export const CAREER_RATIONALE_PREVIEW_LENGTH = 300;
export const ACHIEVEMENT_IMAGES: Record<string, string> = {
  project: "/assets/images/badge_first_project.png",
  streak: "/assets/images/badge_streak.png",
  api: "/assets/images/badge_api_mastery.png",
  architect: "/assets/images/badge_system_architect.png",
};
export const CAPABILITY_LEVEL_DESCRIPTIONS = [
  ["Foundation", "Build familiarity with the core concepts."],
  ["Developing", "Practice applying concepts with guidance."],
  ["Working Knowledge", "Apply the capability to familiar tasks."],
  ["Proficient", "Apply the capability independently to practical challenges."],
] as const;

// Height bounds apply to each card independently; excess content remains scrollable.
export const DASHBOARD_CARD_HEIGHTS = {
  standard: "min-h-80 max-h-[30rem]",
  achievements: "min-h-[22.5rem] max-h-[35rem]",
  careerPaths: "min-h-[25rem] max-h-[45rem] lg:max-h-[40rem]",
  journey: "min-h-[21.25rem] max-h-[40rem] lg:max-h-[30rem]",
  careerTarget: "min-h-64 max-h-[40rem] xl:min-h-40 xl:max-h-64",
} as const;

export const DASHBOARD_ROW_HEIGHTS = {
  journey: "lg:auto-rows-[27.5rem]",
  capabilities: "lg:auto-rows-[26rem]",
  careers: "lg:auto-rows-[35rem]",
} as const;
