-- Generated from LTE_LEARNING_CATALOG_TEMPLATE.xlsx: public.skills.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.skills
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('2370cc9b-bb66-5ace-9cfd-e3907bc9be37'::uuid, 'HTT_SK001', 'Confirm Guest & Visitor Reception eligibility and readiness evidence', 'Learner can confirm Guest & Visitor Reception eligibility and readiness evidence using Reservation record, guest ID evidence, PMS/front-office screen, room-status board, and key/access handoff checklist with guided support to produce the required work output, handoff, or evidence record.', '["Guest eligibility", "visitor eligibility", "reception readiness", "booking verification", "appointment confirmation", "identity verification", "access authorization", "arrival readiness", "host confirmation", "documentation check", "reception checklist", "entry requirements", "readiness evidence", "guest validation", "visitor screening"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('0b5e8893-a2a7-5622-8d9a-1f3951a676cd'::uuid, 'HTT_SK002', 'Allocate service resource for guest arrival identity and stay handoff using guest/visitor identity and service request', 'Learner can allocate service resource for guest arrival identity and stay handoff using guest/visitor identity and service request using Reservation record, guest ID evidence, PMS/front-office screen, room-status board, and key/access handoff checklist with guided support to produce the required work output, handoff, or evidence record.', '["Resource allocation", "guest arrival", "identity confirmation", "service request", "stay handoff", "reception assignment", "staff assignment", "room readiness", "host coordination", "arrival assistance", "guest registration", "check-in support", "service ownership", "handoff coordination", "hospitality operations"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('3680861a-9f9d-5d45-bb35-6f8e2e345257'::uuid, 'HTT_SK003', 'Allocate service resource for visitor information routing service direction using guest/visitor identity service request', 'Learner can allocate service resource for visitor information routing service direction using guest/visitor identity service request using Reservation record, guest ID evidence, PMS/front-office screen, room-status board, and key/access handoff checklist independently for routine cases to produce the required work output, handoff, or evidence record.', '["Visitor information", "information routing", "service direction", "visitor identity", "service request", "enquiry handling", "destination guidance", "department routing", "contact identification", "front desk support", "visitor assistance", "service navigation", "resource assignment", "query ownership", "reception coordination"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('2382fc3b-dd54-54b6-9846-969a2bf560c7'::uuid, 'HTT_SK004', 'Reconcile Guest & Visitor Reception completion evidence before closure or downstream handoff', 'Learner can reconcile Guest & Visitor Reception completion evidence before closure or downstream handoff using Reservation record, guest ID evidence, PMS/front-office screen, room-status board, and key/access handoff checklist independently for routine cases to produce the required work output, handoff, or evidence record.', '["Completion verification", "evidence reconciliation", "reception closure", "handoff validation", "service completion", "checklist review", "record accuracy", "documentation reconciliation", "downstream handoff", "closure approval", "pending action check", "reception records", "audit trail", "completion evidence", "service confirmation"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('af4131f4-4cfd-50dd-9e2c-f61337400adf'::uuid, 'HTT_SK005', 'Resolve identity mismatch or unpaid hold during guest arrival identity', 'Learner can resolve identity mismatch or unpaid hold during guest arrival identity using Reservation record, guest ID evidence, PMS/front-office screen, room-status board, and key/access handoff checklist during exceptions to produce the required work output, handoff, or evidence record.', '["Identity mismatch", "guest verification", "unpaid hold", "payment status", "booking discrepancy", "escalation", "exception handling", "arrival issue resolution", "check-in hold", "document mismatch", "billing coordination", "access restriction", "corrective action", "guest communication", "incident resolution"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('7ae2d40c-3a20-5110-a830-1aafaebd7d36'::uuid, 'HTT_SK006', 'Resolve wrong direction or unowned query during visitor information routing', 'Learner can resolve wrong direction or unowned query during visitor information routing using Reservation record, guest ID evidence, PMS/front-office screen, room-status board, and key/access handoff checklist during exceptions to produce the required work output, handoff, or evidence record.', '["Wrong direction", "unowned query", "visitor redirection", "query ownership", "routing error", "information correction", "escalation pathway", "service recovery", "visitor assistance", "department coordination", "enquiry resolution", "destination verification", "handoff failure", "front desk intervention", "issue closure"]'::jsonb)
ON CONFLICT DO NOTHING;

COMMIT;
