-- Generated from LTE_LEARNING_CATALOG_CAP_CREDIT_001_FINAL_VALIDATED.xlsx: public.artifact_questions.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.artifact_questions
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('eed61dd3-5068-5acb-b125-c3cac0c72c43'::uuid, 'b9a9ade1-c8a0-5093-a9a8-e12ad849e49e'::uuid, 1, 'Complete: M00_EXPRESS_Course_Readiness_Sheet.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: M00_EXPRESS_Course_Readiness_Sheet.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M00_EXPRESS_Course_Readiness_Sheet.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('50b6bfd6-cfb9-5cd9-8459-b28fd0cc961d'::uuid, 'ccc37e1a-a5d4-5fb3-8d7c-df79f7ae01ea'::uuid, 1, 'Complete: M00_EVOLVE_Similar_Case_Readiness_Check.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: M00_EVOLVE_Similar_Case_Readiness_Check.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M00_EVOLVE_Similar_Case_Readiness_Check.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('5605fbc6-1609-5530-821c-b3d79b8d75a6'::uuid, '653dcdb2-5546-5fdd-9a1d-2c68e619c60a'::uuid, 1, 'Complete: M01_EXPRESS_Case_Intake_Note.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: M01_EXPRESS_Case_Intake_Note.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M01_EXPRESS_Case_Intake_Note.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('e4751e8c-44c5-5a16-acb3-acbde09a8d66'::uuid, '5a78f5b8-aaa8-59dd-89f5-f72fade5e4a4'::uuid, 1, 'Complete: M01_EVOLVE_Step_Up_Case_Intake_Note.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: M01_EVOLVE_Step_Up_Case_Intake_Note.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M01_EVOLVE_Step_Up_Case_Intake_Note.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('708382dc-c521-5829-aedc-a12499ab3b4d'::uuid, 'ec4b82fe-55bd-52bf-92dd-c7634ba82d43'::uuid, 1, 'Complete: M02_EXPRESS_Evidence_Validation_Checklist.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: M02_EXPRESS_Evidence_Validation_Checklist.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M02_EXPRESS_Evidence_Validation_Checklist.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('154ad983-579d-5b83-a216-1d2303aebd7b'::uuid, 'a902a466-dc92-5416-ad65-646cf19daa1d'::uuid, 1, 'Complete: M02_EVOLVE_Step_Up_Evidence_Validation_Checklist.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: M02_EVOLVE_Step_Up_Evidence_Validation_Checklist.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M02_EVOLVE_Step_Up_Evidence_Validation_Checklist.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('1a8de807-6a1b-518c-8586-4a504ca6a074'::uuid, 'd0c367bf-6454-53a5-b07d-59f89112d1df'::uuid, 1, 'Complete: M03_EXPRESS_Action_or_Handoff_Note.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: M03_EXPRESS_Action_or_Handoff_Note.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M03_EXPRESS_Action_or_Handoff_Note.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('f9444d0e-72f8-549a-aa30-0889a33ff9e0'::uuid, '083e34c4-5a39-5fbf-bc5d-382d143c7446'::uuid, 1, 'Complete: M03_EVOLVE_Step_Up_Action_or_Handoff_Note.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: M03_EVOLVE_Step_Up_Action_or_Handoff_Note.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M03_EVOLVE_Step_Up_Action_or_Handoff_Note.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('100a62cd-addb-5b0b-98b9-9c8f23f96cce'::uuid, '754f6aab-bcba-5706-b8be-c730fedb71d8'::uuid, 1, 'Complete: M04_EXPRESS_Risk_and_Escalation_Note.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: M04_EXPRESS_Risk_and_Escalation_Note.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M04_EXPRESS_Risk_and_Escalation_Note.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('6e60069b-b8f4-5d23-b279-8f069bb1796e'::uuid, '05a106aa-62fd-5dca-a7de-9108bf237b26'::uuid, 1, 'Complete: M04_EVOLVE_Step_Up_Risk_and_Escalation_Note (1).xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: M04_EVOLVE_Step_Up_Risk_and_Escalation_Note (1).xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M04_EVOLVE_Step_Up_Risk_and_Escalation_Note (1).xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('efeef6bc-9f4c-581a-a880-1c6a8b6a2eaf'::uuid, 'f5bd31ea-970d-55d1-804d-fb2c66c4f1b3'::uuid, 1, 'Complete: M05_EXPRESS_Quality_and_Closure_Report.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: M05_EXPRESS_Quality_and_Closure_Report.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M05_EXPRESS_Quality_and_Closure_Report.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('597d0208-1aaf-529d-a34a-cd2dc26fd136'::uuid, 'a1b7f9c5-67d0-5b0a-b84a-d173ddf4c758'::uuid, 1, 'Complete: M05_EVOLVE_Step_Up_Quality_and_Closure_Report.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: M05_EVOLVE_Step_Up_Quality_and_Closure_Report.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M05_EVOLVE_Step_Up_Quality_and_Closure_Report.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('fb11dea3-ed9c-5f53-94ba-77db5134bed3'::uuid, '54183672-858e-5d05-ad10-8dceea189b26'::uuid, 1, 'Complete: M06_EXPRESS_Final_Portfolio_Pack.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: M06_EXPRESS_Final_Portfolio_Pack.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M06_EXPRESS_Final_Portfolio_Pack.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('14cf46d2-c796-5332-b767-ab628f193dfe'::uuid, '6b571805-2f76-54af-a6de-1c1de297b332'::uuid, 1, 'Complete: M06_EVOLVE_Independent_Transfer_Case_Validation_Pack.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: M06_EVOLVE_Independent_Transfer_Case_Validation_Pack.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: M06_EVOLVE_Independent_Transfer_Case_Validation_Pack.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('b9848131-be03-550b-bc19-acffaaff6667'::uuid, '3de1e677-890e-5af6-8e23-1231b327f812'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M00_EXPRESS_Pre_Screen_Readiness_Map_v4.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M00_EXPRESS_Pre_Screen_Readiness_Map_v4.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M00_EXPRESS_Pre_Screen_Readiness_Map_v4.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('1708f7e6-2a4c-530f-98d7-13c30e993f98'::uuid, 'e5f835d3-287e-5c26-99ca-17b90b016918'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M00_EVOLVE_Step_Up_Pre_Screen_Readiness_Check_v4.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M00_EVOLVE_Step_Up_Pre_Screen_Readiness_Check_v4.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M00_EVOLVE_Step_Up_Pre_Screen_Readiness_Check_v4.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('3bb6c5f0-ee28-54e0-8bc5-c37118f2fee9'::uuid, '2a73bc1d-8a51-5ef8-bcb5-b05a57fe2cda'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M01_EXPRESS_Loan_Intake_Tracker_Entry.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M01_EXPRESS_Loan_Intake_Tracker_Entry.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M01_EXPRESS_Loan_Intake_Tracker_Entry.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('9ad0a7f1-44f2-5617-a13d-10b14cec43c7'::uuid, '393a0f41-9b3c-5563-b1bd-658c856337ea'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M01_EVOLVE_Step_Up_Intake_Tracker_Entry.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M01_EVOLVE_Step_Up_Intake_Tracker_Entry.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M01_EVOLVE_Step_Up_Intake_Tracker_Entry.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('1d9a1435-3838-57d0-9a57-1e674e8aa488'::uuid, 'bc13ae63-101f-57de-80f8-5f6ac8658d15'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M02_EXPRESS_Evidence_Gap_Tracker.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M02_EXPRESS_Evidence_Gap_Tracker.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M02_EXPRESS_Evidence_Gap_Tracker.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('d1b57087-7362-5fba-a23c-a0f63bc6315b'::uuid, '71e345cd-cde2-58f5-979f-6a0ce0075f6b'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M02_EVOLVE_Step_Up_Evidence_Gap_Tracker.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M02_EVOLVE_Step_Up_Evidence_Gap_Tracker.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M02_EVOLVE_Step_Up_Evidence_Gap_Tracker.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('c3053a17-56c2-5f0d-93e7-ba3502ed5a03'::uuid, '2bba3e17-c6e4-5052-804a-54fae18ce2f3'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M03_EXPRESS_Credit_Information_Exposure_Note.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M03_EXPRESS_Credit_Information_Exposure_Note.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M03_EXPRESS_Credit_Information_Exposure_Note.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('5079e8c4-7e37-5a4b-956f-c9df83c87d6a'::uuid, '5dc301b9-5bbe-5190-970b-452de41b5ad1'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M03_EVOLVE_Step_Up_Exposure_Exception_Note.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M03_EVOLVE_Step_Up_Exposure_Exception_Note.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M03_EVOLVE_Step_Up_Exposure_Exception_Note.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('a8a2a05f-c71f-5964-818d-4ca44e2c07f0'::uuid, '7add65d0-45c6-5a3c-aeb6-175078321c8c'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M04_EXPRESS_Draft_Appraisal_Support_Note.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M04_EXPRESS_Draft_Appraisal_Support_Note.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M04_EXPRESS_Draft_Appraisal_Support_Note.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('8ca2eb8f-5cb7-5e99-93b1-179ad64dec2f'::uuid, '2af1683a-385f-5f77-98b6-287ff63ea422'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M04_EVOLVE_Step_Up_Appraisal_Support_Note.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M04_EVOLVE_Step_Up_Appraisal_Support_Note.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M04_EVOLVE_Step_Up_Appraisal_Support_Note.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('f4bc8fd5-f59d-5b1e-97d0-bae957e92b70'::uuid, '40dbfe8c-0551-5b97-978c-e64c13c0a409'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M05_EXPRESS_Reviewer_Handoff_Quality_Closure_Report.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M05_EXPRESS_Reviewer_Handoff_Quality_Closure_Report.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M05_EXPRESS_Reviewer_Handoff_Quality_Closure_Report.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('715a16f1-a501-554b-90c2-727a56931134'::uuid, 'ebc3236a-bb34-548d-a5a0-0ef5651aba18'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M05_EVOLVE_Step_Up_Quality_Closure_Report.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M05_EVOLVE_Step_Up_Quality_Closure_Report.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M05_EVOLVE_Step_Up_Quality_Closure_Report.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('bf977684-4de2-53e8-80b1-57f19df5b9e6'::uuid, '9b57154b-6f72-53e2-a688-bb6419ea606d'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M06_EXPRESS_Final_Showcase_Portfolio_Pack_REVIEW_FIXED.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M06_EXPRESS_Final_Showcase_Portfolio_Pack_REVIEW_FIXED.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M06_EXPRESS_Final_Showcase_Portfolio_Pack_REVIEW_FIXED.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('d109665c-f447-54f0-b0e4-8c70252d7a10'::uuid, 'afa3424f-1c7a-5777-a9a8-e72243b61daa'::uuid, 1, 'Complete: CAP-CREDIT-001_L2_M06_EVOLVE_Independent_Transfer_Case_Validation_Pack (1).xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L2_M06_EVOLVE_Independent_Transfer_Case_Validation_Pack (1).xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L2_M06_EVOLVE_Independent_Transfer_Case_Validation_Pack (1).xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('6764b763-ad26-5ccb-9366-84a18e8bcb68'::uuid, 'ada5b2b2-e08b-56d7-b181-e600b87eabd8'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M00_EXPRESS_Exception-Handling_Readiness_Map_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M00_EXPRESS_Exception-Handling_Readiness_Map_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M00_EXPRESS_Exception-Handling_Readiness_Map_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('e00218cc-cd87-5148-82a2-848daaa7ee40'::uuid, 'c87a3d01-40fe-5491-93d6-2a6b8038fb72'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M00_EVOLVE_Step-Up_Exception_Readiness_Check_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M00_EVOLVE_Step-Up_Exception_Readiness_Check_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M00_EVOLVE_Step-Up_Exception_Readiness_Check_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('25054607-d837-554a-a8ba-a0beb2410a96'::uuid, '11b79fe9-ecd1-5451-9ca7-58721338de38'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M01_EXPRESS_Exception_Intake_and_Inventory_Register_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M01_EXPRESS_Exception_Intake_and_Inventory_Register_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M01_EXPRESS_Exception_Intake_and_Inventory_Register_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('4c115d0b-643d-59a4-aae0-10064d996a74'::uuid, '3aeac146-ab23-50df-a308-cd6fd761d2d8'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M01_EVOLVE_Step-Up_Exception_Intake_Register_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M01_EVOLVE_Step-Up_Exception_Intake_Register_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M01_EVOLVE_Step-Up_Exception_Intake_Register_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('11c7fabb-e7c2-5272-8dd9-fcfdb0a8a465'::uuid, '83a53adf-6474-5880-b811-3b448debc824'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M02_EXPRESS_Evidence_Conflict_and_Source-of-Truth_Matrix_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M02_EXPRESS_Evidence_Conflict_and_Source-of-Truth_Matrix_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M02_EXPRESS_Evidence_Conflict_and_Source-of-Truth_Matrix_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('c76d9a10-c706-52c6-bfc1-69efbfbccfae'::uuid, '8d885867-051e-5714-938b-2cea43484f3e'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M02_EVOLVE_Step-Up_Evidence_Conflict_Matrix_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M02_EVOLVE_Step-Up_Evidence_Conflict_Matrix_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M02_EVOLVE_Step-Up_Evidence_Conflict_Matrix_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('05fca022-b526-5366-b20e-5728562a0f1c'::uuid, '189a6417-6143-5332-a214-bc12b06140fe'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M03_EXPRESS_Exposure_and_Linked-Party_Exception_Note_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M03_EXPRESS_Exposure_and_Linked-Party_Exception_Note_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M03_EXPRESS_Exposure_and_Linked-Party_Exception_Note_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('af76d0e0-a3f4-5b21-b32c-0d180b231331'::uuid, '2dca8ce1-7218-58a7-9309-5de2e466473e'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M03_EVOLVE_Step-Up_Exposure_Exception_Note_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M03_EVOLVE_Step-Up_Exposure_Exception_Note_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M03_EVOLVE_Step-Up_Exposure_Exception_Note_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('9aa04e80-beda-5ebe-9369-2e4454fbd4ff'::uuid, 'fe601fa8-5791-56ef-9c6c-b4e5e4a521c0'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M04_EXPRESS_Exception_Priority_and_Escalation_Plan_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M04_EXPRESS_Exception_Priority_and_Escalation_Plan_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M04_EXPRESS_Exception_Priority_and_Escalation_Plan_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('3d978f53-d2c9-5f8a-9bfc-c0aa9f0d1bc2'::uuid, 'ebcb7486-5e49-5f76-b090-7c1c0774d74a'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M04_EVOLVE_Step-Up_Escalation_Routing_Plan_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M04_EVOLVE_Step-Up_Escalation_Routing_Plan_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M04_EVOLVE_Step-Up_Escalation_Routing_Plan_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('d1c248b4-46d9-5bf6-be2b-57d872e7a5d5'::uuid, '49d7cc70-513e-5833-abfd-e02ea6993152'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M05_EXPRESS_Reviewer_Exception_Handoff_Pack_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M05_EXPRESS_Reviewer_Exception_Handoff_Pack_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M05_EXPRESS_Reviewer_Exception_Handoff_Pack_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('601b9fb6-3d7e-537e-a91a-021c939e4b5a'::uuid, 'c0f36493-b593-5c5e-9a75-6bdbf02781e5'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M05_EVOLVE_Step-Up_Reviewer_Exception_Handoff_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M05_EVOLVE_Step-Up_Reviewer_Exception_Handoff_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M05_EVOLVE_Step-Up_Reviewer_Exception_Handoff_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('552aee37-c331-5462-970a-6c50d99ba88a'::uuid, '9c59fc00-b459-54f8-90d4-c0d31dfec48f'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M06_EXPRESS_Final_L3_Exception_Case_Portfolio_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M06_EXPRESS_Final_L3_Exception_Case_Portfolio_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M06_EXPRESS_Final_L3_Exception_Case_Portfolio_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('5f83f1cc-5d77-503a-a611-4687bbcaec06'::uuid, '65639309-54b1-5bdb-91f2-7229128322ae'::uuid, 1, 'Complete: CAP-CREDIT-001_L3_M06_EVOLVE_Independent_Exception_Transfer_Defence_Pack_FINAL_QA_CLEANED_SME_PENDING.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L3_M06_EVOLVE_Independent_Exception_Transfer_Defence_Pack_FINAL_QA_CLEANED_SME_PENDING.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L3_M06_EVOLVE_Independent_Exception_Transfer_Defence_Pack_FINAL_QA_CLEANED_SME_PENDING.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('81c9eaf2-444a-5f31-ba8b-529a71e4eba9'::uuid, '0f2aa74f-27c7-5768-a43f-c8d11fa76d40'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M00_EXPRESS_Integrated_Quality_Readiness_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M00_EXPRESS_Integrated_Quality_Readiness_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M00_EXPRESS_Integrated_Quality_Readiness_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('a852f968-3e1f-5665-aaff-3967d93b73a7'::uuid, 'b415eff8-6775-56f2-b6dc-8058cbab6742'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M00_EVOLVE_Step-Up_Integrated_Quality_Readiness_Check_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M00_EVOLVE_Step-Up_Integrated_Quality_Readiness_Check_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M00_EVOLVE_Step-Up_Integrated_Quality_Readiness_Check_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('04fcfcf4-07a1-5c94-a895-dfff37986dae'::uuid, '153da3df-0d6c-58e6-92ca-9c86da927067'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M01_EXPRESS_Multi-Packet_Quality_Intake_Register_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M01_EXPRESS_Multi-Packet_Quality_Intake_Register_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M01_EXPRESS_Multi-Packet_Quality_Intake_Register_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('f6af5650-d0e9-59cc-acce-8655e6aa157b'::uuid, '2bfbe61f-e36a-5aef-bc7a-aa2e9e87e5c8'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M01_EVOLVE_Step-Up_Packet_Quality_Register_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M01_EVOLVE_Step-Up_Packet_Quality_Register_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M01_EVOLVE_Step-Up_Packet_Quality_Register_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('5fb8baa0-5b4d-55d2-a7c3-62da20697314'::uuid, '1460fa0c-b6ef-5211-8bef-75ff7bcec1ec'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M02_EXPRESS_Cross-Functional_Evidence_and_Dependency_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M02_EXPRESS_Cross-Functional_Evidence_and_Dependency_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M02_EXPRESS_Cross-Functional_Evidence_and_Dependency_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('3f15f333-d41a-5ed9-8060-18b32286aeb9'::uuid, 'ef433186-0882-595b-97ff-c5f9bdf84bd9'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M02_EVOLVE_Step-Up_Dependency_Integration_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M02_EVOLVE_Step-Up_Dependency_Integration_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M02_EVOLVE_Step-Up_Dependency_Integration_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('62df031a-1bf5-5287-afd7-8c15c293f49d'::uuid, 'fd7db030-0b50-5654-ad0d-b11a0968569c'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M03_EXPRESS_Appraisal_Support_Correction_and_Traceability_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M03_EXPRESS_Appraisal_Support_Correction_and_Traceability_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M03_EXPRESS_Appraisal_Support_Correction_and_Traceability_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('758c7ec5-fd75-5614-aa20-e3f8f8c834ce'::uuid, '25aaf6f7-d704-5da6-b190-07ca83b604fd'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M03_EVOLVE_Step-Up_Correction_Control_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M03_EVOLVE_Step-Up_Correction_Control_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M03_EVOLVE_Step-Up_Correction_Control_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('fe2bf110-52eb-5226-ac64-450dbe323d10'::uuid, '02077d4a-d2a0-5488-9c2b-23b258fe5068'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M04_EXPRESS_Rework_Priority_and_Coordination_Plan_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M04_EXPRESS_Rework_Priority_and_Coordination_Plan_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M04_EXPRESS_Rework_Priority_and_Coordination_Plan_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('b30560a9-4f11-574c-8a27-f1ff09162015'::uuid, 'bc004d35-caa9-50c5-a6b7-01008efe047d'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M04_EVOLVE_Step-Up_Rework_Coordination_Plan_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M04_EVOLVE_Step-Up_Rework_Coordination_Plan_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M04_EVOLVE_Step-Up_Rework_Coordination_Plan_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('3af88d89-b6bd-5853-92f5-bb16ce135cf4'::uuid, 'ce789253-5bbd-5dbd-b9b6-a7565c71daab'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M05_EXPRESS_Integrated_Appraisal_Support_Quality_and_Optimisation_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M05_EXPRESS_Integrated_Appraisal_Support_Quality_and_Optimisation_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M05_EXPRESS_Integrated_Appraisal_Support_Quality_and_Optimisation_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('1951f100-dda1-5af0-af66-363807def2d4'::uuid, '8d3db777-27ab-575f-aa4f-c9a414992639'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M05_EVOLVE_Step-Up_Integrated_Reviewer-Support_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M05_EVOLVE_Step-Up_Integrated_Reviewer-Support_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M05_EVOLVE_Step-Up_Integrated_Reviewer-Support_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('7ed98c6e-2f48-5bad-9656-7b7e526b4e36'::uuid, '4fc5d513-9b29-50ea-b83b-739c32bd86b5'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M06_EXPRESS_Final_L4_Integrated_Quality_Portfolio_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M06_EXPRESS_Final_L4_Integrated_Quality_Portfolio_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M06_EXPRESS_Final_L4_Integrated_Quality_Portfolio_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('f4a2c62d-2b41-5bd2-8541-48f440fcbdbe'::uuid, 'd03d0e33-1f00-58d5-b4ab-6acb67cff383'::uuid, 1, 'Complete: CAP-CREDIT-001_L4_M06_EVOLVE_Independent_Integrated_Quality_Transfer_Defence_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L4_M06_EVOLVE_Independent_Integrated_Quality_Transfer_Defence_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L4_M06_EVOLVE_Independent_Integrated_Quality_Transfer_Defence_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('484ed483-ec52-5a80-9623-353f0fee847c'::uuid, '30e3c18d-1597-5e93-859d-7e5bb488b5d7'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M00_EXPRESS_Workflow_Governance_Readiness_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M00_EXPRESS_Workflow_Governance_Readiness_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M00_EXPRESS_Workflow_Governance_Readiness_Map_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('3d84179f-1a07-5c94-910e-79d23f424ef3'::uuid, 'de8f90d1-c853-50b1-816e-65f6efdea6a7'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M00_EVOLVE_Step-Up_Governance_Readiness_Check_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M00_EVOLVE_Step-Up_Governance_Readiness_Check_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M00_EVOLVE_Step-Up_Governance_Readiness_Check_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('099ac822-a1bc-5515-9688-9d714be9e06f'::uuid, '58ebc6e0-0388-5b99-a195-ac1fbef96a8e'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M01_EXPRESS_Queue_Readiness_and_SLA_Dashboard_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M01_EXPRESS_Queue_Readiness_and_SLA_Dashboard_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M01_EXPRESS_Queue_Readiness_and_SLA_Dashboard_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('95e7fc91-5e5a-52ec-a3af-fb207b9c8076'::uuid, '11f3c2ae-7ece-574f-8cc8-e22f78c7684f'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M01_EVOLVE_Step-Up_Queue_Readiness_Dashboard_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M01_EVOLVE_Step-Up_Queue_Readiness_Dashboard_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M01_EVOLVE_Step-Up_Queue_Readiness_Dashboard_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('cb29ff7b-544b-5b40-862d-dd26593a8eba'::uuid, '67e53b60-2388-5714-9438-aaf63f92b788'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M02_EXPRESS_Recurring_Defect_and_Evidence-Readiness_Analysis_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M02_EXPRESS_Recurring_Defect_and_Evidence-Readiness_Analysis_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M02_EXPRESS_Recurring_Defect_and_Evidence-Readiness_Analysis_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('5c3138ae-7535-5d31-92c7-f4826711f0df'::uuid, '489f0199-b5a1-531b-8cbe-27b6a8664f0f'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M02_EVOLVE_Step-Up_Defect_Trend_Analysis_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M02_EVOLVE_Step-Up_Defect_Trend_Analysis_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M02_EVOLVE_Step-Up_Defect_Trend_Analysis_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('f6bf3455-6d9b-55f8-a7f8-6dba6a51a3e5'::uuid, '6ae0d9d1-6605-590a-a9e8-1c21623bbb22'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M03_EXPRESS_Junior_Work_Review_and_Coaching_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M03_EXPRESS_Junior_Work_Review_and_Coaching_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M03_EXPRESS_Junior_Work_Review_and_Coaching_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('f8650720-20b3-5d79-bf13-42d43e5d498a'::uuid, 'b2313b0d-4951-538d-ba98-57ead7140e8c'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M03_EVOLVE_Step-Up_Coaching_and_Rework_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M03_EVOLVE_Step-Up_Coaching_and_Rework_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M03_EVOLVE_Step-Up_Coaching_and_Rework_Log_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('5c0b8102-1033-5781-800f-b3f891052fc1'::uuid, 'df6149f8-fd9f-516d-aae6-0d0dc1e24d67'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M04_EXPRESS_Template_and_Workflow_Control_Improvement_Proposal_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M04_EXPRESS_Template_and_Workflow_Control_Improvement_Proposal_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M04_EXPRESS_Template_and_Workflow_Control_Improvement_Proposal_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('6d948d2b-4e75-5f8f-95a7-92c5cc785dc0'::uuid, 'd15a566f-f750-5bf8-b28d-c463764abd01'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M04_EVOLVE_Step-Up_Control_Improvement_Proposal_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M04_EVOLVE_Step-Up_Control_Improvement_Proposal_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M04_EVOLVE_Step-Up_Control_Improvement_Proposal_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('22a6dd2c-869a-50e3-a619-3ce02c041f74'::uuid, '11490ea7-9394-53bf-82d1-8abadb9c3da1'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M05_EXPRESS_Credit_Support_Governance_Summary_and_Handoff_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M05_EXPRESS_Credit_Support_Governance_Summary_and_Handoff_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M05_EXPRESS_Credit_Support_Governance_Summary_and_Handoff_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('fb461acf-d432-537a-83f7-77422957874b'::uuid, '1ad51af0-b260-5123-982c-ff460be8661e'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M05_EVOLVE_Step-Up_Governance_Handoff_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M05_EVOLVE_Step-Up_Governance_Handoff_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M05_EVOLVE_Step-Up_Governance_Handoff_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('bcbc9644-4d90-5db4-a0e1-82b8f59f7b73'::uuid, '1cb05d5d-df3a-5906-8916-7174a7eefc38'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M06_EXPRESS_Final_L5_Workflow_Governance_Portfolio_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EXPRESS artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M06_EXPRESS_Final_L5_Workflow_Governance_Portfolio_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M06_EXPRESS_Final_L5_Workflow_Governance_Portfolio_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "response_type", "allowed_file_types", "max_file_size_mb", "response_required", "is_active")
VALUES ('b8467356-a9fb-5f86-8f34-f2dfd0378db5'::uuid, 'dda4f0b2-4c6c-599a-821d-e4a45270a3a4'::uuid, 1, 'Complete: CAP-CREDIT-001_L5_M06_EVOLVE_Independent_Workflow_Governance_Transfer_Defence_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx', 'Complete the exact EVOLVE artifact workbook supplied in Google Drive: CAP-CREDIT-001_L5_M06_EVOLVE_Independent_Workflow_Governance_Transfer_Defence_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx.', '{"required_fields":"Use the exact structure in the supplied Google Drive workbook: CAP-CREDIT-001_L5_M06_EVOLVE_Independent_Workflow_Governance_Transfer_Defence_Pack_OWNER_REVIEWED_CONTROLLED_RELEASE.xlsx. Do not substitute a generic template.","pass_criteria":"Complete the supplied workbook accurately, keep evidence traceable, preserve unresolved items, and stay within the stated credit-support authority boundary.","critical_fail":"No approval, rejection, pricing, sanction, waiver, eligibility decision, risk acceptance, policy override, or other authority outside the stated course role."}'::jsonb, 'file', ARRAY['xlsx']::text[], 20, TRUE, TRUE)
ON CONFLICT DO NOTHING;

COMMIT;
