-- Generated from LTE_LEARNING_CATALOG_CIE_CAP_003_LINKS_COMPLETE.xlsx: public.skills.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.skills
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('f07f2b0a-31b4-5257-9eea-d17436a53ead'::uuid, 'CIE_CAP003_L1_SK_M00', 'Recognise Project Controls Context and Role Boundaries', 'Learner can Identify role scope and readiness requirements for a project-controls case. Technical focus: Recognize baseline schedule, WBS, dashboard, tracker, and evidence-index objects. Cognitive focus: Separate role facts from assumptions and predict downstream risk of weak intake. Communication: State what the learner can and cannot hand off in clear support-role language. Evidence skill: Confirm evidence pack contents, missing supervisor note, and RA-17 owner gap.', '["Construction / infrastructure project-controls support and authority boundary.", "Identify role scope and readiness requirements for a project-controls case.", "Recognize baseline schedule, WBS, dashboard, tracker, and evidence-index objects.", "Confirm evidence pack contents, missing supervisor note, and RA-17 owner gap."]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('941e0186-296a-5fc4-93ef-72f6d90dea93'::uuid, 'CIE_CAP003_L1_SK_M01', 'Frame an L1 Progress-Control Case', 'Learner can Intake the work object, trigger, package constraint, stakeholder, and missing owner. Technical focus: Read WBS 03.04, Activity A-314, planned finish, and planned progress from baseline snapshot. Cognitive focus: Classify confirmed facts versus unvalidated actual progress. Communication: Write an intake note that flags missing owner without blaming a stakeholder. Evidence skill: Extract planned 70 percent, review deadline, and owner blank without inventing actual progress.', '["Weekly progress reporting and client review preparation.", "Intake the work object, trigger, package constraint, stakeholder, and missing owner.", "Read WBS 03.04, Activity A-314, planned finish, and planned progress from baseline snapshot.", "Extract planned 70 percent, review deadline, and owner blank without inventing actual progress."]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('89b41360-a0d3-5609-bc6c-6ff792779e85'::uuid, 'CIE_CAP003_L1_SK_M02', 'Validate L1 Progress and Schedule Evidence', 'Learner can Validate evidence readiness before dashboard release. Technical focus: Compare dashboard 62/65, baseline 70, daily actual 48, float -2, and blank source link. Cognitive focus: Detect conflicting evidence and decide safe next action. Communication: Ask reviewer question that is precise enough for planning engineer action. Evidence skill: Mark dashboard Needs Review and cite exact mismatch values.', '["Progress-control evidence sufficiency for infrastructure review packs.", "Validate evidence readiness before dashboard release.", "Compare dashboard 62/65, baseline 70, daily actual 48, float -2, and blank source link.", "Mark dashboard Needs Review and cite exact mismatch values."]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('f031a1c8-af9c-5d0d-8740-9b79a30b91c1'::uuid, 'CIE_CAP003_L1_SK_M03', 'Prepare an Evidence-Based L1 Action Handoff', 'Learner can Prepare safe action or handoff note for variance and recovery review. Technical focus: Interpret delay note, critical-path movement, and RA-17 draft tracker. Cognitive focus: Connect delay drivers to float movement and owner gap. Communication: Write handoff note with evidence basis and planning review request. Evidence skill: Cite access delay, PO-RB-447 late receipt, -2 float, and RA-17 owner blank.', '["Delay signal and recovery action handoff in project controls.", "Prepare safe action or handoff note for variance and recovery review.", "Interpret delay note, critical-path movement, and RA-17 draft tracker.", "Cite access delay, PO-RB-447 late receipt, -2 float, and RA-17 owner blank."]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('eae485f7-8575-5285-9930-d31b0ef33375'::uuid, 'CIE_CAP003_L1_SK_M04', 'Identify L1 Risks, Blockers and Escalations', 'Learner can Escalate blocker with owner, due date, evidence, risk, and consequence. Technical focus: Read procurement tracker, GRN status, site access permit timing, and QA walkthrough status. Cognitive focus: Distinguish arrival from readiness and access from work resumption. Communication: Route escalation to planning engineer with procurement/site evidence attached. Evidence skill: Attach PO-RB-447 due/received dates, GRN pending, permit reopen time, and QA pending.', '["Procurement/access interface risk in construction progress recovery.", "Escalate blocker with owner, due date, evidence, risk, and consequence.", "Read procurement tracker, GRN status, site access permit timing, and QA walkthrough status.", "Attach PO-RB-447 due/received dates, GRN pending, permit reopen time, and QA pending."]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('7a7769f1-7f7b-565b-bb3a-d7999b3c3e5d'::uuid, 'CIE_CAP003_L1_SK_M05', 'Quality-Review and Close L1 Progress-Control Work', 'Learner can Quality-check handoff communication and closure report. Technical focus: Trace missing evidence attachment, owner gap, float note, and unsupported client-ready wording. Cognitive focus: Evaluate whether communication is supported by source evidence. Communication: Rewrite closure as Pending Planning Engineer Review with precise open risks. Evidence skill: Include E-M2-02, E-M3-02, E-M4-02, E-M4-03, and supervisor comment.', '["Quality closure and review readiness in progress reporting.", "Quality-check handoff communication and closure report.", "Trace missing evidence attachment, owner gap, float note, and unsupported client-ready wording.", "Include E-M2-02, E-M3-02, E-M4-02, E-M4-03, and supervisor comment."]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('f16ed2bb-e932-5919-b8c3-551efebbcde1'::uuid, 'CIE_CAP003_L1_SK_M06', 'Transfer and Demonstrate L1 Progress-Control Capability', 'Learner can Compile final portfolio and transfer method to a second package. Technical focus: Check artifact chain, retry proof, transfer mini-case variance, and baseline approval trap. Cognitive focus: Transfer method from HN-24A to HN24B while preserving role boundary. Communication: Explain portfolio evidence and reviewer questions without claiming final approval. Evidence skill: Show seven artifacts, evidence index, M5 retry proof, and transfer boundary defense.', '["Certification evidence for L1 project-controls support capability.", "Compile final portfolio and transfer method to a second package.", "Check artifact chain, retry proof, transfer mini-case variance, and baseline approval trap.", "Show seven artifacts, evidence index, M5 retry proof, and transfer boundary defense."]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('4c5c0c36-2482-5127-b8ba-4ed7c75d4ced'::uuid, 'CIE_CAP003_L2_SK_M00', 'Diagnose L2 Progress-Control Readiness', 'At L2, the learner can Recognise the course problem and artifact chain in a independent operational application context. Knowledge: Capability, workplace context, level boundary, evidence landscape. Cognitive demand: Orient and diagnose readiness. Communication: State role and uncertainty clearly. Evidence: Readiness / orientation artifact.', '["Capability, workplace context, level boundary, evidence landscape", "Recognise the course problem and artifact chain", "Orient and diagnose readiness"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('be7c2bce-1791-5e1f-9197-7619ff85e650'::uuid, 'CIE_CAP003_L2_SK_M01', 'Frame a Routine Progress-Control Case Independently', 'At L2, the learner can Frame the case and intake in a independent operational application context. Knowledge: Case, work object, trigger, decision rights, known/unknown. Cognitive demand: Separate fact, assumption and gap. Communication: Clarify scope and route unresolved issues. Evidence: Intake artifact.', '["Case, work object, trigger, decision rights, known/unknown", "Frame the case and intake", "Separate fact, assumption and gap"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('0792ecc1-d807-5a67-9545-d627a4fdb532'::uuid, 'CIE_CAP003_L2_SK_M02', 'Validate Routine Multi-Source Progress Evidence', 'At L2, the learner can Validate level-appropriate evidence in a independent operational application context. Knowledge: Evidence relevance, currency, traceability, consistency. Cognitive demand: Compare, reconcile or judge uncertainty. Communication: Explain what evidence supports and what remains unresolved. Evidence: Evidence validation artifact.', '["Evidence relevance, currency, traceability, consistency", "Validate level-appropriate evidence", "Compare, reconcile or judge uncertainty"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('9f57ec11-264e-5283-b1c3-f55758ff8094'::uuid, 'CIE_CAP003_L2_SK_M03', 'Update Routine Progress Controls and Complete Handoff', 'At L2, the learner can Create the main level-matched output in a independent operational application context. Knowledge: Action / recommendation / integrated option / governance direction. Cognitive demand: Use approved decision verb and evidence. Communication: Write a clear handoff, rationale or direction statement. Evidence: Core action artifact.', '["Action / recommendation / integrated option / governance direction", "Create the main level-matched output", "Use approved decision verb and evidence"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('550a8efd-bc4f-51a3-94cd-bee9aae959ee'::uuid, 'CIE_CAP003_L2_SK_M04', 'Control Routine Exceptions and Escalations', 'At L2, the learner can Control exceptions at the correct level in a independent operational application context. Knowledge: Exception trigger, risk, escalation, ownership. Cognitive demand: Assess significance and escalation condition. Communication: State consequence, owner/forum and request. Evidence: Exception / escalation artifact.', '["Exception trigger, risk, escalation, ownership", "Control exceptions at the correct level", "Assess significance and escalation condition"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('f1c38b26-49f1-530f-b231-44c0e6d86a46'::uuid, 'CIE_CAP003_L2_SK_M05', 'Independently Quality-Check and Close Routine Progress-Control Work', 'At L2, the learner can Quality-check and correct the output in a independent operational application context. Knowledge: Quality criteria, communication, assurance, closure. Cognitive demand: Identify material weaknesses independently. Communication: Produce reviewer-ready closure / assurance language. Evidence: Quality / closure artifact.', '["Quality criteria, communication, assurance, closure", "Quality-check and correct the output", "Identify material weaknesses independently"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('d0f77de7-c122-5e34-8539-1fac6c4b96d0'::uuid, 'CIE_CAP003_L2_SK_M06', 'Transfer and Demonstrate L2 Operational Progress-Control Capability', 'At L2, the learner can Transfer method and assemble final proof in a independent operational application context. Knowledge: Portfolio chain, transfer, reflection, final validation. Cognitive demand: Adapt to new context at the same level. Communication: Defend decision, boundaries and next review. Evidence: Portfolio / final framework.', '["Portfolio chain, transfer, reflection, final validation", "Transfer method and assemble final proof", "Adapt to new context at the same level"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('4a74e0da-ad40-5b6a-8e50-0dbca41123a5'::uuid, 'CIE_CAP003_L3_SK_M00', 'Diagnose L3 Decision Readiness', 'At L3, the learner can Recognise the course problem and artifact chain in a analysis, judgement and decision-making context. Knowledge: Capability, workplace context, level boundary, evidence landscape. Cognitive demand: Orient and diagnose readiness. Communication: State role and uncertainty clearly. Evidence: Readiness / orientation artifact.', '["Capability, workplace context, level boundary, evidence landscape", "Recognise the course problem and artifact chain", "Orient and diagnose readiness"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('6aebb88d-2430-5c0c-a490-fb636aba69dd'::uuid, 'CIE_CAP003_L3_SK_M01', 'Frame a Non-Routine Progress-Control Case and Decision Boundary', 'At L3, the learner can Frame the case and intake in a analysis, judgement and decision-making context. Knowledge: Case, work object, trigger, decision rights, known/unknown. Cognitive demand: Separate fact, assumption and gap. Communication: Clarify scope and route unresolved issues. Evidence: Intake artifact.', '["Case, work object, trigger, decision rights, known/unknown", "Frame the case and intake", "Separate fact, assumption and gap"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('f4a3e54d-363c-5fa7-89a8-c08867187008'::uuid, 'CIE_CAP003_L3_SK_M02', 'Reconcile Incomplete or Conflicting Linked Evidence', 'At L3, the learner can Validate level-appropriate evidence in a analysis, judgement and decision-making context. Knowledge: Evidence relevance, currency, traceability, consistency. Cognitive demand: Compare, reconcile or judge uncertainty. Communication: Explain what evidence supports and what remains unresolved. Evidence: Evidence validation artifact.', '["Evidence relevance, currency, traceability, consistency", "Validate level-appropriate evidence", "Compare, reconcile or judge uncertainty"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('20a0ba7d-b7d7-5c72-bf54-8a84957259bb'::uuid, 'CIE_CAP003_L3_SK_M03', 'Develop a Progress Variance and Recovery Recommendation', 'At L3, the learner can Create the main level-matched output in a analysis, judgement and decision-making context. Knowledge: Action / recommendation / integrated option / governance direction. Cognitive demand: Use approved decision verb and evidence. Communication: Write a clear handoff, rationale or direction statement. Evidence: Core action artifact.', '["Action / recommendation / integrated option / governance direction", "Create the main level-matched output", "Use approved decision verb and evidence"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('ccfe9c8b-cc82-53a2-9344-d85d825b17a4'::uuid, 'CIE_CAP003_L3_SK_M04', 'Justify Exception and Escalation Decisions', 'At L3, the learner can Control exceptions at the correct level in a analysis, judgement and decision-making context. Knowledge: Exception trigger, risk, escalation, ownership. Cognitive demand: Assess significance and escalation condition. Communication: State consequence, owner/forum and request. Evidence: Exception / escalation artifact.', '["Exception trigger, risk, escalation, ownership", "Control exceptions at the correct level", "Assess significance and escalation condition"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('339b0ab5-5252-5baa-9ba4-47d5e169f007'::uuid, 'CIE_CAP003_L3_SK_M05', 'Quality-Check and Defend a Progress-Recovery Recommendation', 'At L3, the learner can Quality-check and correct the output in a analysis, judgement and decision-making context. Knowledge: Quality criteria, communication, assurance, closure. Cognitive demand: Identify material weaknesses independently. Communication: Produce reviewer-ready closure / assurance language. Evidence: Quality / closure artifact.', '["Quality criteria, communication, assurance, closure", "Quality-check and correct the output", "Identify material weaknesses independently"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('80d29452-58b5-5ce3-99dc-eca4f17a3cdb'::uuid, 'CIE_CAP003_L3_SK_M06', 'Transfer and Demonstrate L3 Analytical Progress-Control Capability', 'At L3, the learner can Transfer method and assemble final proof in a analysis, judgement and decision-making context. Knowledge: Portfolio chain, transfer, reflection, final validation. Cognitive demand: Adapt to new context at the same level. Communication: Defend decision, boundaries and next review. Evidence: Portfolio / final framework.', '["Portfolio chain, transfer, reflection, final validation", "Transfer method and assemble final proof", "Adapt to new context at the same level"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('6496c8ac-84cd-544a-9a44-b12eb808353e'::uuid, 'CIE_CAP003_L4_SK_M00', 'Diagnose Integrated Recovery-Control Readiness', 'At L4, the learner can Recognise the course problem and artifact chain in a integration, optimisation and cross-functional leadership context. Knowledge: Capability, workplace context, level boundary, evidence landscape. Cognitive demand: Orient and diagnose readiness. Communication: State role and uncertainty clearly. Evidence: Readiness / orientation artifact.', '["Capability, workplace context, level boundary, evidence landscape", "Recognise the course problem and artifact chain", "Orient and diagnose readiness"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('db6c143c-f905-5ee5-bcc8-9fce85e1b493'::uuid, 'CIE_CAP003_L4_SK_M01', 'Frame Cross-Functional Recovery-Control Boundaries', 'At L4, the learner can Frame the case and intake in a integration, optimisation and cross-functional leadership context. Knowledge: Case, work object, trigger, decision rights, known/unknown. Cognitive demand: Separate fact, assumption and gap. Communication: Clarify scope and route unresolved issues. Evidence: Intake artifact.', '["Case, work object, trigger, decision rights, known/unknown", "Frame the case and intake", "Separate fact, assumption and gap"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('58a4a91b-b081-5ba5-9129-3750fd2cd223'::uuid, 'CIE_CAP003_L4_SK_M02', 'Validate Integrated Cross-Functional Progress Evidence', 'At L4, the learner can Validate level-appropriate evidence in a integration, optimisation and cross-functional leadership context. Knowledge: Evidence relevance, currency, traceability, consistency. Cognitive demand: Compare, reconcile or judge uncertainty. Communication: Explain what evidence supports and what remains unresolved. Evidence: Evidence validation artifact.', '["Evidence relevance, currency, traceability, consistency", "Validate level-appropriate evidence", "Compare, reconcile or judge uncertainty"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('4deb3e71-6995-5675-aece-049c641e1dab'::uuid, 'CIE_CAP003_L4_SK_M03', 'Coordinate an Integrated Recovery Action and Handoff', 'At L4, the learner can Create the main level-matched output in a integration, optimisation and cross-functional leadership context. Knowledge: Action / recommendation / integrated option / governance direction. Cognitive demand: Use approved decision verb and evidence. Communication: Write a clear handoff, rationale or direction statement. Evidence: Core action artifact.', '["Action / recommendation / integrated option / governance direction", "Create the main level-matched output", "Use approved decision verb and evidence"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('aa6e7fc8-5b31-5d6b-a121-a72dbbf76051'::uuid, 'CIE_CAP003_L4_SK_M04', 'Control Cross-Functional Exceptions and Recovery Trade-offs', 'At L4, the learner can Control exceptions at the correct level in a integration, optimisation and cross-functional leadership context. Knowledge: Exception trigger, risk, escalation, ownership. Cognitive demand: Assess significance and escalation condition. Communication: State consequence, owner/forum and request. Evidence: Exception / escalation artifact.', '["Exception trigger, risk, escalation, ownership", "Control exceptions at the correct level", "Assess significance and escalation condition"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('7bc2feeb-aa19-5234-9965-696ad109f49a'::uuid, 'CIE_CAP003_L4_SK_M05', 'Assure Integrated Recovery Quality and Closure', 'At L4, the learner can Quality-check and correct the output in a integration, optimisation and cross-functional leadership context. Knowledge: Quality criteria, communication, assurance, closure. Cognitive demand: Identify material weaknesses independently. Communication: Produce reviewer-ready closure / assurance language. Evidence: Quality / closure artifact.', '["Quality criteria, communication, assurance, closure", "Quality-check and correct the output", "Identify material weaknesses independently"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('53b58824-9ec5-50e0-9dee-09bde18a423a'::uuid, 'CIE_CAP003_L4_SK_M06', 'Transfer and Demonstrate L4 Integrated Project-Control Leadership', 'At L4, the learner can Transfer method and assemble final proof in a integration, optimisation and cross-functional leadership context. Knowledge: Portfolio chain, transfer, reflection, final validation. Cognitive demand: Adapt to new context at the same level. Communication: Defend decision, boundaries and next review. Evidence: Portfolio / final framework.', '["Portfolio chain, transfer, reflection, final validation", "Transfer method and assemble final proof", "Adapt to new context at the same level"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('59c14fb5-0bda-5f60-92a9-a5a6ef5eb78c'::uuid, 'CIE_CAP003_L5_SK_M00', 'Diagnose Enterprise Progress-Governance Readiness', 'At L5, the learner can Recognise the course problem and artifact chain in a strategy, governance and transformation context. Knowledge: Capability, workplace context, level boundary, evidence landscape. Cognitive demand: Orient and diagnose readiness. Communication: State role and uncertainty clearly. Evidence: Readiness / orientation artifact.', '["Capability, workplace context, level boundary, evidence landscape", "Recognise the course problem and artifact chain", "Orient and diagnose readiness"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('72319569-a0f7-5c72-8fd0-fb5d819d2112'::uuid, 'CIE_CAP003_L5_SK_M01', 'Define Enterprise Governance Intake and Decision Rights', 'At L5, the learner can Frame the case and intake in a strategy, governance and transformation context. Knowledge: Case, work object, trigger, decision rights, known/unknown. Cognitive demand: Separate fact, assumption and gap. Communication: Clarify scope and route unresolved issues. Evidence: Intake artifact.', '["Case, work object, trigger, decision rights, known/unknown", "Frame the case and intake", "Separate fact, assumption and gap"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('32e7f364-294d-54de-8476-eef6eabd793f'::uuid, 'CIE_CAP003_L5_SK_M02', 'Set Enterprise Progress Evidence and Assurance Standards', 'At L5, the learner can Validate level-appropriate evidence in a strategy, governance and transformation context. Knowledge: Evidence relevance, currency, traceability, consistency. Cognitive demand: Compare, reconcile or judge uncertainty. Communication: Explain what evidence supports and what remains unresolved. Evidence: Evidence validation artifact.', '["Evidence relevance, currency, traceability, consistency", "Validate level-appropriate evidence", "Compare, reconcile or judge uncertainty"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('21c86829-1a85-5638-bdcf-e82bc7653643'::uuid, 'CIE_CAP003_L5_SK_M03', 'Develop Governance Direction and Transformation Options', 'At L5, the learner can Create the main level-matched output in a strategy, governance and transformation context. Knowledge: Action / recommendation / integrated option / governance direction. Cognitive demand: Use approved decision verb and evidence. Communication: Write a clear handoff, rationale or direction statement. Evidence: Core action artifact.', '["Action / recommendation / integrated option / governance direction", "Create the main level-matched output", "Use approved decision verb and evidence"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('a19cd5d4-4f3c-5ce2-bc33-ed06f7bcc43f'::uuid, 'CIE_CAP003_L5_SK_M04', 'Define Enterprise Risk Appetite, Exceptions and Escalation', 'At L5, the learner can Control exceptions at the correct level in a strategy, governance and transformation context. Knowledge: Exception trigger, risk, escalation, ownership. Cognitive demand: Assess significance and escalation condition. Communication: State consequence, owner/forum and request. Evidence: Exception / escalation artifact.', '["Exception trigger, risk, escalation, ownership", "Control exceptions at the correct level", "Assess significance and escalation condition"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('28375bef-5089-5621-8758-25ee8b3fa132'::uuid, 'CIE_CAP003_L5_SK_M05', 'Set Enterprise Assurance, Disclosure and Closure Protocols', 'At L5, the learner can Quality-check and correct the output in a strategy, governance and transformation context. Knowledge: Quality criteria, communication, assurance, closure. Cognitive demand: Identify material weaknesses independently. Communication: Produce reviewer-ready closure / assurance language. Evidence: Quality / closure artifact.', '["Quality criteria, communication, assurance, closure", "Quality-check and correct the output", "Identify material weaknesses independently"]'::jsonb)
ON CONFLICT DO NOTHING;
INSERT INTO public."skills" ("id", "code", "name", "description", "tags")
VALUES ('ff4cd878-3baa-5b4e-966b-45fd0b1aa21c'::uuid, 'CIE_CAP003_L5_SK_M06', 'Design and Defend an Enterprise Progress-Governance Transformation Framework', 'At L5, the learner can Transfer method and assemble final proof in a strategy, governance and transformation context. Knowledge: Portfolio chain, transfer, reflection, final validation. Cognitive demand: Adapt to new context at the same level. Communication: Defend decision, boundaries and next review. Evidence: Portfolio / final framework.', '["Portfolio chain, transfer, reflection, final validation", "Transfer method and assemble final proof", "Adapt to new context at the same level"]'::jsonb)
ON CONFLICT DO NOTHING;

COMMIT;
