-- Generated from LTE_LEARNING_CATALOG_TEMPLATE.xlsx: public.e_content.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.e_content
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('cb23266f-4088-522d-9fc7-26e36aa0e506'::uuid, '3d2baa17-5cf2-56e9-8cb4-750fd261c5da'::uuid, 'slide'::public.content_type, 'Engage: Industry, Role & Course Readiness', 'Show a guest arriving at 3:30 PM after travel while room status and payment/readiness are unclear.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-0/content/Guided_Guest_and_Visitor_Arrival_Readiness_01_Engage_SME_Fixed.pptx', 1, 150, NULL, 'application/octet-stream', 203157, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('904af095-8494-549e-a370-3721e7798ecb'::uuid, 'c8e1dfe1-a5ce-5c4d-9aa9-e6f47c9bb724'::uuid, 'slide'::public.content_type, 'Explore: Industry, Role & Course Readiness', 'Learner inspects reservation excerpt, room board, and SOP extract.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-0/content/Guided_Guest_and_Visitor_Arrival_Readiness_02_Explore_SME_Fixed.pptx', 2, 180, NULL, 'application/octet-stream', 388487, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('128f7c13-c87a-5be3-8182-401d4a676024'::uuid, '5d8d203d-43fb-5b4e-9a38-fb91eb728686'::uuid, 'slide'::public.content_type, 'Explain: Industry, Role & Course Readiness', 'Connect academic front-office concepts to evidence-backed arrival readiness and role authority.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-0/content/Guided_Guest_and_Visitor_Arrival_Readiness_03_Explain_SME_Fixed.pptx', 3, 240, NULL, 'application/octet-stream', 284628, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('70c3348d-9422-57c7-9927-160c3fbd812a'::uuid, 'b3fce0a2-ce90-50b2-bd9a-5e0544d4ba87'::uuid, 'slide'::public.content_type, 'Express: Industry, Role & Course Readiness', 'Learner drafts Course Readiness Sheet with evidence types, risks, boundaries, and one validation question.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-0/content/Guided_Guest_and_Visitor_Arrival_Readiness_04_Express_SME_Fixed.pptx', 4, 300, NULL, 'application/octet-stream', 187583, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('078bec1d-2363-5ff7-837d-9eec9cc5a892'::uuid, 'a5e99d26-62df-5c75-a853-413edfa22c70'::uuid, 'slide'::public.content_type, 'Empower: Industry, Role & Course Readiness', 'Learner chooses which risk must not be ignored and explains why L1 cannot approve.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-0/content/Guided_Guest_and_Visitor_Arrival_Readiness_05_Empower_SME_Fixed.pptx', 5, 180, NULL, 'application/octet-stream', 266053, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('5f03ce1d-61c4-5a6d-b1da-c45624b8ea13'::uuid, '275e3ab8-5c8b-5f17-87e6-49feed022545'::uuid, 'slide'::public.content_type, 'Evolve: Industry, Role & Course Readiness', 'Learner revises readiness sheet and carries risk/boundary/question to Module 1.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-0/content/Guided_Guest_and_Visitor_Arrival_Readiness_06_Evolve_SME_Fixed.pptx', 6, 150, NULL, 'application/octet-stream', 245446, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('ebe17747-d8f4-5c10-b019-63115f0a407b'::uuid, 'cd64ebbe-b9a3-5b7e-8cac-39a36f09feed'::uuid, 'slide'::public.content_type, 'Engage: Case Intake & Role Boundary', 'Guest says, "I already paid online and I am tired," creating pressure to act quickly.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-1/content/Module1_01_Engage_Case_Intake_Role_Boundary_FIXED.pptx', 1, 240, NULL, 'application/octet-stream', 155509, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('e753ae0c-1f06-517a-9143-bab29c901fbc'::uuid, '703383ca-a2c0-5543-bb3c-9fa612a7eb9a'::uuid, 'slide'::public.content_type, 'Explore: Case Intake & Role Boundary', 'Learner inspects reservation card, masked ID description, and PMS note.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-1/content/Module1_02_Explore_Inspect_Evidence_Pack_FIXED.pptx', 2, 360, NULL, 'application/octet-stream', 304657, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('a10b862d-2d8c-58c2-a1de-e615e249fb93'::uuid, '8526f8b6-9eef-58ba-8c6a-8b33d0ea4d60'::uuid, 'slide'::public.content_type, 'Explain: Case Intake & Role Boundary', 'Explain why front-office intake must separate visible evidence from guest statements and assumptions.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-1/content/Module1_03_Explain_Sort_Evidence_Safely_FIXED.pptx', 3, 420, NULL, 'application/octet-stream', 299890, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('09060727-d50e-509c-8dbc-a6f2895afdc6'::uuid, '1812dd59-483b-5b34-88d5-157b86fb3801'::uuid, 'slide'::public.content_type, 'Express: Case Intake & Role Boundary', 'Learner drafts Case Intake Note using evidence, assumptions, missing items, and clarification questions.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-1/content/Module1_04_Express_Role_Safe_Intake_Language_FIXED.pptx', 4, 600, NULL, 'application/octet-stream', 215121, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('7c711b8b-5465-547f-83db-8746e8f88236'::uuid, 'da47e5d0-9eb3-5a4e-b65e-63748fa38275'::uuid, 'slide'::public.content_type, 'Empower: Case Intake & Role Boundary', 'Learner chooses whether to proceed, clarify, hold, or escalate while staying inside L1 boundary.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-1/content/Module1_05_Empower_Build_Case_Intake_Note_FIXED.pptx', 5, 420, NULL, 'application/octet-stream', 280518, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('ac6ab27d-7825-5ca6-8647-4f74f0922113'::uuid, '1f71303a-3b95-572b-abf2-3e42ae033212'::uuid, 'slide'::public.content_type, 'Evolve: Case Intake & Role Boundary', 'Learner revises note and passes confirmed evidence/questions to validation.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-1/content/Module1_06_Evolve_Final_Intake_Challenge_Handoff_FIXED.pptx', 6, 360, NULL, 'application/octet-stream', 289151, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('26712e49-dc8e-5f7b-9d89-a837d6def08b'::uuid, 'f8d26cc1-48cd-5034-b55a-8d07c6df65fe'::uuid, 'slide'::public.content_type, 'Engage: Evidence / Requirement Validation', 'Learner sees mixed signals that look almost ready but still include blockers.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-2/content/Module2_01_Engage_Evidence_Validation_Matters_FIXED.pptx', 1, 300, NULL, 'application/octet-stream', 212005, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('1e2198ff-3124-5bd4-a5d3-63634c14aea9'::uuid, '055c6dbb-59a8-5cb8-a5ae-47d13a0eb18a'::uuid, 'slide'::public.content_type, 'Explore: Evidence / Requirement Validation', 'Learner compares room board, SOP extract, payment note, reservation, and ID description.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-2/content/Module2_02_Explore_Inspect_Evidence_Sources_FIXED.pptx', 2, 480, NULL, 'application/octet-stream', 389487, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('11f6c2fc-2bbe-5ac5-8819-04d212e40815'::uuid, 'ce5dfe89-bd1d-543e-9112-e2441354f17e'::uuid, 'slide'::public.content_type, 'Explain: Evidence / Requirement Validation', 'Explain validation categories and why each category changes what L1 can recommend.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-2/content/Module2_03_Explain_Validation_Labels_and_Owners_FIXED.pptx', 3, 540, NULL, 'application/octet-stream', 422189, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('c98b1f4e-a22b-5d04-9be6-9726b42a0ae2'::uuid, 'da000269-2331-5314-9195-61f407425ecd'::uuid, 'slide'::public.content_type, 'Express: Evidence / Requirement Validation', 'Learner completes Evidence Validation Checklist with status and evidence reason.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-2/content/Module2_04_Express_Safe_Validation_Questions_FIXED.pptx', 4, 780, NULL, 'application/octet-stream', 280122, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('78ee3032-1da2-5e48-852b-19d497e72a57'::uuid, 'cbc152c9-98b3-5316-a16a-2902f19aed65'::uuid, 'slide'::public.content_type, 'Empower: Evidence / Requirement Validation', 'Learner chooses safe validation status and explains blocker impact.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-2/content/Module2_05_Empower_Build_Evidence_Validation_Checklist_FIXED.pptx', 5, 480, NULL, 'application/octet-stream', 425015, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('c9918155-ae0b-59c6-a93b-6a0c98070baf'::uuid, '0cb9cfd3-c081-5475-9bbd-944de5e5a5b9'::uuid, 'slide'::public.content_type, 'Evolve: Evidence / Requirement Validation', 'Learner revises checklist and passes confirmed/risk/missing evidence to Module 3.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-2/content/Module2_06_Evolve_Final_Validation_Challenge_FIXED.pptx', 6, 420, NULL, 'application/octet-stream', 333311, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('15cd7d5b-3e51-5ffd-9ec7-d08c377a31f4'::uuid, '19473ea6-8c9c-5b9e-adab-4bb37d44e514'::uuid, 'slide'::public.content_type, 'Engage: Guided Work Action or Handoff', 'Learner must respond without keeping guest waiting or crossing authority.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-3/content/Module_3_PPT_1_Engage_SME_FIXED.pptx', 1, 240, NULL, 'application/octet-stream', 198545, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('ac1eabc9-b2dc-5073-92e8-ad647082e428'::uuid, 'c14444cb-ff62-5003-93f2-7734b92ef36c'::uuid, 'slide'::public.content_type, 'Explore: Guided Work Action or Handoff', 'Learner compares validation checklist, weak note, and key/access checklist.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-3/content/Module_3_PPT_2_Explore_SME_FIXED.pptx', 2, 360, NULL, 'application/octet-stream', 227510, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('88cb1f3a-88ec-535d-854e-948deb9877b0'::uuid, '295471fb-bc13-527b-9785-e06669f3a633'::uuid, 'slide'::public.content_type, 'Explain: Guided Work Action or Handoff', 'Explain why handoff quality depends on evidence, owner, blocker, and what L1 cannot do.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-3/content/Module_3_PPT_3_Explain_SME_FIXED.pptx', 3, 420, NULL, 'application/octet-stream', 264536, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('ef5f4fbf-b60f-5af8-adcd-ed69c5f4f633'::uuid, '1a4de1c0-6748-503c-b923-d4fbbe62134b'::uuid, 'slide'::public.content_type, 'Express: Guided Work Action or Handoff', 'Learner drafts Action or Handoff Note.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-3/content/Module_3_PPT_4_Express_SME_FIXED.pptx', 4, 600, NULL, 'application/octet-stream', 235240, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('aaaa4c10-b9b7-5869-9f74-96d395d25257'::uuid, 'faedcab8-16cc-5ac2-8719-4f2fe4f86e4f'::uuid, 'slide'::public.content_type, 'Empower: Guided Work Action or Handoff', 'Learner chooses safe recommendation and action-not-allowed statement.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-3/content/Module_3_PPT_5_Empower_SME_FIXED.pptx', 5, 420, NULL, 'application/octet-stream', 256987, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('16abcf5d-947d-5d17-a66d-b1030f3dd7e7'::uuid, '2a22b10b-6a77-53bd-af88-1f4df7b5476f'::uuid, 'slide'::public.content_type, 'Evolve: Guided Work Action or Handoff', 'Learner revises note and passes recommendation/risk/owner/action-not-allowed to Module 4.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-3/content/Module_3_PPT_6_Evolve_SME_FIXED.pptx', 6, 360, NULL, 'application/octet-stream', 229062, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('e1c885f6-ee06-596e-8560-ee2e39c9b5d6'::uuid, '2e91e4a4-6b9f-5a5b-bc01-8a9ab3c745d4'::uuid, 'slide'::public.content_type, 'Engage: Exceptions, Blockers, Risks & Escalations', 'Learner feels workplace pressure as guest waits and multiple blockers remain unresolved.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-4/content/Module_4_PPT_1_Engage_SME_FINAL_FIXED.pptx', 1, 300, NULL, 'application/octet-stream', 3709036, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('ae036f4d-30f3-55c8-9d3b-397b055c78e8'::uuid, '545ba836-22e1-5ccb-9605-07f110bab4a0'::uuid, 'slide'::public.content_type, 'Explore: Exceptions, Blockers, Risks & Escalations', 'Learner inspects handoff note, supervisor note, room-status update, and weak escalation draft.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-4/content/Module_4_PPT_2_Explore_SME_FINAL_FIXED.pptx', 2, 420, NULL, 'application/octet-stream', 1421281, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('7ca46829-afe2-5a0c-93e3-45c3f89cd330'::uuid, '909c8b2e-211b-50f3-ba0d-c2cd31414164'::uuid, 'slide'::public.content_type, 'Explain: Exceptions, Blockers, Risks & Escalations', 'Explain difference between issue, blocker, risk, owner, urgency, and safe next step.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-4/content/Module_4_PPT_3_Explain_SME_FINAL_FIXED.pptx', 3, 480, NULL, 'application/octet-stream', 1860851, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('5d9e9dd9-b5f4-5172-9b5c-50a07d5bed0d'::uuid, 'f39245a7-5594-57dc-8bb0-f6645a6f983d'::uuid, 'slide'::public.content_type, 'Express: Exceptions, Blockers, Risks & Escalations', 'Learner writes Risk and Escalation Note.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-4/content/Module_4_PPT_4_Express_SME_FINAL_FIXED.pptx', 4, 660, NULL, 'application/octet-stream', 1855302, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('c93a09ca-7eb4-5e07-8df8-9fd863db8b74'::uuid, 'c25fc2cc-a73b-5436-90ba-7cb90200a4cd'::uuid, 'slide'::public.content_type, 'Empower: Exceptions, Blockers, Risks & Escalations', 'Learner chooses correct escalation route and defends why L1 must not bypass blocker.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-4/content/Module_4_PPT_5_Empower_SME_FINAL_FIXED.pptx', 5, 480, NULL, 'application/octet-stream', 2025555, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('d5b38616-48c6-5299-901c-024dff564ed1'::uuid, '377f7d0a-1ef1-51a7-9d43-51253ea7fb24'::uuid, 'slide'::public.content_type, 'Evolve: Exceptions, Blockers, Risks & Escalations', 'Learner revises escalation note and passes risk/owner/safe next step to Module 5.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-4/content/Module_4_PPT_6_Evolve_SME_FINAL_FIXED.pptx', 6, 360, NULL, 'application/octet-stream', 1881098, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('8b01aa55-00cd-5fc4-8d00-5f7ec5d348b6'::uuid, 'd9e74c03-979d-50ab-afb1-d471b4277693'::uuid, 'slide'::public.content_type, 'Engage: Quality, Communication & Closure', 'Learner wants to complete the case but must avoid false closure.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-5/content/Module5_01_Engage_Owner_Follow_Up_Status_Tracking_FIXED.pptx', 1, 240, NULL, 'application/octet-stream', 196501, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('614a0aec-eb1b-5fa6-8408-d7d6fd56646f'::uuid, '73e34b31-e462-52a5-a43e-4fb50ac2af79'::uuid, 'slide'::public.content_type, 'Explore: Quality, Communication & Closure', 'Learner compares false closure note, responsible closure note, and final PMS note.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-5/content/Module5_02_Explore_Open_Items_Owner_Paths_FIXED.pptx', 2, 360, NULL, 'application/octet-stream', 283423, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('d722431f-6873-5cf6-aea8-873a4920d337'::uuid, '89c0df2d-a828-58ea-af1f-64890985276b'::uuid, 'slide'::public.content_type, 'Explain: Quality, Communication & Closure', 'Explain difference between L1 work completed, case unresolved, and access readiness not approved.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-5/content/Module5_03_Explain_Status_Labels_Delay_Visibility_FIXED.pptx', 3, 420, NULL, 'application/octet-stream', 294736, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('9ec1d5ae-2ee7-5e1a-90d9-25116779244a'::uuid, '62f14bd1-7495-5f8b-a806-00e2081fb5d5'::uuid, 'slide'::public.content_type, 'Express: Quality, Communication & Closure', 'Learner drafts Quality and Closure Report.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-5/content/Module5_04_Express_Safe_Guest_Status_Updates_FIXED.pptx', 4, 600, NULL, 'application/octet-stream', 228947, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('6aafa00b-4eab-55a4-b5d8-3d64c3ae7dec'::uuid, '8b1428a2-dcbc-502d-b036-493819744e56'::uuid, 'slide'::public.content_type, 'Empower: Quality, Communication & Closure', 'Learner chooses closure recommendation and remaining-risk communication.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-5/content/Module5_05_Empower_Build_Owner_Follow_Up_Tracker_FIXED.pptx', 5, 420, NULL, 'application/octet-stream', 262393, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('b836533e-c989-5275-b43d-3c61b8cda05c'::uuid, '5627e19e-9dea-5fb2-9bcb-18d82bcf0078'::uuid, 'slide'::public.content_type, 'Evolve: Quality, Communication & Closure', 'Learner revises closure report and passes portfolio proof to Module 6.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-5/content/Module5_06_Evolve_Final_Status_Tracking_Handoff_FIXED.pptx', 6, 360, NULL, 'application/octet-stream', 290170, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('336b9f6c-565d-56e6-9d58-75c147a76a01'::uuid, 'a139942f-6cae-592b-8362-78c36f3c447c'::uuid, 'slide'::public.content_type, 'Engage: Portfolio, Transfer & Final Validation', 'Learner sees that portfolio must prove how they think, not only what they filled.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-6/content/Module_6_PPT_1_Engage_SME_RELEASE_FIXED.pptx', 1, 360, NULL, 'application/octet-stream', 144410, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('aa9deb91-282c-550b-84d6-dd638ce0c5b6'::uuid, '44e19266-7aca-5be7-afe5-e5ae2135b76b'::uuid, 'slide'::public.content_type, 'Explore: Portfolio, Transfer & Final Validation', 'Learner reviews all prior artifacts and new visitor case evidence.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-6/content/Module_6_PPT_2_Explore_SME_RELEASE_FIXED.pptx', 2, 720, NULL, 'application/octet-stream', 176769, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('9e9534d3-6506-5d5f-ba23-ba30daed66c4'::uuid, '7c465d87-e8f1-5e10-bfe6-28e88d9967de'::uuid, 'slide'::public.content_type, 'Explain: Portfolio, Transfer & Final Validation', 'Explain transfer: same evidence-readiness method, different guest/visitor evidence and authority limits.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-6/content/Module_6_PPT_3_Explain_SME_RELEASE_FIXED.pptx', 3, 720, NULL, 'application/octet-stream', 174502, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('48fb498b-69b7-5eda-bcc3-166b31ee2138'::uuid, '43801986-7a75-58c2-8b17-70b45a7a32be'::uuid, 'slide'::public.content_type, 'Express: Portfolio, Transfer & Final Validation', 'Learner assembles Final Portfolio Pack and drafts decision defense.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-6/content/Module_6_PPT_4_Express_SME_RELEASE_FIXED.pptx', 4, 1500, NULL, 'application/octet-stream', 161426, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('c628c4fb-6192-5f0f-8314-b4999ba93592'::uuid, '6a34e716-8f9d-513a-aa0a-0fd662e0fc9d'::uuid, 'slide'::public.content_type, 'Empower: Portfolio, Transfer & Final Validation', 'Learner applies method to visitor case and defends safe escalation/role boundary.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-6/content/Module_6_PPT_5_Empower_SME_RELEASE_FIXED.pptx', 5, 900, NULL, 'application/octet-stream', 164025, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;
INSERT INTO public."e_content" ("id", "modules_content_id", "content_type", "title", "description", "url", "sort_order", "duration_seconds", "xp_reward", "mime_type", "file_size_bytes", "version", "status")
VALUES ('4190b757-93bc-5813-a4fa-d47025e268fc'::uuid, 'dba44b31-95f6-5e72-8119-cd6100bbd1b2'::uuid, 'slide'::public.content_type, 'Evolve: Portfolio, Transfer & Final Validation', 'Learner improves portfolio and identifies how to use the same method in future arrival-readiness work.', 'https://bucket.lte.rareminds.in/resources/capabilities/HTT-IND-CAP-01/courses/HTT_L1/modules-6/content/Module_6_PPT_6_Evolve_SME_RELEASE_FIXED.pptx', 6, 900, NULL, 'application/octet-stream', 163640, 1, 'draft'::public.content_publish_status)
ON CONFLICT DO NOTHING;

COMMIT;
