-- Generated from LTE_LEARNING_CATALOG_TEMPLATE.xlsx: public.modules_content.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.modules_content
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('3d2baa17-5cf2-56e9-8cb4-750fd261c5da'::uuid, '2e018b03-2663-5f67-8e6f-d1327b2894e2'::uuid, 'engage'::public.lte_6e_stage, 1, 'Show a guest arriving at 3:30 PM after travel while room status and payment/readiness are unclear.', 'At 3:30 PM, a tired guest is waiting near the front desk while the queue grows. The learner sees a reservation for Rohan Mehta, an early-arrival note, payment/readiness uncertainty, and a room that is not yet fully inspection-cleared. Before touching any check-in or access step, the learner must identify the course mission, L1 role boundary, tools, risks, and one open validation question.', '{"prerequisites": "None", "technical_concepts": "Front-Office Arrival Readiness; Evidence-Before-Action Principle; L1 Role Boundary in Guest/Visitor Readiness; Professional Readiness Mindset; Pause Before Promise; Service Value Awareness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner connects front-office arrival readiness to guest trust, room flow, payment/readiness safety, team workload, and L1 role boundaries before working the case.", "module_continuity": "Readiness sheet becomes the intake lens for the Rohan Mehta case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('c8e1dfe1-a5ce-5c4d-9aa9-e6f47c9bb724'::uuid, '2e018b03-2663-5f67-8e6f-d1327b2894e2'::uuid, 'explore'::public.lte_6e_stage, 2, 'Learner inspects reservation excerpt, room board, and SOP extract.', 'At 3:30 PM, a tired guest is waiting near the front desk while the queue grows. The learner sees a reservation for Rohan Mehta, an early-arrival note, payment/readiness uncertainty, and a room that is not yet fully inspection-cleared. Before touching any check-in or access step, the learner must identify the course mission, L1 role boundary, tools, risks, and one open validation question.', '{"prerequisites": "None", "technical_concepts": "Front-Office Arrival Readiness; Evidence-Before-Action Principle; L1 Role Boundary in Guest/Visitor Readiness; Professional Readiness Mindset; Pause Before Promise; Service Value Awareness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner connects front-office arrival readiness to guest trust, room flow, payment/readiness safety, team workload, and L1 role boundaries before working the case.", "module_continuity": "Readiness sheet becomes the intake lens for the Rohan Mehta case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('5d8d203d-43fb-5b4e-9a38-fb91eb728686'::uuid, '2e018b03-2663-5f67-8e6f-d1327b2894e2'::uuid, 'explain'::public.lte_6e_stage, 3, 'Connect academic front-office concepts to evidence-backed arrival readiness and role authority.', 'At 3:30 PM, a tired guest is waiting near the front desk while the queue+F4:G7 grows. The learner sees a reservation for Rohan Mehta, an early-arrival note, payment/readiness uncertainty, and a room that is not yet fully inspection-cleared. Before touching any check-in or access step, the learner must identify the course mission, L1 role boundary, tools, risks, and one open validation question.', '{"prerequisites": "None", "technical_concepts": "Front-Office Arrival Readiness; Evidence-Before-Action Principle; L1 Role Boundary in Guest/Visitor Readiness; Professional Readiness Mindset; Pause Before Promise; Service Value Awareness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner connects front-office arrival readiness to guest trust, room flow, payment/readiness safety, team workload, and L1 role boundaries before working the case.", "module_continuity": "Readiness sheet becomes the intake lens for the Rohan Mehta case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('b3fce0a2-ce90-50b2-bd9a-5e0544d4ba87'::uuid, '2e018b03-2663-5f67-8e6f-d1327b2894e2'::uuid, 'express'::public.lte_6e_stage, 4, 'Learner drafts Course Readiness Sheet with evidence types, risks, boundaries, and one validation question.', 'At 3:30 PM, a tired guest is waiting near the front desk while the queue grows. The learner sees a reservation for Rohan Mehta, an early-arrival note, payment/readiness uncertainty, and a room that is not yet fully inspection-cleared. Before touching any check-in or access step, the learner must identify the course mission, L1 role boundary, tools, risks, and one open validation question.', '{"prerequisites": "None", "technical_concepts": "Front-Office Arrival Readiness; Evidence-Before-Action Principle; L1 Role Boundary in Guest/Visitor Readiness; Professional Readiness Mindset; Pause Before Promise; Service Value Awareness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner connects front-office arrival readiness to guest trust, room flow, payment/readiness safety, team workload, and L1 role boundaries before working the case.", "module_continuity": "Readiness sheet becomes the intake lens for the Rohan Mehta case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('a5e99d26-62df-5c75-a853-413edfa22c70'::uuid, '2e018b03-2663-5f67-8e6f-d1327b2894e2'::uuid, 'empower'::public.lte_6e_stage, 5, 'Learner chooses which risk must not be ignored and explains why L1 cannot approve.', 'At 3:30 PM, a tired guest is waiting near the front desk while the queue grows. The learner sees a reservation for Rohan Mehta, an early-arrival note, payment/readiness uncertainty, and a room that is not yet fully inspection-cleared. Before touching any check-in or access step, the learner must identify the course mission, L1 role boundary, tools, risks, and one open validation question.', '{"prerequisites": "None", "technical_concepts": "Front-Office Arrival Readiness; Evidence-Before-Action Principle; L1 Role Boundary in Guest/Visitor Readiness; Professional Readiness Mindset; Pause Before Promise; Service Value Awareness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner connects front-office arrival readiness to guest trust, room flow, payment/readiness safety, team workload, and L1 role boundaries before working the case.", "module_continuity": "Readiness sheet becomes the intake lens for the Rohan Mehta case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('275e3ab8-5c8b-5f17-87e6-49feed022545'::uuid, '2e018b03-2663-5f67-8e6f-d1327b2894e2'::uuid, 'evolve'::public.lte_6e_stage, 6, 'Learner revises readiness sheet and carries risk/boundary/question to Module 1.', 'At 3:30 PM, a tired guest is waiting near the front desk while the queue grows. The learner sees a reservation for Rohan Mehta, an early-arrival note, payment/readiness uncertainty, and a room that is not yet fully inspection-cleared. Before touching any check-in or access step, the learner must identify the course mission, L1 role boundary, tools, risks, and one open validation question.', '{"prerequisites": "None", "technical_concepts": "Front-Office Arrival Readiness; Evidence-Before-Action Principle; L1 Role Boundary in Guest/Visitor Readiness; Professional Readiness Mindset; Pause Before Promise; Service Value Awareness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner connects front-office arrival readiness to guest trust, room flow, payment/readiness safety, team workload, and L1 role boundaries before working the case.", "module_continuity": "Readiness sheet becomes the intake lens for the Rohan Mehta case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('cd64ebbe-b9a3-5b7e-8cac-39a36f09feed'::uuid, 'df2d80be-e296-5bda-901e-0869b8f2491e'::uuid, 'engage'::public.lte_6e_stage, 1, 'Guest says, "I already paid online and I am tired," creating pressure to act quickly.', 'The learner receives the first case file. Reservation card shows guest name Rohan Mehta, OTA source, today arrival, early arrival requested. Masked ID evidence shows Rohan M. The guest says payment is complete. PMS note says payment hold pending. Room board says Room 412 clean - not inspected. Learner must separate facts, assumptions, missing information, and role boundary.', '{"prerequisites": "Course Readiness Sheet", "technical_concepts": "Arrival Evidence Mapping; Case Intake Sequencing; PMS / Front-Office Field Recognition; Active Listening for Arrival Evidence; Assumption Control; Calm Guest Greeting Under Pressure", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner opens the arrival case, separates facts from assumptions, identifies available/missing records, and protects L1 authority while preparing intake.", "module_continuity": "Case Intake Note feeds the Evidence Validation Checklist."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('703383ca-a2c0-5543-bb3c-9fa612a7eb9a'::uuid, 'df2d80be-e296-5bda-901e-0869b8f2491e'::uuid, 'explore'::public.lte_6e_stage, 2, 'Learner inspects reservation card, masked ID description, and PMS note.', 'The learner receives the first case file. Reservation card shows guest name Rohan Mehta, OTA source, today arrival, early arrival requested. Masked ID evidence shows Rohan M. The guest says payment is complete. PMS note says payment hold pending. Room board says Room 412 clean - not inspected. Learner must separate facts, assumptions, missing information, and role boundary.', '{"prerequisites": "Course Readiness Sheet", "technical_concepts": "Arrival Evidence Mapping; Case Intake Sequencing; PMS / Front-Office Field Recognition; Active Listening for Arrival Evidence; Assumption Control; Calm Guest Greeting Under Pressure", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner opens the arrival case, separates facts from assumptions, identifies available/missing records, and protects L1 authority while preparing intake.", "module_continuity": "Case Intake Note feeds the Evidence Validation Checklist."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('8526f8b6-9eef-58ba-8c6a-8b33d0ea4d60'::uuid, 'df2d80be-e296-5bda-901e-0869b8f2491e'::uuid, 'explain'::public.lte_6e_stage, 3, 'Explain why front-office intake must separate visible evidence from guest statements and assumptions.', 'The learner receives the first case file. Reservation card shows guest name Rohan Mehta, OTA source, today arrival, early arrival requested. Masked ID evidence shows Rohan M. The guest says payment is complete. PMS note says payment hold pending. Room board says Room 412 clean - not inspected. Learner must separate facts, assumptions, missing information, and role boundary.', '{"prerequisites": "Course Readiness Sheet", "technical_concepts": "Arrival Evidence Mapping; Case Intake Sequencing; PMS / Front-Office Field Recognition; Active Listening for Arrival Evidence; Assumption Control; Calm Guest Greeting Under Pressure", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner opens the arrival case, separates facts from assumptions, identifies available/missing records, and protects L1 authority while preparing intake.", "module_continuity": "Case Intake Note feeds the Evidence Validation Checklist."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('1812dd59-483b-5b34-88d5-157b86fb3801'::uuid, 'df2d80be-e296-5bda-901e-0869b8f2491e'::uuid, 'express'::public.lte_6e_stage, 4, 'Learner drafts Case Intake Note using evidence, assumptions, missing items, and clarification questions.', 'The learner receives the first case file. Reservation card shows guest name Rohan Mehta, OTA source, today arrival, early arrival requested. Masked ID evidence shows Rohan M. The guest says payment is complete. PMS note says payment hold pending. Room board says Room 412 clean - not inspected. Learner must separate facts, assumptions, missing information, and role boundary.', '{"prerequisites": "Course Readiness Sheet", "technical_concepts": "Arrival Evidence Mapping; Case Intake Sequencing; PMS / Front-Office Field Recognition; Active Listening for Arrival Evidence; Assumption Control; Calm Guest Greeting Under Pressure", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner opens the arrival case, separates facts from assumptions, identifies available/missing records, and protects L1 authority while preparing intake.", "module_continuity": "Case Intake Note feeds the Evidence Validation Checklist."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('da47e5d0-9eb3-5a4e-b65e-63748fa38275'::uuid, 'df2d80be-e296-5bda-901e-0869b8f2491e'::uuid, 'empower'::public.lte_6e_stage, 5, 'Learner chooses whether to proceed, clarify, hold, or escalate while staying inside L1 boundary.', 'The learner receives the first case file. Reservation card shows guest name Rohan Mehta, OTA source, today arrival, early arrival requested. Masked ID evidence shows Rohan M. The guest says payment is complete. PMS note says payment hold pending. Room board says Room 412 clean - not inspected. Learner must separate facts, assumptions, missing information, and role boundary.', '{"prerequisites": "Course Readiness Sheet", "technical_concepts": "Arrival Evidence Mapping; Case Intake Sequencing; PMS / Front-Office Field Recognition; Active Listening for Arrival Evidence; Assumption Control; Calm Guest Greeting Under Pressure", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner opens the arrival case, separates facts from assumptions, identifies available/missing records, and protects L1 authority while preparing intake.", "module_continuity": "Case Intake Note feeds the Evidence Validation Checklist."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('1f71303a-3b95-572b-abf2-3e42ae033212'::uuid, 'df2d80be-e296-5bda-901e-0869b8f2491e'::uuid, 'evolve'::public.lte_6e_stage, 6, 'Learner revises note and passes confirmed evidence/questions to validation.', 'The learner receives the first case file. Reservation card shows guest name Rohan Mehta, OTA source, today arrival, early arrival requested. Masked ID evidence shows Rohan M. The guest says payment is complete. PMS note says payment hold pending. Room board says Room 412 clean - not inspected. Learner must separate facts, assumptions, missing information, and role boundary.', '{"prerequisites": "Course Readiness Sheet", "technical_concepts": "Arrival Evidence Mapping; Case Intake Sequencing; PMS / Front-Office Field Recognition; Active Listening for Arrival Evidence; Assumption Control; Calm Guest Greeting Under Pressure", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner opens the arrival case, separates facts from assumptions, identifies available/missing records, and protects L1 authority while preparing intake.", "module_continuity": "Case Intake Note feeds the Evidence Validation Checklist."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('f8d26cc1-48cd-5034-b55a-8d07c6df65fe'::uuid, '6549115e-08da-53bb-a2d8-4c1f40cda084'::uuid, 'engage'::public.lte_6e_stage, 1, 'Learner sees mixed signals that look almost ready but still include blockers.', 'The learner must validate whether the case evidence is complete and usable. Reservation name Rohan Mehta and ID name Rohan M. may be a minor variation, but payment hold pending and Room 412 clean-not-inspected are blockers. Learner must mark each signal as match, minor variation, mismatch, missing, or hold/blocker.', '{"prerequisites": "Case Intake Note", "technical_concepts": "Reservation Status Validation; ID Matching and Mismatch Classification; Privacy-Safe Guest Record Handling; Room-Status and Payment Hold Validation; Polite Clarification; Confidence to Pause", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner validates whether reservation, identity, room-status, and payment/readiness evidence is complete, matching, missing, blocked, or requires supervisor review.", "module_continuity": "Validation checklist becomes the basis for the action/handoff note."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('055c6dbb-59a8-5cb8-a5ae-47d13a0eb18a'::uuid, '6549115e-08da-53bb-a2d8-4c1f40cda084'::uuid, 'explore'::public.lte_6e_stage, 2, 'Learner compares room board, SOP extract, payment note, reservation, and ID description.', 'The learner must validate whether the case evidence is complete and usable. Reservation name Rohan Mehta and ID name Rohan M. may be a minor variation, but payment hold pending and Room 412 clean-not-inspected are blockers. Learner must mark each signal as match, minor variation, mismatch, missing, or hold/blocker.', '{"prerequisites": "Case Intake Note", "technical_concepts": "Reservation Status Validation; ID Matching and Mismatch Classification; Privacy-Safe Guest Record Handling; Room-Status and Payment Hold Validation; Polite Clarification; Confidence to Pause", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner validates whether reservation, identity, room-status, and payment/readiness evidence is complete, matching, missing, blocked, or requires supervisor review.", "module_continuity": "Validation checklist becomes the basis for the action/handoff note."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('ce5dfe89-bd1d-543e-9112-e2441354f17e'::uuid, '6549115e-08da-53bb-a2d8-4c1f40cda084'::uuid, 'explain'::public.lte_6e_stage, 3, 'Explain validation categories and why each category changes what L1 can recommend.', 'The learner must validate whether the case evidence is complete and usable. Reservation name Rohan Mehta and ID name Rohan M. may be a minor variation, but payment hold pending and Room 412 clean-not-inspected are blockers. Learner must mark each signal as match, minor variation, mismatch, missing, or hold/blocker.', '{"prerequisites": "Case Intake Note", "technical_concepts": "Reservation Status Validation; ID Matching and Mismatch Classification; Privacy-Safe Guest Record Handling; Room-Status and Payment Hold Validation; Polite Clarification; Confidence to Pause", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner validates whether reservation, identity, room-status, and payment/readiness evidence is complete, matching, missing, blocked, or requires supervisor review.", "module_continuity": "Validation checklist becomes the basis for the action/handoff note."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('da000269-2331-5314-9195-61f407425ecd'::uuid, '6549115e-08da-53bb-a2d8-4c1f40cda084'::uuid, 'express'::public.lte_6e_stage, 4, 'Learner completes Evidence Validation Checklist with status and evidence reason.', 'The learner must validate whether the case evidence is complete and usable. Reservation name Rohan Mehta and ID name Rohan M. may be a minor variation, but payment hold pending and Room 412 clean-not-inspected are blockers. Learner must mark each signal as match, minor variation, mismatch, missing, or hold/blocker.', '{"prerequisites": "Case Intake Note", "technical_concepts": "Reservation Status Validation; ID Matching and Mismatch Classification; Privacy-Safe Guest Record Handling; Room-Status and Payment Hold Validation; Polite Clarification; Confidence to Pause", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner validates whether reservation, identity, room-status, and payment/readiness evidence is complete, matching, missing, blocked, or requires supervisor review.", "module_continuity": "Validation checklist becomes the basis for the action/handoff note."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('cbc152c9-98b3-5316-a16a-2902f19aed65'::uuid, '6549115e-08da-53bb-a2d8-4c1f40cda084'::uuid, 'empower'::public.lte_6e_stage, 5, 'Learner chooses safe validation status and explains blocker impact.', 'The learner must validate whether the case evidence is complete and usable. Reservation name Rohan Mehta and ID name Rohan M. may be a minor variation, but payment hold pending and Room 412 clean-not-inspected are blockers. Learner must mark each signal as match, minor variation, mismatch, missing, or hold/blocker.', '{"prerequisites": "Case Intake Note", "technical_concepts": "Reservation Status Validation; ID Matching and Mismatch Classification; Privacy-Safe Guest Record Handling; Room-Status and Payment Hold Validation; Polite Clarification; Confidence to Pause", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner validates whether reservation, identity, room-status, and payment/readiness evidence is complete, matching, missing, blocked, or requires supervisor review.", "module_continuity": "Validation checklist becomes the basis for the action/handoff note."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('0cb9cfd3-c081-5475-9bbd-944de5e5a5b9'::uuid, '6549115e-08da-53bb-a2d8-4c1f40cda084'::uuid, 'evolve'::public.lte_6e_stage, 6, 'Learner revises checklist and passes confirmed/risk/missing evidence to Module 3.', 'The learner must validate whether the case evidence is complete and usable. Reservation name Rohan Mehta and ID name Rohan M. may be a minor variation, but payment hold pending and Room 412 clean-not-inspected are blockers. Learner must mark each signal as match, minor variation, mismatch, missing, or hold/blocker.', '{"prerequisites": "Case Intake Note", "technical_concepts": "Reservation Status Validation; ID Matching and Mismatch Classification; Privacy-Safe Guest Record Handling; Room-Status and Payment Hold Validation; Polite Clarification; Confidence to Pause", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner validates whether reservation, identity, room-status, and payment/readiness evidence is complete, matching, missing, blocked, or requires supervisor review.", "module_continuity": "Validation checklist becomes the basis for the action/handoff note."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('19473ea6-8c9c-5b9e-adab-4bb37d44e514'::uuid, 'b6606c1e-a0fd-505f-ba6c-d96e07150bba'::uuid, 'engage'::public.lte_6e_stage, 1, 'Learner must respond without keeping guest waiting or crossing authority.', 'The learner has a completed validation checklist and must prepare a role-safe handoff note. The note must recommend supervisor review, show evidence, identify blockers, name owner, and state action not allowed for L1. Learner must not approve check-in or release key/access.', '{"prerequisites": "Evidence Validation Checklist", "technical_concepts": "Role-Safe Handoff Note Design; Recommendation vs Approval Language; Owner Routing for Arrival Handoff; Key/Access Handoff Boundary; Traceable Service Handoff Record; Accountability in Documentation", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner turns validated evidence into a role-safe recommendation or handoff without approving check-in or releasing access.", "module_continuity": "Handoff note provides the risk/owner/action-not-allowed context for escalation."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('c14444cb-ff62-5003-93f2-7734b92ef36c'::uuid, 'b6606c1e-a0fd-505f-ba6c-d96e07150bba'::uuid, 'explore'::public.lte_6e_stage, 2, 'Learner compares validation checklist, weak note, and key/access checklist.', 'The learner has a completed validation checklist and must prepare a role-safe handoff note. The note must recommend supervisor review, show evidence, identify blockers, name owner, and state action not allowed for L1. Learner must not approve check-in or release key/access.', '{"prerequisites": "Evidence Validation Checklist", "technical_concepts": "Role-Safe Handoff Note Design; Recommendation vs Approval Language; Owner Routing for Arrival Handoff; Key/Access Handoff Boundary; Traceable Service Handoff Record; Accountability in Documentation", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner turns validated evidence into a role-safe recommendation or handoff without approving check-in or releasing access.", "module_continuity": "Handoff note provides the risk/owner/action-not-allowed context for escalation."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('295471fb-bc13-527b-9785-e06669f3a633'::uuid, 'b6606c1e-a0fd-505f-ba6c-d96e07150bba'::uuid, 'explain'::public.lte_6e_stage, 3, 'Explain why handoff quality depends on evidence, owner, blocker, and what L1 cannot do.', 'The learner has a completed validation checklist and must prepare a role-safe handoff note. The note must recommend supervisor review, show evidence, identify blockers, name owner, and state action not allowed for L1. Learner must not approve check-in or release key/access.', '{"prerequisites": "Evidence Validation Checklist", "technical_concepts": "Role-Safe Handoff Note Design; Recommendation vs Approval Language; Owner Routing for Arrival Handoff; Key/Access Handoff Boundary; Traceable Service Handoff Record; Accountability in Documentation", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner turns validated evidence into a role-safe recommendation or handoff without approving check-in or releasing access.", "module_continuity": "Handoff note provides the risk/owner/action-not-allowed context for escalation."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('1a4de1c0-6748-503c-b923-d4fbbe62134b'::uuid, 'b6606c1e-a0fd-505f-ba6c-d96e07150bba'::uuid, 'express'::public.lte_6e_stage, 4, 'Learner drafts Action or Handoff Note.', 'The learner has a completed validation checklist and must prepare a role-safe handoff note. The note must recommend supervisor review, show evidence, identify blockers, name owner, and state action not allowed for L1. Learner must not approve check-in or release key/access.', '{"prerequisites": "Evidence Validation Checklist", "technical_concepts": "Role-Safe Handoff Note Design; Recommendation vs Approval Language; Owner Routing for Arrival Handoff; Key/Access Handoff Boundary; Traceable Service Handoff Record; Accountability in Documentation", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner turns validated evidence into a role-safe recommendation or handoff without approving check-in or releasing access.", "module_continuity": "Handoff note provides the risk/owner/action-not-allowed context for escalation."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('faedcab8-16cc-5ac2-8719-4f2fe4f86e4f'::uuid, 'b6606c1e-a0fd-505f-ba6c-d96e07150bba'::uuid, 'empower'::public.lte_6e_stage, 5, 'Learner chooses safe recommendation and action-not-allowed statement.', 'The learner has a completed validation checklist and must prepare a role-safe handoff note. The note must recommend supervisor review, show evidence, identify blockers, name owner, and state action not allowed for L1. Learner must not approve check-in or release key/access.', '{"prerequisites": "Evidence Validation Checklist", "technical_concepts": "Role-Safe Handoff Note Design; Recommendation vs Approval Language; Owner Routing for Arrival Handoff; Key/Access Handoff Boundary; Traceable Service Handoff Record; Accountability in Documentation", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner turns validated evidence into a role-safe recommendation or handoff without approving check-in or releasing access.", "module_continuity": "Handoff note provides the risk/owner/action-not-allowed context for escalation."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('2a22b10b-6a77-53bd-af88-1f4df7b5476f'::uuid, 'b6606c1e-a0fd-505f-ba6c-d96e07150bba'::uuid, 'evolve'::public.lte_6e_stage, 6, 'Learner revises note and passes recommendation/risk/owner/action-not-allowed to Module 4.', 'The learner has a completed validation checklist and must prepare a role-safe handoff note. The note must recommend supervisor review, show evidence, identify blockers, name owner, and state action not allowed for L1. Learner must not approve check-in or release key/access.', '{"prerequisites": "Evidence Validation Checklist", "technical_concepts": "Role-Safe Handoff Note Design; Recommendation vs Approval Language; Owner Routing for Arrival Handoff; Key/Access Handoff Boundary; Traceable Service Handoff Record; Accountability in Documentation", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner turns validated evidence into a role-safe recommendation or handoff without approving check-in or releasing access.", "module_continuity": "Handoff note provides the risk/owner/action-not-allowed context for escalation."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('2e91e4a4-6b9f-5a5b-bc01-8a9ab3c745d4'::uuid, '75003941-b763-5c96-9fff-c47c6e00a5b5'::uuid, 'engage'::public.lte_6e_stage, 1, 'Learner feels workplace pressure as guest waits and multiple blockers remain unresolved.', 'The guest is still waiting, the queue has grown, housekeeping has not updated inspection status, and the payment hold is still visible. Learner must escalate the right blocker to the right owner with evidence and urgency, without letting pressure cause unsafe access or false reassurance.', '{"prerequisites": "Action or Handoff Note", "technical_concepts": "Exception Classification; Escalation Matrix Reading; Supervisor Note Writing; Composure During Conflict; Empathy Without Overpromising; Urgency Without Unsafe Release", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner identifies exceptions, blockers, dependency risks, wrong-owner routes, and pressure traps, then escalates with evidence and safe next step.", "module_continuity": "Escalation note feeds the closure quality review."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('545ba836-22e1-5ccb-9605-07f110bab4a0'::uuid, '75003941-b763-5c96-9fff-c47c6e00a5b5'::uuid, 'explore'::public.lte_6e_stage, 2, 'Learner inspects handoff note, supervisor note, room-status update, and weak escalation draft.', 'The guest is still waiting, the queue has grown, housekeeping has not updated inspection status, and the payment hold is still visible. Learner must escalate the right blocker to the right owner with evidence and urgency, without letting pressure cause unsafe access or false reassurance.', '{"prerequisites": "Action or Handoff Note", "technical_concepts": "Exception Classification; Escalation Matrix Reading; Supervisor Note Writing; Composure During Conflict; Empathy Without Overpromising; Urgency Without Unsafe Release", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner identifies exceptions, blockers, dependency risks, wrong-owner routes, and pressure traps, then escalates with evidence and safe next step.", "module_continuity": "Escalation note feeds the closure quality review."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('909c8b2e-211b-50f3-ba0d-c2cd31414164'::uuid, '75003941-b763-5c96-9fff-c47c6e00a5b5'::uuid, 'explain'::public.lte_6e_stage, 3, 'Explain difference between issue, blocker, risk, owner, urgency, and safe next step.', 'The guest is still waiting, the queue has grown, housekeeping has not updated inspection status, and the payment hold is still visible. Learner must escalate the right blocker to the right owner with evidence and urgency, without letting pressure cause unsafe access or false reassurance.', '{"prerequisites": "Action or Handoff Note", "technical_concepts": "Exception Classification; Escalation Matrix Reading; Supervisor Note Writing; Composure During Conflict; Empathy Without Overpromising; Urgency Without Unsafe Release", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner identifies exceptions, blockers, dependency risks, wrong-owner routes, and pressure traps, then escalates with evidence and safe next step.", "module_continuity": "Escalation note feeds the closure quality review."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('f39245a7-5594-57dc-8bb0-f6645a6f983d'::uuid, '75003941-b763-5c96-9fff-c47c6e00a5b5'::uuid, 'express'::public.lte_6e_stage, 4, 'Learner writes Risk and Escalation Note.', 'The guest is still waiting, the queue has grown, housekeeping has not updated inspection status, and the payment hold is still visible. Learner must escalate the right blocker to the right owner with evidence and urgency, without letting pressure cause unsafe access or false reassurance.', '{"prerequisites": "Action or Handoff Note", "technical_concepts": "Exception Classification; Escalation Matrix Reading; Supervisor Note Writing; Composure During Conflict; Empathy Without Overpromising; Urgency Without Unsafe Release", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner identifies exceptions, blockers, dependency risks, wrong-owner routes, and pressure traps, then escalates with evidence and safe next step.", "module_continuity": "Escalation note feeds the closure quality review."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('c25fc2cc-a73b-5436-90ba-7cb90200a4cd'::uuid, '75003941-b763-5c96-9fff-c47c6e00a5b5'::uuid, 'empower'::public.lte_6e_stage, 5, 'Learner chooses correct escalation route and defends why L1 must not bypass blocker.', 'The guest is still waiting, the queue has grown, housekeeping has not updated inspection status, and the payment hold is still visible. Learner must escalate the right blocker to the right owner with evidence and urgency, without letting pressure cause unsafe access or false reassurance.', '{"prerequisites": "Action or Handoff Note", "technical_concepts": "Exception Classification; Escalation Matrix Reading; Supervisor Note Writing; Composure During Conflict; Empathy Without Overpromising; Urgency Without Unsafe Release", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner identifies exceptions, blockers, dependency risks, wrong-owner routes, and pressure traps, then escalates with evidence and safe next step.", "module_continuity": "Escalation note feeds the closure quality review."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('377f7d0a-1ef1-51a7-9d43-51253ea7fb24'::uuid, '75003941-b763-5c96-9fff-c47c6e00a5b5'::uuid, 'evolve'::public.lte_6e_stage, 6, 'Learner revises escalation note and passes risk/owner/safe next step to Module 5.', 'The guest is still waiting, the queue has grown, housekeeping has not updated inspection status, and the payment hold is still visible. Learner must escalate the right blocker to the right owner with evidence and urgency, without letting pressure cause unsafe access or false reassurance.', '{"prerequisites": "Action or Handoff Note", "technical_concepts": "Exception Classification; Escalation Matrix Reading; Supervisor Note Writing; Composure During Conflict; Empathy Without Overpromising; Urgency Without Unsafe Release", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner identifies exceptions, blockers, dependency risks, wrong-owner routes, and pressure traps, then escalates with evidence and safe next step.", "module_continuity": "Escalation note feeds the closure quality review."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('d9e74c03-979d-50ab-afb1-d471b4277693'::uuid, '3d7514ef-3b3f-551d-b87d-72717114909d'::uuid, 'engage'::public.lte_6e_stage, 1, 'Learner wants to complete the case but must avoid false closure.', 'The learner must prepare closure status without pretending the case is solved. Supervisor review has been requested, but payment hold and room inspection may still be pending. Learner must separate completed L1 work from unresolved owner action and write truthful closure for handoff/review.', '{"prerequisites": "Risk and Escalation Note", "technical_concepts": "Responsible Closure vs Resolution; Quality Check for Arrival Readiness; Remaining Risk Communication; False Closure Detection; Structured Self-Review; Documentation Completeness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner checks whether L1 work is clear, complete, safe, and ready for review/closure while distinguishing completed work from unresolved risks.", "module_continuity": "Quality and Closure Report becomes evidence for final portfolio and transfer case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('73e34b31-e462-52a5-a43e-4fb50ac2af79'::uuid, '3d7514ef-3b3f-551d-b87d-72717114909d'::uuid, 'explore'::public.lte_6e_stage, 2, 'Learner compares false closure note, responsible closure note, and final PMS note.', 'The learner must prepare closure status without pretending the case is solved. Supervisor review has been requested, but payment hold and room inspection may still be pending. Learner must separate completed L1 work from unresolved owner action and write truthful closure for handoff/review.', '{"prerequisites": "Risk and Escalation Note", "technical_concepts": "Responsible Closure vs Resolution; Quality Check for Arrival Readiness; Remaining Risk Communication; False Closure Detection; Structured Self-Review; Documentation Completeness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner checks whether L1 work is clear, complete, safe, and ready for review/closure while distinguishing completed work from unresolved risks.", "module_continuity": "Quality and Closure Report becomes evidence for final portfolio and transfer case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('89c0df2d-a828-58ea-af1f-64890985276b'::uuid, '3d7514ef-3b3f-551d-b87d-72717114909d'::uuid, 'explain'::public.lte_6e_stage, 3, 'Explain difference between L1 work completed, case unresolved, and access readiness not approved.', 'The learner must prepare closure status without pretending the case is solved. Supervisor review has been requested, but payment hold and room inspection may still be pending. Learner must separate completed L1 work from unresolved owner action and write truthful closure for handoff/review.', '{"prerequisites": "Risk and Escalation Note", "technical_concepts": "Responsible Closure vs Resolution; Quality Check for Arrival Readiness; Remaining Risk Communication; False Closure Detection; Structured Self-Review; Documentation Completeness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner checks whether L1 work is clear, complete, safe, and ready for review/closure while distinguishing completed work from unresolved risks.", "module_continuity": "Quality and Closure Report becomes evidence for final portfolio and transfer case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('62f14bd1-7495-5f8b-a806-00e2081fb5d5'::uuid, '3d7514ef-3b3f-551d-b87d-72717114909d'::uuid, 'express'::public.lte_6e_stage, 4, 'Learner drafts Quality and Closure Report.', 'The learner must prepare closure status without pretending the case is solved. Supervisor review has been requested, but payment hold and room inspection may still be pending. Learner must separate completed L1 work from unresolved owner action and write truthful closure for handoff/review.', '{"prerequisites": "Risk and Escalation Note", "technical_concepts": "Responsible Closure vs Resolution; Quality Check for Arrival Readiness; Remaining Risk Communication; False Closure Detection; Structured Self-Review; Documentation Completeness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner checks whether L1 work is clear, complete, safe, and ready for review/closure while distinguishing completed work from unresolved risks.", "module_continuity": "Quality and Closure Report becomes evidence for final portfolio and transfer case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('8b1428a2-dcbc-502d-b036-493819744e56'::uuid, '3d7514ef-3b3f-551d-b87d-72717114909d'::uuid, 'empower'::public.lte_6e_stage, 5, 'Learner chooses closure recommendation and remaining-risk communication.', 'The learner must prepare closure status without pretending the case is solved. Supervisor review has been requested, but payment hold and room inspection may still be pending. Learner must separate completed L1 work from unresolved owner action and write truthful closure for handoff/review.', '{"prerequisites": "Risk and Escalation Note", "technical_concepts": "Responsible Closure vs Resolution; Quality Check for Arrival Readiness; Remaining Risk Communication; False Closure Detection; Structured Self-Review; Documentation Completeness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner checks whether L1 work is clear, complete, safe, and ready for review/closure while distinguishing completed work from unresolved risks.", "module_continuity": "Quality and Closure Report becomes evidence for final portfolio and transfer case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('5627e19e-9dea-5fb2-9bcb-18d82bcf0078'::uuid, '3d7514ef-3b3f-551d-b87d-72717114909d'::uuid, 'evolve'::public.lte_6e_stage, 6, 'Learner revises closure report and passes portfolio proof to Module 6.', 'The learner must prepare closure status without pretending the case is solved. Supervisor review has been requested, but payment hold and room inspection may still be pending. Learner must separate completed L1 work from unresolved owner action and write truthful closure for handoff/review.', '{"prerequisites": "Risk and Escalation Note", "technical_concepts": "Responsible Closure vs Resolution; Quality Check for Arrival Readiness; Remaining Risk Communication; False Closure Detection; Structured Self-Review; Documentation Completeness", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner checks whether L1 work is clear, complete, safe, and ready for review/closure while distinguishing completed work from unresolved risks.", "module_continuity": "Quality and Closure Report becomes evidence for final portfolio and transfer case."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('a139942f-6cae-592b-8362-78c36f3c447c'::uuid, '635864f6-1f2c-5e4c-ae2e-06ffef18a321'::uuid, 'engage'::public.lte_6e_stage, 1, 'Learner sees that portfolio must prove how they think, not only what they filled.', 'The learner assembles portfolio proof and then applies the same readiness method to a new visitor case: corporate visitor Anika Rao arrives for a meeting with guest/company contact, but host confirmation is missing and ID has a minor spelling variation. Learner must defend evidence logic and transfer role-safe escalation without treating visitor access like guest check-in approval.', '{"prerequisites": "All previous artifacts", "technical_concepts": "Evidence Indexing; Decision Traceability; Portfolio QA and PDF Export; Visitor Transfer Case Logic; Interview Storytelling from Evidence; Learning from Feedback", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner assembles evidence chain, defends decisions, applies same logic to a new visitor readiness case, and proves guided L1 capability.", "module_continuity": "Final portfolio pulls all prior artifacts into certification-ready proof."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('44e19266-7aca-5be7-afe5-e5ae2135b76b'::uuid, '635864f6-1f2c-5e4c-ae2e-06ffef18a321'::uuid, 'explore'::public.lte_6e_stage, 2, 'Learner reviews all prior artifacts and new visitor case evidence.', 'The learner assembles portfolio proof and then applies the same readiness method to a new visitor case: corporate visitor Anika Rao arrives for a meeting with guest/company contact, but host confirmation is missing and ID has a minor spelling variation. Learner must defend evidence logic and transfer role-safe escalation without treating visitor access like guest check-in approval.', '{"prerequisites": "All previous artifacts", "technical_concepts": "Evidence Indexing; Decision Traceability; Portfolio QA and PDF Export; Visitor Transfer Case Logic; Interview Storytelling from Evidence; Learning from Feedback", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner assembles evidence chain, defends decisions, applies same logic to a new visitor readiness case, and proves guided L1 capability.", "module_continuity": "Final portfolio pulls all prior artifacts into certification-ready proof."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('7c465d87-e8f1-5e10-bfe6-28e88d9967de'::uuid, '635864f6-1f2c-5e4c-ae2e-06ffef18a321'::uuid, 'explain'::public.lte_6e_stage, 3, 'Explain transfer: same evidence-readiness method, different guest/visitor evidence and authority limits.', 'The learner assembles portfolio proof and then applies the same readiness method to a new visitor case: corporate visitor Anika Rao arrives for a meeting with guest/company contact, but host confirmation is missing and ID has a minor spelling variation. Learner must defend evidence logic and transfer role-safe escalation without treating visitor access like guest check-in approval.', '{"prerequisites": "All previous artifacts", "technical_concepts": "Evidence Indexing; Decision Traceability; Portfolio QA and PDF Export; Visitor Transfer Case Logic; Interview Storytelling from Evidence; Learning from Feedback", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner assembles evidence chain, defends decisions, applies same logic to a new visitor readiness case, and proves guided L1 capability.", "module_continuity": "Final portfolio pulls all prior artifacts into certification-ready proof."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('43801986-7a75-58c2-8b17-70b45a7a32be'::uuid, '635864f6-1f2c-5e4c-ae2e-06ffef18a321'::uuid, 'express'::public.lte_6e_stage, 4, 'Learner assembles Final Portfolio Pack and drafts decision defense.', 'The learner assembles portfolio proof and then applies the same readiness method to a new visitor case: corporate visitor Anika Rao arrives for a meeting with guest/company contact, but host confirmation is missing and ID has a minor spelling variation. Learner must defend evidence logic and transfer role-safe escalation without treating visitor access like guest check-in approval.', '{"prerequisites": "All previous artifacts", "technical_concepts": "Evidence Indexing; Decision Traceability; Portfolio QA and PDF Export; Visitor Transfer Case Logic; Interview Storytelling from Evidence; Learning from Feedback", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner assembles evidence chain, defends decisions, applies same logic to a new visitor readiness case, and proves guided L1 capability.", "module_continuity": "Final portfolio pulls all prior artifacts into certification-ready proof."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('6a34e716-8f9d-513a-aa0a-0fd662e0fc9d'::uuid, '635864f6-1f2c-5e4c-ae2e-06ffef18a321'::uuid, 'empower'::public.lte_6e_stage, 5, 'Learner applies method to visitor case and defends safe escalation/role boundary.', 'The learner assembles portfolio proof and then applies the same readiness method to a new visitor case: corporate visitor Anika Rao arrives for a meeting with guest/company contact, but host confirmation is missing and ID has a minor spelling variation. Learner must defend evidence logic and transfer role-safe escalation without treating visitor access like guest check-in approval.', '{"prerequisites": "All previous artifacts", "technical_concepts": "Evidence Indexing; Decision Traceability; Portfolio QA and PDF Export; Visitor Transfer Case Logic; Interview Storytelling from Evidence; Learning from Feedback", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner assembles evidence chain, defends decisions, applies same logic to a new visitor readiness case, and proves guided L1 capability.", "module_continuity": "Final portfolio pulls all prior artifacts into certification-ready proof."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."modules_content" ("id", "module_id", "stage_name", "stage_order", "stage_description", "module_context", "curriculum_reference", "is_active")
VALUES ('dba44b31-95f6-5e72-8119-cd6100bbd1b2'::uuid, '635864f6-1f2c-5e4c-ae2e-06ffef18a321'::uuid, 'evolve'::public.lte_6e_stage, 6, 'Learner improves portfolio and identifies how to use the same method in future arrival-readiness work.', 'The learner assembles portfolio proof and then applies the same readiness method to a new visitor case: corporate visitor Anika Rao arrives for a meeting with guest/company contact, but host confirmation is missing and ID has a minor spelling variation. Learner must defend evidence logic and transfer role-safe escalation without treating visitor access like guest check-in approval.', '{"prerequisites": "All previous artifacts", "technical_concepts": "Evidence Indexing; Decision Traceability; Portfolio QA and PDF Export; Visitor Transfer Case Logic; Interview Storytelling from Evidence; Learning from Feedback", "workplace_context": "Guest and visitor arrival readiness", "when_to_use": "Learner assembles evidence chain, defends decisions, applies same logic to a new visitor readiness case, and proves guided L1 capability.", "module_continuity": "Final portfolio pulls all prior artifacts into certification-ready proof."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;

COMMIT;
