-- Generated from LTE_LEARNING_CATALOG_CAP037_L1_L2_L3_L4_L5_BLOCKERS_CORRECTED.xlsx: public.artifact_questions.
-- Edit the Excel template and rerun scripts/excel_to_lte_seed.py.
-- ON CONFLICT DO NOTHING keeps this seed safe to rerun.

BEGIN;

-- public.artifact_questions
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('73050239-27ae-581c-a874-9c8d38ec6dcc'::uuid, '5e1e45f2-9e32-5055-8fb1-338d9a25b8d0'::uuid, 1, 'Complete the GenAI Workflow Entry Record', 'Create an evidence-linked observation showing what was noticed, which supplied record was checked, what remains uncertain and that the record is being submitted to the GenAI Workflow Owner rather than treated as a decision.', '{"required_fields": "the course and learner role, case anchor, course mission, evidence types, visible facts, unknown information, risk, L1 allowed actions, L1 prohibited actions, evidence-before-action statement, behaviour commitment, promise-safe response, open validation question, and Module 1 handoff.", "pass_criteria": "The learner completes every required artifact field, links observations to supplied evidence, records uncertainty and the required handoff, preserves A01/A02 improvement proof, and remains within the stated L1 recognition-and-handoff boundary.", "critical_fail": "The learner invents evidence, changes or approves the response, publishes or closes the case, or claims decision authority beyond the L1 inspection-and-handoff role."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('8e44bc6c-47c9-59ad-9166-72dbbe455bbb'::uuid, '50680fa9-d2c5-5b8d-bd1d-d5579dbc5a13'::uuid, 1, 'Complete the Annotated GenAI Workflow Map', 'Create a complete annotated map of all supplied objects, their roles, their controlled relationships, the unconfirmed source connection and the explicit handoff to OWN-001.', '{"required_fields": "case ID, workflow-object inventory, object IDs, object roles, confirmed relationships, unconfirmed source connection, uncertainty note, ownership boundary, escalation point, and handoff to OWN-001.", "pass_criteria": "The learner completes every required artifact field, links observations to supplied evidence, records uncertainty and the required handoff, preserves A01/A02 improvement proof, and remains within the stated L1 recognition-and-handoff boundary.", "critical_fail": "The learner invents evidence, changes or approves the response, publishes or closes the case, or claims decision authority beyond the L1 inspection-and-handoff role."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('4cfd53a6-a622-5184-90a6-62ddc6987649'::uuid, 'e2b3beb5-7170-5b95-96e6-779d47eca0aa'::uuid, 1, 'Complete the Evidence Classification Register', 'Create a traceable register that lists each controlled claim, the evidence checked, the correct classification, exact supporting excerpt, uncertainty and a neutral reviewer note.', '{"required_fields": "claim ID, claim text, evidence source, exact excerpt, evidence or assumption classification, confidence, unknown information, risk note, neutral reviewer note, and required owner review.", "pass_criteria": "The learner completes every required artifact field, links observations to supplied evidence, records uncertainty and the required handoff, preserves A01/A02 improvement proof, and remains within the stated L1 recognition-and-handoff boundary.", "critical_fail": "The learner invents evidence, changes or approves the response, publishes or closes the case, or claims decision authority beyond the L1 inspection-and-handoff role."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('73dd1223-d1d3-5a34-9abc-b28f1e31b6cb'::uuid, '0842e16b-5293-5fff-ab65-d6f37718bd61'::uuid, 1, 'Complete the GenAI Response Signal Scan', 'Create a signal scan containing the signal ID, location, exact evidence, signal group, controlled label, approved priority and role-safe reviewer note for each required signal.', '{"required_fields": "signal ID, signal location, exact evidence, signal group, controlled label, priority, uncertainty, boundary implication, reviewer note, and required handoff.", "pass_criteria": "The learner completes every required artifact field, links observations to supplied evidence, records uncertainty and the required handoff, preserves A01/A02 improvement proof, and remains within the stated L1 recognition-and-handoff boundary.", "critical_fail": "The learner invents evidence, changes or approves the response, publishes or closes the case, or claims decision authority beyond the L1 inspection-and-handoff role."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('7968b88f-6fa9-57ba-8bfa-49796d58d6e5'::uuid, '682673ae-9153-5f81-8466-229e00a85380'::uuid, 1, 'Complete the GenAI Workflow Review Handoff Pack', 'Create one consolidated six-section handoff containing case identity, review context, confirmed evidence, unresolved items, priority signal summary and an authority-safe handoff note to OWN-001.', '{"required_fields": "case identity, review context, confirmed evidence, unresolved items, priority signals, risk summary, authority boundary, accountable receiver, handoff note, and open validation question.", "pass_criteria": "The learner completes every required artifact field, links observations to supplied evidence, records uncertainty and the required handoff, preserves A01/A02 improvement proof, and remains within the stated L1 recognition-and-handoff boundary.", "critical_fail": "The learner invents evidence, changes or approves the response, publishes or closes the case, or claims decision authority beyond the L1 inspection-and-handoff role."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('84413a5b-aae2-58f9-b2fc-3432e7cb50c9'::uuid, 'd5c03703-f95a-5f64-b332-9a0b8ca91276'::uuid, 1, 'Complete the Safe First Review Action Record', 'Create one action record for the assigned S-006 issue that includes exact evidence, permitted action category, required owner review, accountable receiver, preserved uncertainty and an explicit learner authority boundary.', '{"required_fields": "assigned issue ID, exact evidence, risk, permitted action category, prohibited action, accountable owner, required review, preserved uncertainty, safe first action, and handoff statement.", "pass_criteria": "The learner completes every required artifact field, links observations to supplied evidence, records uncertainty and the required handoff, preserves A01/A02 improvement proof, and remains within the stated L1 recognition-and-handoff boundary.", "critical_fail": "The learner invents evidence, changes or approves the response, publishes or closes the case, or claims decision authority beyond the L1 inspection-and-handoff role."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('dcd0e254-b54e-5a33-bcf9-8ca51985b8e0'::uuid, '26b9b371-3215-589e-aa19-f5e9444fe476'::uuid, 1, 'Complete the L1 Evidence Review Portfolio and Transfer Pack', 'Create a final portfolio pack containing the selected evidence from M0–M5, A01/A02 improvement proof, reflection, and a completed parallel-case workflow review artifact demonstrating independent L1 recognition and handoff.', '{"required_fields": "portfolio index, selected M0–M5 evidence, evidence-to-decision links, A01 and A02 improvement proof, role-boundary proof, reflection, transfer-case evidence, transfer decision, residual uncertainty, and future development action.", "pass_criteria": "The learner completes every required artifact field, links observations to supplied evidence, records uncertainty and the required handoff, preserves A01/A02 improvement proof, and remains within the stated L1 recognition-and-handoff boundary.", "critical_fail": "The learner invents evidence, changes or approves the response, publishes or closes the case, or claims decision authority beyond the L1 inspection-and-handoff role."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('25faf29f-754a-5d9e-a29f-abba9e517c2e'::uuid, '752d6553-615f-51bf-ae79-fc6fa76ffd92'::uuid, 1, 'Complete the L2 Readiness and Authority Record', 'Create a readiness record that identifies the assigned role, allowed tools, editable fields, locked controls, escalation triggers and the learner’s confirmation that only authorised sandbox actions will be performed.', '{"required_fields": "assigned role, approved tools, editable fields, locked controls, permitted sandbox actions, prohibited actions, escalation triggers, evidence-preservation duties, supervisor confirmation, and readiness declaration.", "pass_criteria": "The learner completes every required artifact field using the approved template and supplied controls, records traceable evidence and any required escalation, preserves A01/A02 improvement proof, and performs only authorised supported sandbox actions.", "critical_fail": "The learner uses an unapproved source, changes a protected control, performs an unauthorised workflow change, deploys to production, approves output, or closes an exception."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('9485d7d1-83c9-50c5-ab03-ab76b7244a4a'::uuid, 'c8e2ac6b-c26b-562f-97a4-9eb5197d85cb'::uuid, 1, 'Complete the Workflow Requirement Brief', 'Create a structured brief covering objective, users, input, output, approved sources, constraints, success conditions, missing information, assumptions requiring confirmation and owner decisions.', '{"required_fields": "workflow objective, intended users, inputs, outputs, approved sources, constraints, success conditions, missing information, assumptions requiring confirmation, owner decisions, and requirement version.", "pass_criteria": "The learner completes every required artifact field using the approved template and supplied controls, records traceable evidence and any required escalation, preserves A01/A02 improvement proof, and performs only authorised supported sandbox actions.", "critical_fail": "The learner uses an unapproved source, changes a protected control, performs an unauthorised workflow change, deploys to production, approves output, or closes an exception."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('4d0b61f1-f23e-52fd-b1f8-99291ef0da86'::uuid, '0d04dbfc-18c2-550b-8174-019266f290e9'::uuid, 1, 'Complete the Prompt Assembly Record', 'Create a versioned prompt assembly record containing role, task, context, approved evidence, constraints, output format, boundary instructions, traceability to requirements and change notes.', '{"required_fields": "prompt version, role instruction, task instruction, approved context, evidence references, constraints, output format, boundary instructions, requirement traceability, change note, and reviewer status.", "pass_criteria": "The learner completes every required artifact field using the approved template and supplied controls, records traceable evidence and any required escalation, preserves A01/A02 improvement proof, and performs only authorised supported sandbox actions.", "critical_fail": "The learner uses an unapproved source, changes a protected control, performs an unauthorised workflow change, deploys to production, approves output, or closes an exception."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('4b2a6b6b-52f5-5fb6-9c45-7d4f78ef11de'::uuid, '6d1a2601-8141-560f-b2dd-4f865bfac025'::uuid, 1, 'Complete the Source Connection Checklist', 'Create a checklist showing source ID, status, permitted use, connection requirement, connection evidence, restricted-content boundary, unresolved traceability and reviewer confirmation needed.', '{"required_fields": "source ID, source status, permitted use, restricted-use boundary, connection requirement, connection evidence, traceability status, unresolved issue, reviewer confirmation required, and version note.", "pass_criteria": "The learner completes every required artifact field using the approved template and supplied controls, records traceable evidence and any required escalation, preserves A01/A02 improvement proof, and performs only authorised supported sandbox actions.", "critical_fail": "The learner uses an unapproved source, changes a protected control, performs an unauthorised workflow change, deploys to production, approves output, or closes an exception."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('ab9887d4-8704-5d94-a65b-97fca2cc729a'::uuid, '3771c8a0-2172-50ef-aea9-f1f64630928d'::uuid, 1, 'Complete the Sandbox Configuration Record', 'Create a configuration record showing the original state, assigned changes, editable and locked fields, entered values, saved version, validation evidence and any blocked or escalated item.', '{"required_fields": "original configuration state, assigned changes, editable fields, locked controls, entered values, saved version, validation evidence, blocked item, escalation note, and supervisor review status.", "pass_criteria": "The learner completes every required artifact field using the approved template and supplied controls, records traceable evidence and any required escalation, preserves A01/A02 improvement proof, and performs only authorised supported sandbox actions.", "critical_fail": "The learner uses an unapproved source, changes a protected control, performs an unauthorised workflow change, deploys to production, approves output, or closes an exception."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('3f271883-2fa8-5a80-a043-dec7cb948f5c'::uuid, '900c3c1b-2666-5939-b2cc-ff261bcf98c4'::uuid, 1, 'Complete the Test Execution Log', 'Create a test log containing test case ID, input, expected condition, actual output, evidence capture, pass/deviation status, deviation category, permitted next step and unresolved issue.', '{"required_fields": "test case ID, test input, expected condition, actual output, evidence capture, pass or deviation status, deviation category, permitted next step, unresolved issue, and escalation decision.", "pass_criteria": "The learner completes every required artifact field using the approved template and supplied controls, records traceable evidence and any required escalation, preserves A01/A02 improvement proof, and performs only authorised supported sandbox actions.", "critical_fail": "The learner uses an unapproved source, changes a protected control, performs an unauthorised workflow change, deploys to production, approves output, or closes an exception."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('152ff5f4-0e23-563a-8396-dc7d240902eb'::uuid, '1085831e-4c42-5856-baad-a6c09ac63e48'::uuid, 1, 'Complete the Supported GenAI Workflow Build and Test Pack', 'Create a final integrated pack containing requirements, prompt version, approved source connection, sandbox setup, test evidence, authorised revision, retest result, unresolved exception, version history and owner handoff.', '{"required_fields": "requirement brief, prompt version, approved source connection, sandbox configuration, test evidence, authorised revision, retest result, unresolved exception, version history, owner handoff, and release-boundary statement.", "pass_criteria": "The learner completes every required artifact field using the approved template and supplied controls, records traceable evidence and any required escalation, preserves A01/A02 improvement proof, and performs only authorised supported sandbox actions.", "critical_fail": "The learner uses an unapproved source, changes a protected control, performs an unauthorised workflow change, deploys to production, approves output, or closes an exception."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('5ec44e47-d9ac-5bd4-af54-9898285acac8'::uuid, '6fb6285a-d4a0-50d3-b092-0850dbd2cae7'::uuid, 1, 'Complete the L3 Builder Readiness and Authority Record', 'Create a readiness record defining independent routine authority, mandatory standards, escalation triggers, approved system surfaces and evidence that must be preserved throughout the build.', '{"required_fields": "independent routine authority, mandatory standards, approved system surfaces, evidence-preservation requirements, non-routine triggers, escalation route, prohibited decisions, owner dependencies, readiness risks, and readiness confirmation.", "pass_criteria": "The learner produces a complete, traceable and testable standard-workflow artifact, connects decisions to approved requirements and evidence, records routine corrections and escalations, preserves A01/A02 improvement proof, and remains within L3 independent standard-work authority.", "critical_fail": "The learner bypasses an approved pattern or control, treats a non-routine or high-risk issue as routine, uses unapproved context, or claims final production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('6688d5e3-60bc-57fc-ac07-e53b52058661'::uuid, '006ac214-c19e-5351-a550-31c2b4752ff3'::uuid, 1, 'Complete the Workflow Objective and Acceptance Criteria Brief', 'Create a brief containing objective, users, inputs, outputs, approved context, functional criteria, quality criteria, boundary criteria, testable acceptance conditions and unresolved non-routine decisions.', '{"required_fields": "workflow objective, users, inputs, outputs, approved context, functional criteria, quality criteria, boundary criteria, testable acceptance conditions, unresolved non-routine decisions, and owner confirmation needs.", "pass_criteria": "The learner produces a complete, traceable and testable standard-workflow artifact, connects decisions to approved requirements and evidence, records routine corrections and escalations, preserves A01/A02 improvement proof, and remains within L3 independent standard-work authority.", "critical_fail": "The learner bypasses an approved pattern or control, treats a non-routine or high-risk issue as routine, uses unapproved context, or claims final production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('c281fa07-c68b-5478-8465-b3626b162617'::uuid, 'cd046cba-a5d6-5298-9b18-5e3e0f948f53'::uuid, 1, 'Complete the Prompt Workflow Design Record', 'Create a complete design record showing prompt stages, instruction hierarchy, context placement, constraints, output schema, failure handling, version rationale and traceability to acceptance criteria.', '{"required_fields": "workflow stages, instruction hierarchy, context placement, constraints, output schema, failure handling, control points, version rationale, acceptance-criteria traceability, and unresolved design risk.", "pass_criteria": "The learner produces a complete, traceable and testable standard-workflow artifact, connects decisions to approved requirements and evidence, records routine corrections and escalations, preserves A01/A02 improvement proof, and remains within L3 independent standard-work authority.", "critical_fail": "The learner bypasses an approved pattern or control, treats a non-routine or high-risk issue as routine, uses unapproved context, or claims final production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('e0848375-c5d4-58db-87d1-cc665d5190ca'::uuid, 'ba2f1856-d4af-5c56-8f4b-688051ad48a9'::uuid, 1, 'Complete the Context Configuration and Retrieval Record', 'Create a record covering approved sources, retrieval scope, filters, ranking or selection rules, fallback behaviour, restricted-content controls, traceability evidence and escalated exceptions.', '{"required_fields": "approved sources, retrieval scope, filters, ranking or selection rules, fallback behaviour, restricted-content controls, traceability evidence, test requirement, unresolved exception, and escalation route.", "pass_criteria": "The learner produces a complete, traceable and testable standard-workflow artifact, connects decisions to approved requirements and evidence, records routine corrections and escalations, preserves A01/A02 improvement proof, and remains within L3 independent standard-work authority.", "critical_fail": "The learner bypasses an approved pattern or control, treats a non-routine or high-risk issue as routine, uses unapproved context, or claims final production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('b9c48fee-47a9-51a9-b944-6719d6dcdf45'::uuid, 'b1c6f0d8-ed70-543d-8a30-b7fd3d1a33fe'::uuid, 1, 'Complete the Workflow Validation Test Plan', 'Create a validation plan containing test objectives, test cases, input variations, expected results, evidence capture, pass/fail rules, boundary tests, regression coverage and escalation criteria.', '{"required_fields": "test objectives, test cases, input variations, expected results, evidence capture method, pass or fail rules, boundary tests, regression coverage, defect-routing rule, and escalation criteria.", "pass_criteria": "The learner produces a complete, traceable and testable standard-workflow artifact, connects decisions to approved requirements and evidence, records routine corrections and escalations, preserves A01/A02 improvement proof, and remains within L3 independent standard-work authority.", "critical_fail": "The learner bypasses an approved pattern or control, treats a non-routine or high-risk issue as routine, uses unapproved context, or claims final production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('4d5dbf96-f59a-58cc-9c6a-eb27cbd5fdf6'::uuid, '49fd2be1-b49a-51c6-a8c4-cabef785573c'::uuid, 1, 'Complete the Test Run and Routine Defect Resolution Log', 'Create a log showing each test run, actual result, defect evidence, routine/non-routine classification, permitted correction, changed version, retest evidence and unresolved escalation.', '{"required_fields": "test run ID, actual result, defect evidence, routine or non-routine classification, permitted correction, changed version, retest evidence, acceptance impact, unresolved issue, and escalation record.", "pass_criteria": "The learner produces a complete, traceable and testable standard-workflow artifact, connects decisions to approved requirements and evidence, records routine corrections and escalations, preserves A01/A02 improvement proof, and remains within L3 independent standard-work authority.", "critical_fail": "The learner bypasses an approved pattern or control, treats a non-routine or high-risk issue as routine, uses unapproved context, or claims final production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('512673f5-8a76-532c-925f-4ffb6cd8117d'::uuid, '9a2933e3-6504-54cb-8a7f-7bda432b57e1'::uuid, 1, 'Complete the Standard GenAI Workflow Validation Handoff Pack', 'Create a final pack containing objective, design, context controls, test plan, test results, resolved defects, residual issues, acceptance-criteria evaluation, version history and release recommendation for accountable owner decision.', '{"required_fields": "workflow objective, final design, context controls, validation plan, test results, resolved defects, residual issues, acceptance-criteria evaluation, version history, recommendation, and accountable owner decision.", "pass_criteria": "The learner produces a complete, traceable and testable standard-workflow artifact, connects decisions to approved requirements and evidence, records routine corrections and escalations, preserves A01/A02 improvement proof, and remains within L3 independent standard-work authority.", "critical_fail": "The learner bypasses an approved pattern or control, treats a non-routine or high-risk issue as routine, uses unapproved context, or claims final production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('58fa695f-da04-547e-b599-c169ddffdad9'::uuid, '7b61ec91-7cbb-5b54-bd2d-33b37f8e90f3'::uuid, 1, 'Complete the Adaptive Authority and Ambiguity Readiness Record', 'Create a readiness record covering adaptive decision rights, ambiguity-handling rules, evidence thresholds, trade-off documentation, stakeholder ownership and mandatory escalation conditions.', '{"required_fields": "adaptive decision rights, ambiguity-handling rules, evidence thresholds, trade-off documentation rules, stakeholder ownership, mandatory escalation conditions, prohibited authority, consultation duties, readiness risks, and readiness declaration.", "pass_criteria": "The learner produces a defensible adaptive artifact that distinguishes evidence, assumptions, options, trade-offs and residual risks, records accountable escalation and A01/A02 improvement proof, and remains within the L4 recommendation boundary.", "critical_fail": "The learner hides material uncertainty or residual risk, bypasses governance, makes an unsupported policy decision, or independently authorises production release."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('f34d2cd0-1262-5f41-b017-f8a58896a704'::uuid, '6219194c-375d-553d-8395-b8115b1fa5fd'::uuid, 1, 'Complete the Ambiguous Workflow Change Interpretation Brief', 'Create an interpretation brief containing confirmed needs, ambiguous statements, assumptions, competing constraints, stakeholder questions, impact areas, decision dependencies and a controlled problem definition.', '{"required_fields": "confirmed needs, ambiguous statements, assumptions, competing constraints, stakeholder questions, impact areas, decision dependencies, evidence gaps, controlled problem definition, and escalation needs.", "pass_criteria": "The learner produces a defensible adaptive artifact that distinguishes evidence, assumptions, options, trade-offs and residual risks, records accountable escalation and A01/A02 improvement proof, and remains within the L4 recommendation boundary.", "critical_fail": "The learner hides material uncertainty or residual risk, bypasses governance, makes an unsupported policy decision, or independently authorises production release."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('07700b3d-b78b-50dd-acc5-e7bddbbc3861'::uuid, '6331aeb5-d9cf-50ec-a805-e354707fb360'::uuid, 1, 'Complete the Adaptive Prompt and Workflow Option Comparison Matrix', 'Create a comparison matrix of design options showing intended benefit, evidence basis, constraints, trade-offs, risks, reversibility, test implications and recommendation rationale.', '{"required_fields": "design option, intended benefit, evidence basis, constraints, trade-offs, risks, reversibility, test implications, stakeholder impact, recommendation rationale, and unresolved dependency.", "pass_criteria": "The learner produces a defensible adaptive artifact that distinguishes evidence, assumptions, options, trade-offs and residual risks, records accountable escalation and A01/A02 improvement proof, and remains within the L4 recommendation boundary.", "critical_fail": "The learner hides material uncertainty or residual risk, bypasses governance, makes an unsupported policy decision, or independently authorises production release."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('005647d4-51c5-503b-9300-9671ffef46c8'::uuid, '4ce5dbaf-c039-57c3-80c6-3d762b6adeb3'::uuid, 1, 'Complete the Context Adaptation and Retrieval Risk Record', 'Create a record showing proposed context changes, source eligibility, retrieval trade-offs, leakage and relevance risks, safeguards, test needs, residual uncertainty and escalation points.', '{"required_fields": "proposed context change, source eligibility, retrieval trade-offs, leakage risk, relevance risk, safeguards, test needs, residual uncertainty, escalation point, and accountable owner decision.", "pass_criteria": "The learner produces a defensible adaptive artifact that distinguishes evidence, assumptions, options, trade-offs and residual risks, records accountable escalation and A01/A02 improvement proof, and remains within the L4 recommendation boundary.", "critical_fail": "The learner hides material uncertainty or residual risk, bypasses governance, makes an unsupported policy decision, or independently authorises production release."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('18449455-ebb0-5485-bd50-b277049da2c5'::uuid, 'c99730d6-5a18-56df-af4b-504fb87eacd6'::uuid, 1, 'Complete the Adaptive Workflow Test Coverage Plan', 'Create a plan containing scenario families, edge cases, competing-constraint tests, boundary tests, expected evidence, comparison criteria, risk-based priorities and unresolved coverage limits.', '{"required_fields": "scenario families, edge cases, competing-constraint tests, boundary tests, expected evidence, comparison criteria, risk-based priority, coverage limit, escalation trigger, and review owner.", "pass_criteria": "The learner produces a defensible adaptive artifact that distinguishes evidence, assumptions, options, trade-offs and residual risks, records accountable escalation and A01/A02 improvement proof, and remains within the L4 recommendation boundary.", "critical_fail": "The learner hides material uncertainty or residual risk, bypasses governance, makes an unsupported policy decision, or independently authorises production release."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('639b6419-e810-580a-a79f-465f8ab00109'::uuid, 'd5cab8a5-4a9f-5530-aad0-f52b5a4b9882'::uuid, 1, 'Complete the Adaptive Test Evidence Evaluation Record', 'Create an evaluation record showing evidence by scenario, conflicting results, trade-offs, confidence, residual risk, limitations, comparison with acceptance criteria and recommendation implications.', '{"required_fields": "scenario evidence, conflicting results, trade-offs, confidence, residual risk, limitations, acceptance-criteria comparison, recommendation implication, unresolved uncertainty, and escalation requirement.", "pass_criteria": "The learner produces a defensible adaptive artifact that distinguishes evidence, assumptions, options, trade-offs and residual risks, records accountable escalation and A01/A02 improvement proof, and remains within the L4 recommendation boundary.", "critical_fail": "The learner hides material uncertainty or residual risk, bypasses governance, makes an unsupported policy decision, or independently authorises production release."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('a70ee02d-770d-5e66-8e29-fc3120d79e54'::uuid, '38187024-bc61-581c-bd91-9a937d07fe6c'::uuid, 1, 'Complete the Adaptive GenAI Workflow Design Recommendation Pack', 'Create a recommendation pack containing problem framing, option comparison, selected design, rationale, context controls, test evidence, trade-offs, residual risks, implementation conditions and accountable approval requirements.', '{"required_fields": "problem framing, option comparison, selected design, rationale, context controls, test evidence, trade-offs, residual risks, implementation conditions, accountable approval requirements, and review cadence.", "pass_criteria": "The learner produces a defensible adaptive artifact that distinguishes evidence, assumptions, options, trade-offs and residual risks, records accountable escalation and A01/A02 improvement proof, and remains within the L4 recommendation boundary.", "critical_fail": "The learner hides material uncertainty or residual risk, bypasses governance, makes an unsupported policy decision, or independently authorises production release."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('f46117ae-dbb6-56e6-89a4-4a33868955e2'::uuid, '7875e32f-10fb-5735-8b84-69af6498a280'::uuid, 1, 'Complete the Leadership Authority and Governance Readiness Record', 'Create a readiness record defining practice-lead authority, governance responsibilities, accountable business and control owners, evidence requirements, consultation duties and non-delegable approval boundaries.', '{"required_fields": "practice-lead authority, governance responsibilities, accountable business owner, legal owner, privacy owner, security owner, evidence requirements, consultation duties, non-delegable approvals, and readiness declaration.", "pass_criteria": "The learner produces a complete practice-level artifact with traceable standards, governance controls, ownership, evidence, adoption or improvement logic, preserves A01/A02 improvement proof, and maintains accountable business, legal, privacy, security and release boundaries.", "critical_fail": "The learner removes accountable ownership, treats governance guidance as final legal, privacy, security or business approval, or claims unilateral production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('5bb227ae-1e5b-5eb4-8004-abd9532e8f86'::uuid, 'a679624b-59cc-5921-8a0f-b5fd6a43c7f4'::uuid, 1, 'Complete the GenAI Workflow Design Standard', 'Create an organisational standard covering scope, required design elements, evidence requirements, minimum controls, validation expectations, exceptions, ownership, review cadence and adoption guidance.', '{"required_fields": "standard scope, required design elements, evidence requirements, minimum controls, validation expectations, exception process, ownership, review cadence, adoption guidance, and change-control rule.", "pass_criteria": "The learner produces a complete practice-level artifact with traceable standards, governance controls, ownership, evidence, adoption or improvement logic, preserves A01/A02 improvement proof, and maintains accountable business, legal, privacy, security and release boundaries.", "critical_fail": "The learner removes accountable ownership, treats governance guidance as final legal, privacy, security or business approval, or claims unilateral production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('a4ce9731-14fa-53d6-ba24-8499a696c938'::uuid, '8d84df78-1774-5927-b717-4c5a62edf5c5'::uuid, 1, 'Complete the Prompt and Context Pattern Library Entry', 'Create a governed pattern entry containing problem type, context of use, pattern structure, approved examples, required controls, anti-patterns, limitations, evidence of effectiveness, ownership and maintenance rules.', '{"required_fields": "problem type, context of use, pattern structure, approved example, required controls, anti-patterns, limitations, effectiveness evidence, owner, maintenance rule, and retirement trigger.", "pass_criteria": "The learner produces a complete practice-level artifact with traceable standards, governance controls, ownership, evidence, adoption or improvement logic, preserves A01/A02 improvement proof, and maintains accountable business, legal, privacy, security and release boundaries.", "critical_fail": "The learner removes accountable ownership, treats governance guidance as final legal, privacy, security or business approval, or claims unilateral production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('94cace9f-a473-528c-9d79-8088645ac941'::uuid, '69982da9-13bb-55e6-b87a-740c6f60596b'::uuid, 1, 'Complete the Evaluation and Governance Control Plan', 'Create a control plan defining evaluation layers, required test evidence, thresholds, exception routing, review roles, monitoring cadence, audit evidence, change control and governance decisions.', '{"required_fields": "evaluation layers, required test evidence, thresholds, exception routing, review roles, monitoring cadence, audit evidence, change control, governance decisions, and accountable owners.", "pass_criteria": "The learner produces a complete practice-level artifact with traceable standards, governance controls, ownership, evidence, adoption or improvement logic, preserves A01/A02 improvement proof, and maintains accountable business, legal, privacy, security and release boundaries.", "critical_fail": "The learner removes accountable ownership, treats governance guidance as final legal, privacy, security or business approval, or claims unilateral production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('f944938d-f811-51e8-a309-10d15643b435'::uuid, 'a53776fe-e637-5ee3-8b50-d5de2efc97ac'::uuid, 1, 'Complete the Systemic Workflow Weakness Analysis', 'Create an analysis containing recurring evidence patterns, affected workflows, contributing conditions, control gaps, impact, confidence, prioritised improvement opportunities and evidence still required.', '{"required_fields": "recurring evidence patterns, affected workflows, contributing conditions, control gaps, impact, confidence, systemic risk, prioritised improvement opportunities, evidence still required, and accountable owner.", "pass_criteria": "The learner produces a complete practice-level artifact with traceable standards, governance controls, ownership, evidence, adoption or improvement logic, preserves A01/A02 improvement proof, and maintains accountable business, legal, privacy, security and release boundaries.", "critical_fail": "The learner removes accountable ownership, treats governance guidance as final legal, privacy, security or business approval, or claims unilateral production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('d5aa8941-1cf2-5d48-b0e7-965d08cb0a15'::uuid, '3bef052c-b434-51a2-b146-733905c7a519'::uuid, 1, 'Complete the Reviewer Coaching and Practice Improvement Plan', 'Create a plan containing target behaviours, observed gaps, coaching activities, practice cases, feedback model, calibration method, success evidence, follow-up cadence and escalation for persistent risk.', '{"required_fields": "target behaviours, observed gaps, coaching activities, practice cases, feedback model, calibration method, success evidence, follow-up cadence, persistent-risk escalation, and accountable reviewer owner.", "pass_criteria": "The learner produces a complete practice-level artifact with traceable standards, governance controls, ownership, evidence, adoption or improvement logic, preserves A01/A02 improvement proof, and maintains accountable business, legal, privacy, security and release boundaries.", "critical_fail": "The learner removes accountable ownership, treats governance guidance as final legal, privacy, security or business approval, or claims unilateral production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;
INSERT INTO public."artifact_questions" ("id", "artifact_id", "question_order", "title", "description", "instructions", "is_active")
VALUES ('c9907bfb-fdd9-5a99-8e9e-b83c8c99bc15'::uuid, '3881e8c8-1e23-53d4-be4b-4dcc2670d3eb'::uuid, 1, 'Complete the GenAI Workflow Governance and Scale Pack', 'Create a final governance pack containing operating model, design standard, pattern library structure, evaluation controls, issue and exception governance, capability plan, adoption roadmap, metrics, review cadence and accountable decision ownership.', '{"required_fields": "operating model, design standard, pattern-library structure, evaluation controls, issue governance, exception governance, capability plan, adoption roadmap, metrics, review cadence, and accountable decision ownership.", "pass_criteria": "The learner produces a complete practice-level artifact with traceable standards, governance controls, ownership, evidence, adoption or improvement logic, preserves A01/A02 improvement proof, and maintains accountable business, legal, privacy, security and release boundaries.", "critical_fail": "The learner removes accountable ownership, treats governance guidance as final legal, privacy, security or business approval, or claims unilateral production-release authority."}'::jsonb, TRUE)
ON CONFLICT DO NOTHING;

COMMIT;
